Repository kubeflow/kfp-tekton, pull requests merged in 2019-10, with the labels that each got.

#1 Adding Andrea as a reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#2 Adding more reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#3 Initializing the repo
  .gitignore
  CONTRIBUTING.md
  README.md
  kfp-samples/flip-coin-kfp.yaml
Labels: approved, lgtm, size/L

#4 Add the Tekton version of the flip-coin sample
  kfp-samples/README.md
  kfp-samples/condition/README.md
  kfp-samples/condition/flip-coin-argo.yaml
  kfp-samples/condition/flip-coin-tekton-resorces.yaml
  kfp-samples/condition/flip-coin-tekton.yaml
Labels: approved, lgtm, size/L

#5 Add KFP-TFX on-prem example
  samples/kfp-tekton/README.md
  samples/kfp-tekton/flip-coin/README.md
  samples/kfp-tekton/flip-coin/flip-coin-argo.yaml
  samples/kfp-tekton/flip-coin/flip-coin-tekton-resorces.yaml
  samples/kfp-tekton/flip-coin/flip-coin-tekton.yaml
  samples/kfp-tfx/tfx-taxi-on-prem/README.md
  samples/kfp-tfx/tfx-taxi-on-prem/TFX-taxi-sample-pvc.py
  samples/kfp-tfx/tfx-taxi-on-prem/kfs.py
  samples/kfp-tfx/tfx-taxi-on-prem/pvc/filebrowser.yaml
  samples/kfp-tfx/tfx-taxi-on-prem/pvc/pv.yaml
  samples/kfp-tfx/tfx-taxi-on-prem/pvc/tfx-pvc.yaml
  samples/kfp-tfx/tfx-taxi-on-prem/tfx-kfs.yaml
Labels: approved, lgtm, size/XXL

#6 Rearranged pipelines and descriptions
  OWNERS
  samples/kfp-tekton/README.md
  samples/kfp-tekton/flip-coin/README.md
  samples/kfp-tekton/flip-coin/argo/flip-coin-argo.yaml
  samples/kfp-tekton/flip-coin/tekton/flip-coin-tekton-resorces.yaml
  samples/kfp-tekton/flip-coin/tekton/flip-coin-tekton.yaml
Labels: approved, lgtm, size/S

#7 TfX readme
  samples/kfp-tfx/README.md
  samples/kfp-tfx/images/tfx-taxi.png
Labels: approved, lgtm, size/XS
