Repository kubeflow/kfp-tekton, pull requests merged in 2020-07, with the labels that each got.

#207 Prepare release 0.2.0
  sdk/README.md
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/setup.py
Labels: approved, lgtm, size/S

#209 Make verify
  Makefile
  sdk/python/README.md
Labels: approved, lgtm, size/M

#206 Update samples with the new PipelineRun SDK
  .gitignore
  samples/README.md
  samples/e2e-mnist/README.md
  samples/e2e-mnist/mnist.ipynb
  samples/flip-coin/README.md
  samples/katib/README.md
  samples/lightweight-component/README.md
  samples/lightweight-component/lightweight_component.ipynb
  samples/nested-pipeline/README.md
  samples/trusted-ai/README.md
  samples/trusted-ai/trusted-ai.py
  samples/watson-train-serve/README.md
  samples/watson-train-serve/watson_train_serve_pipeline.py
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/load_from_yaml.log
  sdk/python/tests/compiler/testdata/load_from_yaml.py
  sdk/python/tests/compiler/testdata/load_from_yaml.yaml
Labels: approved, lgtm, size/XL

#213 Remove build.sh in favor of make distribution
  sdk/python/build.sh
Labels: approved, lgtm, size/M

#211 Add KFP Tekton user guide
  samples/README.md
  samples/kfp-user-guide/README.md
  samples/kfp-user-guide/echo_pipeline.py
  samples/kfp-user-guide/images/experiment-page.png
  samples/kfp-user-guide/images/pipeline-page.png
  samples/kfp-user-guide/images/run-page.png
  samples/kfp-user-guide/images/upload-button.png
  samples/kfp-user-guide/images/upload-page.png
Labels: approved, lgtm, size/L

#212 Update SDK README.md
  sdk/README.md
Labels: approved, lgtm, size/M

#210 Make unit tests run with Python 3.5
  .travis.yml
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/k8s_helper_tests.py
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
Labels: approved, lgtm, size/M

#220 Fix runAfter specification failing to be parsed
  frontend/src/lib/WorkflowParser.ts
Labels: approved, lgtm, size/XS

#217 Update the samples of big data since the design changed
  samples/big_data_passing/big_data_passing_description.ipynb
  samples/big_data_passing/constant_to_consumer_pipeline.yaml
  samples/big_data_passing/pipeline_parameter_to_consumer_pipeline.yaml
  samples/big_data_passing/print_repeating_lines_pipeline.yaml
  samples/big_data_passing/processing_pipeline.yaml
  samples/big_data_passing/producers_to_consumers_pipeline.yaml
  samples/big_data_passing/sum_pipeline.yaml
  samples/big_data_passing/task_output_to_consumer_pipeline.yaml
  samples/big_data_passing/text_splitting_pipeline.yaml
  samples/big_data_passing/text_splitting_pipeline2.yaml
Labels: approved, lgtm, size/XXL

#215 Verify Markdown files have current Table of Contents
  .travis.yml
  CONTRIBUTING.md
  Makefile
  tools/mdtoc.sh
Labels: approved, lgtm, size/M

#214 Don't kill no pipelines :-)
  samples/kfp-user-guide/README.md
Labels: approved, lgtm, size/M

#216 Upgrade to Tekton version 0.14.0
  README.md
  samples/README.md
  sdk/FEATURES.md
  sdk/README.md
  sdk/python/README.md
  sdk/python/tests/compiler/testdata/exit_handler.log
  tekton_kfp_guide.md
Labels: approved, lgtm, size/L

#221 Add support for finally syntax in UI
  frontend/src/lib/StaticGraphParser.ts
  frontend/src/lib/WorkflowParser.ts
Labels: approved, lgtm, size/M

#218 Add Tekton 0.14 support to the api
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#223 Include sdk/FEATURES.md in Table-of-Contents check
  Makefile
  sdk/FEATURES.md
  tools/mdtoc.sh
Labels: approved, lgtm, size/M

#226 Add init tekton samples as part of the apiserver build
  backend/Dockerfile
  backend/metadata_writer/src/metadata_writer.py
  backend/src/apiserver/config/sample_config.json
  backend/src/common/util/template_util.go
Labels: approved, lgtm, size/M

#228 Update trusted-ai sample to pull the component from new organization
  samples/trusted-ai/trusted-ai.py
Labels: approved, lgtm, size/XS

#233 Update terminate status using the latest tekton api spec
  backend/src/apiserver/resource/resource_manager.go
  backend/src/common/util/workflow.go
Labels: approved, lgtm, size/S

#236 Simplify deployment and usage instructions
  README.md
  tekton_kfp_guide.md
Labels: approved, lgtm, size/M

#237 remove numbering
  README.md
Labels: size/M

#239 Provide one of solution to achive pipeline logs to S3
  samples/Logging_S3/pipeline_log_to_S3_by_banzaicloud/minio_s3.png
  samples/Logging_S3/pipeline_log_to_S3_by_banzaicloud/pipeline_logging_output_s3_banzaicloud.md
Labels: approved, lgtm, size/L

#235 Make E2E tests more robust
  .gitignore
  Makefile
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/compiler_tests_e2e.py
  sdk/python/tests/compiler/testdata/basic_no_decorator.log
  sdk/python/tests/compiler/testdata/compose.log
  sdk/python/tests/compiler/testdata/condition.log
  sdk/python/tests/compiler/testdata/exit_handler.log
  sdk/python/tests/compiler/testdata/hidden_output_file.log
  sdk/python/tests/compiler/testdata/imagepullsecrets.log
  sdk/python/tests/compiler/testdata/load_from_yaml.log
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.log
  sdk/python/tests/compiler/testdata/parallel_join_with_artifacts.log
  sdk/python/tests/compiler/testdata/pipelineparams.log
  sdk/python/tests/compiler/testdata/sidecar.log
  sdk/python/tests/compiler/testdata/volume_op.log
  sdk/python/tests/compiler/testdata/withitem_nested.log
Labels: approved, lgtm, size/L

#240 Add conversion from status to phase for new statuses
  frontend/src/lib/StatusUtils.ts
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/Status.tsx
Labels: approved, lgtm, size/M

#247 UI refactoring for kfp 1.0.0 rebase
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/Status.tsx
Labels: approved, lgtm, size/M

#245 Api and manifest rebase patch
  backend/Dockerfile
  backend/metadata_writer/src/metadata_writer.py
  backend/src/common/util/workflow.go
  go.sum
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
Labels: approved, lgtm, size/M

#250 Fix run output crash when artifacts are present
  frontend/src/lib/CompareUtils.ts
Labels: approved, lgtm, size/XS
