Repository kubeflow/kfp-tekton, pull requests merged in 2020-08, with the labels that each got.

#246 Upgrade E2E tests for tkn CLI version 0.11
  Makefile
  sdk/README.md
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/compiler_tests_e2e.py
  sdk/python/tests/compiler/testdata/affinity.py
  sdk/python/tests/compiler/testdata/affinity.yaml
  sdk/python/tests/compiler/testdata/basic_no_decorator.log
  sdk/python/tests/compiler/testdata/basic_no_decorator.py
  sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
  sdk/python/tests/compiler/testdata/compose.log
  sdk/python/tests/compiler/testdata/exit_handler.log
  sdk/python/tests/compiler/testdata/node_selector.py
  sdk/python/tests/compiler/testdata/node_selector.yaml
  sdk/python/tests/compiler/testdata/pipelineparams.log
  sdk/python/tests/compiler/testdata/retry.py
  sdk/python/tests/compiler/testdata/sidecar.log
Labels: approved, lgtm, size/L

#248 An easy solution of archiving pipeline logs to S3
  samples/logging_s3/pipeline_log_to_s3_by_banzaicloud/minio_s3.png
  samples/logging_s3/pipeline_log_to_s3_by_banzaicloud/pipeline_logging_output_s3_banzaicloud.md
  samples/logging_s3/pipeline_log_to_s3_by_sdk/parallel_join.py
  samples/logging_s3/pipeline_log_to_s3_by_sdk/pipeline_logging_output_s3_compiler.md
  samples/logging_s3/pipeline_log_to_s3_by_sdk/s3-1.png
  samples/logging_s3/pipeline_log_to_s3_by_sdk/s3-2.png
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/compiler/main.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/compiler_tests_e2e.py
  sdk/python/tests/compiler/testdata/parallel_join_with_logging.yaml
Labels: approved, area/logging, lgtm, size/XL

#263 Update comment for kfp-tekton image
  sdk/python/kfp_tekton/compiler/_op_to_template.py
Labels: approved, lgtm, size/XS

#260 Upgrade SDK to Tekton Pipelines v0.15.0
  Makefile
  README.md
  sdk/README.md
  sdk/python/README.md
  sdk/python/tests/compiler/compiler_tests_e2e.py
Labels: approved, lgtm, size/M

#262 Update Tekton api client to 0.15
  go.mod
  go.sum
  tekton_kfp_guide.md
Labels: approved, lgtm, size/XL

#261 feat(backend): Update scheduledworkflow image to run with pipelinerun
  backend/Dockerfile.scheduledworkflow
  backend/src/crd/controller/scheduledworkflow/client/workflow_client.go
  backend/src/crd/controller/scheduledworkflow/controller.go
  backend/src/crd/controller/scheduledworkflow/main.go
  backend/src/crd/controller/scheduledworkflow/util/label.go
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow.go
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-role.yaml
  tekton_kfp_guide.md
Labels: approved, lgtm, size/L

#259 fix(sdk): Update SDK to pull artifact related information from annotations
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/affinity.yaml
  sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/compose.yaml
  sdk/python/tests/compiler/testdata/condition.yaml
  sdk/python/tests/compiler/testdata/exit_handler.yaml
  sdk/python/tests/compiler/testdata/hidden_output_file.yaml
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
  sdk/python/tests/compiler/testdata/init_container.yaml
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
  sdk/python/tests/compiler/testdata/katib.yaml
  sdk/python/tests/compiler/testdata/load_from_yaml.yaml
  sdk/python/tests/compiler/testdata/loop_static.yaml
  sdk/python/tests/compiler/testdata/node_selector.yaml
  sdk/python/tests/compiler/testdata/parallel_join.yaml
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.yaml
  sdk/python/tests/compiler/testdata/parallel_join_with_artifacts.yaml
  sdk/python/tests/compiler/testdata/parallel_join_with_logging.yaml
  sdk/python/tests/compiler/testdata/pipeline_transformers.yaml
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/retry.yaml
  sdk/python/tests/compiler/testdata/sequential.yaml
  sdk/python/tests/compiler/testdata/sidecar.yaml
  sdk/python/tests/compiler/testdata/timeout.yaml
  sdk/python/tests/compiler/testdata/tolerations.yaml
  sdk/python/tests/compiler/testdata/volume.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
  sdk/python/tests/compiler/testdata/volume_snapshot_op.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
Labels: approved, lgtm, size/XL

#266 fix(ui): Update UI to display artifact information
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/RunDetails.tsx
Labels: approved, lgtm, size/L

#272 feat(samples): parameterize storageclass for the e2e-mnist example
  samples/e2e-mnist/README.md
  samples/e2e-mnist/mnist.ipynb
Labels: approved, lgtm, size/M

#275 Add kfp-tekton deployment instructions and update user guide for multi-user
  developer_guide.md
  samples/kfp-user-guide/README.md
  samples/kfp-user-guide/images/run-page.png
  tekton_kfp_guide.md
Labels: approved, lgtm, size/XL

#265 support logging pipeline logs to S3 via fluentd
  samples/logging_s3/pipeline_log_to_s3_by_fluentd_recommend/Dockerfile
  samples/logging_s3/pipeline_log_to_s3_by_fluentd_recommend/Makefile
  samples/logging_s3/pipeline_log_to_s3_by_fluentd_recommend/README.md
  samples/logging_s3/pipeline_log_to_s3_by_fluentd_recommend/entrypoint.sh
  samples/logging_s3/pipeline_log_to_s3_by_fluentd_recommend/fluent-config.yaml
  samples/logging_s3/pipeline_log_to_s3_by_fluentd_recommend/fluent.conf
  samples/logging_s3/pipeline_log_to_s3_by_fluentd_recommend/images/s3-1.png
  samples/logging_s3/pipeline_log_to_s3_by_fluentd_recommend/images/s3-2.png
  samples/logging_s3/pipeline_log_to_s3_by_fluentd_recommend/pipeline-logs-fluentd-s3.yaml
Labels: approved, lgtm, size/L

#279 casestudy: make a random pipeline outside of kfp main repo work with Tekton
  samples/titanic-ml-dataset/data/test.csv
  samples/titanic-ml-dataset/data/train.csv
  samples/titanic-ml-dataset/requirements.txt
  samples/titanic-ml-dataset/titanic-ml.py
Labels: approved, lgtm, size/XXL

#278 Feature: Configurable artifact credentials and annotations
  backend/metadata_writer/src/metadata_writer.py
  backend/src/apiserver/common/config.go
  backend/src/apiserver/common/const.go
  backend/src/apiserver/resource/resource_manager.go
  manifests/kustomize/env/platform-agnostic/apiserver-deployment.yaml
  manifests/kustomize/env/platform-agnostic/kfp-pipeline-install-config.yaml
  manifests/kustomize/env/platform-agnostic/kustomization.yaml
Labels: approved, lgtm, size/L

#282 fix(sdk): Fix volumes bug on wrong dict key
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/volume_logging.yaml
Labels: approved, lgtm, size/L

#283 fix(sdk): throw errors on deprecated volume definition
  .travis.yml
  sdk/README.md
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/old_kfp_volume.py
Labels: approved, lgtm, size/XXL

#285 update kfp tekton install steps
  tekton_kfp_guide.md
Labels: approved, lgtm, size/L

#289 Move pytest dependency into Makefile
  .travis.yml
  Makefile
Labels: approved, lgtm, size/XS

#291 Remove dependency on KUBECONFIG environment variable
  Makefile
  sdk/python/tests/compiler/compiler_tests_e2e.py
Labels: approved, lgtm, size/S

#294 Updating reviewers
  OWNERS
Labels: approved, lgtm, size/XS
