Repository kubeflow/kfp-tekton, pull requests merged in 2020-12, with the labels that each got.

#369 Fix the yaml cannot show in Safari browser issue
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/__snapshots__/PipelineDetails.test.tsx.snap
Labels: approved, lgtm, size/S

#373 fix(frontend): enhance the when condition UI display
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/RunDetails.tsx
Labels: approved, lgtm, size/M

#377 fix(frontend): Fix UI display issue if custom task definend for Tekton Task
  frontend/src/lib/StaticGraphParser.ts
Labels: approved, lgtm, size/XS

#380 Fix broken clone link
  guides/developer_guide.md
Labels: approved, lgtm, size/XS

#378 fix(frontend): Fixes "Report an issue" link and cleanup UI warnings
  frontend/src/components/Banner.tsx
  frontend/src/components/SideNav.tsx
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/RunDetails.tsx
Labels: approved, lgtm, size/S

#379 Fix race condition on stand alone deployment
  guides/kfp_tekton_install.md
  install/v0.4.0/kfp-tekton.yaml
  manifests/kustomize/env/kfp-template/application-crd.yaml
  manifests/kustomize/env/kfp-template/kustomization.yaml
  manifests/kustomize/env/kfp-template/scheduled-workflow-crd.yaml
  manifests/kustomize/env/kfp-template/viewer-crd.yaml
Labels: approved, lgtm, size/M

#384 test: Add build test for apiserver, agent, and workflow
  .travis.yml
  Makefile
Labels: approved, lgtm, size/S

#383 fix(ui and sdk): Support display name annotations
  frontend/src/lib/ParserUtils.ts
  frontend/src/lib/StaticGraphParser.ts
  frontend/src/lib/WorkflowParser.ts
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/set_display_name.py
  sdk/python/tests/compiler/testdata/set_display_name.yaml
Labels: approved, lgtm, size/L

#391 Update broken link to pass travis test
  sdk/python/README.md
Labels: approved, lgtm, size/XS

#390 fix(sdk): dump "y" and "n" in enforced string mode
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/compiler/yaml_utils.py
Labels: approved, lgtm, size/M

#392 Use fixed version of minio image
  install/v0.4.0/kfp-tekton.yaml
  manifests/kustomize/env/platform-agnostic/kfp-pipeline-config.yaml
Labels: approved, lgtm, size/XS

#387 Update the backend test instructions with go test
  backend/README.md
Labels: approved, lgtm, size/M

#393 Prepare SDK 0.5.0 release on PyPI
  Makefile
  VERSION
  sdk/python/kfp_tekton/__init__.py
  sdk/python/requirements.in
  sdk/python/setup.py
Labels: approved, lgtm, size/S

#385 test: Add docker image build tests for backend
  .travis.yml
  Makefile
  scripts/check_diff.sh
Labels: approved, lgtm, size/L

#396 Limit scope of Markdown link verification to 404 errors
  tools/python/verify_doc_links.py
Labels: approved, lgtm, size/XS
