Repository kubeflow/kfp-tekton, pull requests merged in 2020-05, with the labels that each got.

#116 Kubeflow e2e example
  .gitignore
  samples/e2e-mnist/9.bmp
  samples/e2e-mnist/README.md
  samples/e2e-mnist/mnist.ipynb
Labels: approved, area/example, lgtm, size/XL

#130 Add compilation report for all KFP DSL scripts
  sdk/python/tests/README.md
  sdk/python/tests/test_kfp_samples.sh
Labels: approved, lgtm, size/L

#134 Add trusted ai example
  samples/katib/README.md
  samples/trusted-ai/README.md
  samples/trusted-ai/trusted-ai.py
  sdk/README.md
Labels: approved, lgtm, size/L

#131 Create lightweight sample
  samples/lightweight-component/README.md
  samples/lightweight-component/images/Tekton_add-2.png
  samples/lightweight-component/images/Tekton_add.png
  samples/lightweight-component/images/Tekton_divmod.png
  samples/lightweight-component/images/Tekton_resource.png
  samples/lightweight-component/images/Tekton_taskruns.png
  samples/lightweight-component/lightweight_component.ipynb
Labels: approved, lgtm, size/L

#136 Porting kubectl-wrapper
  tekton-catalog/kubectl-wrapper/Dockerfile
  tekton-catalog/kubectl-wrapper/Makefile
  tekton-catalog/kubectl-wrapper/README.md
  tekton-catalog/kubectl-wrapper/cmd/client/main.go
  tekton-catalog/kubectl-wrapper/deploy/kubectl-deploy.yaml
  tekton-catalog/kubectl-wrapper/deploy/rbac.yaml
  tekton-catalog/kubectl-wrapper/deploy/taskrun-delete.yaml
  tekton-catalog/kubectl-wrapper/deploy/taskrun.yaml
  tekton-catalog/kubectl-wrapper/go.mod
  tekton-catalog/kubectl-wrapper/go.sum
Labels: approved, lgtm, size/XXL

#132 Add Andrew and Kevin as reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#135 Upgrade kfp version from 0.2.2 to 0.5.0
  README.md
  sdk/README.md
  sdk/python/README.md
  sdk/python/kfp_tekton/compiler/_k8s_helper.py
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/requirements.txt
  sdk/python/setup.py
  sdk/python/tests/README.md
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
  sdk/python/tests/compiler/testdata/compose.yaml
  sdk/python/tests/compiler/testdata/condition.yaml
  sdk/python/tests/test_kfp_samples.sh
  sdk/python/tests/test_kfp_samples_report.txt
  tools/mdtoc.sh
Labels: approved, lgtm, size/L

#140 point to the test results from features
  sdk/FEATURES.md
Labels: approved, lgtm, size/XS

#138 Add wml sample
  samples/watson-train-serve/README.md
  samples/watson-train-serve/watson_train_serve_pipeline.py
Labels: approved, lgtm, size/L

#141 tested pipeline samples
  README.md
  samples/README.md
  samples/e2e-mnist/README.md
  samples/trusted-ai/README.md
Labels: approved, lgtm, size/M

#142 Minor fixes for markdown, headers, and warnings.
  samples/README.md
  samples/trusted-ai/README.md
  samples/watson-train-serve/README.md
  sdk/FEATURES.md
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/parallel_join.py
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.py
  sdk/python/tests/compiler/testdata/sequential.py
  sdk/python/tests/test_util.py
Labels: approved, lgtm, size/S

#145 Add nested pipeline example:
  samples/README.md
  samples/nested-pipeline/README.md
  samples/nested-pipeline/compose.py
Labels: approved, lgtm, size/L

#148 Remove compiler monkey-patch
  sdk/python/README.md
  sdk/python/kfp_tekton/compiler/__init__.py
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/kfp_tekton/compiler/_k8s_helper.py
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/affinity.py
  sdk/python/tests/compiler/testdata/artifact_location.py
  sdk/python/tests/compiler/testdata/basic_no_decorator.py
  sdk/python/tests/compiler/testdata/compose.py
  sdk/python/tests/compiler/testdata/condition.py
  sdk/python/tests/compiler/testdata/hidden_output_file.py
  sdk/python/tests/compiler/testdata/imagepullsecrets.py
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
  sdk/python/tests/compiler/testdata/init_container.py
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.py
  sdk/python/tests/compiler/testdata/katib.py
  sdk/python/tests/compiler/testdata/loop_static.py
  sdk/python/tests/compiler/testdata/node_selector.py
  sdk/python/tests/compiler/testdata/parallel_join.py
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.py
  sdk/python/tests/compiler/testdata/pipeline_transformers.py
  sdk/python/tests/compiler/testdata/pipelineparams.py
  sdk/python/tests/compiler/testdata/resourceop_basic.py
  sdk/python/tests/compiler/testdata/retry.py
  sdk/python/tests/compiler/testdata/sequential.py
  sdk/python/tests/compiler/testdata/sidecar.py
  sdk/python/tests/compiler/testdata/timeout.py
  sdk/python/tests/compiler/testdata/tolerations.py
  sdk/python/tests/compiler/testdata/volume.py
  sdk/python/tests/compiler/testdata/volume_op.py
  sdk/python/tests/compiler/testdata/volume_snapshot_op.py
  sdk/python/tests/compiler/testdata/withitem_nested.py
  tools/mdtoc.sh
Labels: approved, lgtm, size/XL

#155 Make the intent of the repository clear
  README.md
Labels: approved, lgtm, size/S

#156 Rename main step name to "main"
  sdk/FEATURES.md
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/tests/compiler/testdata/affinity.yaml
  sdk/python/tests/compiler/testdata/artifact_location.yaml
  sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
  sdk/python/tests/compiler/testdata/compose.yaml
  sdk/python/tests/compiler/testdata/condition.yaml
  sdk/python/tests/compiler/testdata/hidden_output_file.yaml
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
  sdk/python/tests/compiler/testdata/init_container.yaml
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
  sdk/python/tests/compiler/testdata/katib.yaml
  sdk/python/tests/compiler/testdata/loop_static.yaml
  sdk/python/tests/compiler/testdata/node_selector.yaml
  sdk/python/tests/compiler/testdata/parallel_join.yaml
  sdk/python/tests/compiler/testdata/parallel_join_pipelinerun.yaml
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.yaml
  sdk/python/tests/compiler/testdata/pipeline_transformers.yaml
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/retry.yaml
  sdk/python/tests/compiler/testdata/sequential.yaml
  sdk/python/tests/compiler/testdata/sidecar.yaml
  sdk/python/tests/compiler/testdata/timeout.yaml
  sdk/python/tests/compiler/testdata/timeout_pipelinerun.yaml
  sdk/python/tests/compiler/testdata/tolerations.yaml
  sdk/python/tests/compiler/testdata/volume.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
  sdk/python/tests/compiler/testdata/volume_snapshot_op.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
Labels: approved, lgtm, size/L

#157 Add troubleshooting pointer for venv errors
  sdk/README.md
Labels: approved, lgtm, size/XS

#153 Update to use taskRunSpec for podTemplate spec.
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/affinity.yaml
  sdk/python/tests/compiler/testdata/node_selector.yaml
  sdk/python/tests/compiler/testdata/tolerations.yaml
Labels: approved, lgtm, size/M

#160 Fix tiny issue for kubectl-wrapper
  tekton-catalog/kubectl-wrapper/deploy/taskrun.yaml
Labels: approved, lgtm, size/XS

#159 Verify source files contain license header
  .travis.yml
  Makefile
  sdk/python/tests/config.yaml
Labels: approved, lgtm, size/M

#162 Update feature doc related to the recently changes
  sdk/FEATURES.md
  sdk/README.md
Labels: approved, lgtm, size/M

#158 Sanitize Kubernetes Names
  sdk/python/kfp_tekton/compiler/_k8s_helper.py
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/k8s_helper_tests.py
  sdk/python/tests/compiler/testdata/loop_static.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
  sdk/python/tests/run_tests.sh
Labels: approved, lgtm, size/L

#164 make lint
  .travis.yml
  Makefile
  sdk/python/README.md
  sdk/python/kfp_tekton/compiler/__init__.py
  sdk/python/kfp_tekton/compiler/_k8s_helper.py
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/compiler/main.py
  sdk/python/setup.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/k8s_helper_tests.py
  sdk/python/tests/compiler/testdata/affinity.py
  sdk/python/tests/compiler/testdata/artifact_location.py
  sdk/python/tests/compiler/testdata/basic_no_decorator.py
  sdk/python/tests/compiler/testdata/condition.py
  sdk/python/tests/compiler/testdata/imagepullsecrets.py
  sdk/python/tests/compiler/testdata/init_container.py
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.py
  sdk/python/tests/compiler/testdata/katib.py
  sdk/python/tests/compiler/testdata/node_selector.py
  sdk/python/tests/compiler/testdata/pipeline_transformers.py
  sdk/python/tests/compiler/testdata/resourceop_basic.py
  sdk/python/tests/compiler/testdata/retry.py
  sdk/python/tests/compiler/testdata/sidecar.py
  sdk/python/tests/compiler/testdata/timeout.py
  sdk/python/tests/compiler/testdata/tolerations.py
  sdk/python/tests/compiler/testdata/volume_op.py
  sdk/python/tests/compiler/testdata/withitem_nested.py
  sdk/python/tests/test_util.py
Labels: approved, lgtm, size/L
