Repository kubeflow/kfp-tekton, pull requests merged in 2020-06, with the labels that each got.

#167 Update conditional feature with the catalog condition approach
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/condition.yaml
  tekton-catalog/condition/README.md
  tekton-catalog/condition/condition.yaml
Labels: approved, lgtm, size/L

#169 Fix for big data passing
  samples/bigger_data_passing/big_data_passing_description.ipynb
  samples/bigger_data_passing/constant_to_consumer_pipeline.yaml
  samples/bigger_data_passing/pipeline_parameter_to_consumer_pipeline.yaml
  samples/bigger_data_passing/print_repeating_lines_pipeline.yaml
  samples/bigger_data_passing/processing_pipeline.yaml
  samples/bigger_data_passing/producers_to_consumers_pipeline.yaml
  samples/bigger_data_passing/sum_pipeline.yaml
  samples/bigger_data_passing/task_output_to_consumer_pipeline.yaml
  samples/bigger_data_passing/text_splitting_pipeline.yaml
  samples/bigger_data_passing/text_splitting_pipeline2.yaml
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/affinity.yaml
  sdk/python/tests/compiler/testdata/artifact_location.yaml
  sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
  sdk/python/tests/compiler/testdata/big_data_passing.py
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/condition.yaml
  sdk/python/tests/compiler/testdata/hidden_output_file.yaml
  sdk/python/tests/compiler/testdata/init_container.yaml
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
  sdk/python/tests/compiler/testdata/loop_static.yaml
  sdk/python/tests/compiler/testdata/node_selector.yaml
  sdk/python/tests/compiler/testdata/pipeline_transformers.yaml
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/retry.yaml
  sdk/python/tests/compiler/testdata/sidecar.yaml
  sdk/python/tests/compiler/testdata/timeout.yaml
  sdk/python/tests/compiler/testdata/timeout_pipelinerun.yaml
  sdk/python/tests/compiler/testdata/tolerations.yaml
  sdk/python/tests/compiler/testdata/volume.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
Labels: approved, lgtm, size/XXL

#171 Apply to be kfp-tekton approver
  OWNERS
Labels: approved, lgtm, size/XS

#172 Update imagepullsecret and update to v0.13.0
  README.md
  sdk/FEATURES.md
  sdk/README.md
  sdk/python/README.md
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/affinity.yaml
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
  sdk/python/tests/compiler/testdata/node_selector.yaml
  sdk/python/tests/compiler/testdata/tolerations.yaml
Labels: approved, lgtm, size/M

#177 Consolidate the value of results to avoid underscore convering in params
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/artifact_location.yaml
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/katib.yaml
  sdk/python/tests/compiler/testdata/loop_static.yaml
  sdk/python/tests/compiler/testdata/pipelineparams.py
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
Labels: approved, lgtm, size/L

#179 Support Exit Handler
  sdk/FEATURES.md
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
  sdk/python/tests/compiler/testdata/exit_handler.py
  sdk/python/tests/compiler/testdata/exit_handler.yaml
Labels: approved, lgtm, size/L

#178 Remove randomness from condition example
  sdk/python/tests/compiler/testdata/condition.py
  sdk/python/tests/compiler/testdata/condition.yaml
Labels: approved, lgtm, size/M

#175 Deprecate artifact location and update to kfp 0.5.1
  README.md
  sdk/README.md
  sdk/python/README.md
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/compiler/main.py
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
  sdk/python/tests/README.md
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/affinity.yaml
  sdk/python/tests/compiler/testdata/artifact_location.py
  sdk/python/tests/compiler/testdata/artifact_location.yaml
  sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/compose.yaml
  sdk/python/tests/compiler/testdata/condition.yaml
  sdk/python/tests/compiler/testdata/hidden_output_file.yaml
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
  sdk/python/tests/compiler/testdata/init_container.yaml
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
  sdk/python/tests/compiler/testdata/katib.yaml
  sdk/python/tests/compiler/testdata/loop_static.yaml
  sdk/python/tests/compiler/testdata/node_selector.yaml
  sdk/python/tests/compiler/testdata/parallel_join.yaml
  sdk/python/tests/compiler/testdata/parallel_join_pipelinerun.yaml
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.yaml
  sdk/python/tests/compiler/testdata/parallel_join_with_artifacts.yaml
  sdk/python/tests/compiler/testdata/pipeline_transformers.yaml
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/retry.yaml
  sdk/python/tests/compiler/testdata/sequential.yaml
  sdk/python/tests/compiler/testdata/sidecar.yaml
  sdk/python/tests/compiler/testdata/timeout.yaml
  sdk/python/tests/compiler/testdata/timeout_pipelinerun.yaml
  sdk/python/tests/compiler/testdata/tolerations.yaml
  sdk/python/tests/compiler/testdata/volume.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
  sdk/python/tests/compiler/testdata/volume_snapshot_op.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
  sdk/python/tests/test_kfp_samples.sh
  sdk/python/tests/test_kfp_samples_report.txt
Labels: approved, lgtm, size/L

#182 Prepare release 0.1.0
  sdk/python/kfp_tekton/__init__.py
  sdk/python/setup.py
Labels: approved, lgtm, size/S

#184 Update artifact docs and fix minor bug
  sdk/README.md
  sdk/python/kfp_tekton/compiler/main.py
Labels: approved, lgtm, size/M

#186 Fix result path identifier and annotation bug
  sdk/README.md
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/affinity.yaml
  sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/compose.yaml
  sdk/python/tests/compiler/testdata/condition.yaml
  sdk/python/tests/compiler/testdata/exit_handler.yaml
  sdk/python/tests/compiler/testdata/hidden_output_file.yaml
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
  sdk/python/tests/compiler/testdata/init_container.yaml
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
  sdk/python/tests/compiler/testdata/katib.yaml
  sdk/python/tests/compiler/testdata/loop_static.yaml
  sdk/python/tests/compiler/testdata/node_selector.yaml
  sdk/python/tests/compiler/testdata/parallel_join.yaml
  sdk/python/tests/compiler/testdata/parallel_join_pipelinerun.yaml
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.yaml
  sdk/python/tests/compiler/testdata/parallel_join_with_artifacts.log
  sdk/python/tests/compiler/testdata/parallel_join_with_artifacts.yaml
  sdk/python/tests/compiler/testdata/pipeline_transformers.yaml
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/retry.yaml
  sdk/python/tests/compiler/testdata/sequential.yaml
  sdk/python/tests/compiler/testdata/sidecar.yaml
  sdk/python/tests/compiler/testdata/timeout.yaml
  sdk/python/tests/compiler/testdata/timeout_pipelinerun.yaml
  sdk/python/tests/compiler/testdata/tolerations.yaml
  sdk/python/tests/compiler/testdata/volume.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
  sdk/python/tests/compiler/testdata/volume_snapshot_op.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
Labels: approved, lgtm, size/L

#187 Update E2E tests
  sdk/python/tests/compiler/compiler_tests_e2e.py
  sdk/python/tests/compiler/testdata/basic_no_decorator.log
  sdk/python/tests/compiler/testdata/compose.log
  sdk/python/tests/compiler/testdata/condition.log
  sdk/python/tests/compiler/testdata/hidden_output_file.log
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.log
  sdk/python/tests/compiler/testdata/loop_static.log
  sdk/python/tests/compiler/testdata/parallel_join.log
  sdk/python/tests/compiler/testdata/parallel_join_pipelinerun.log
  sdk/python/tests/compiler/testdata/parallel_join_with_artifacts.log
  sdk/python/tests/compiler/testdata/pipeline_transformers.log
  sdk/python/tests/compiler/testdata/pipelineparams.log
  sdk/python/tests/compiler/testdata/retry.log
  sdk/python/tests/compiler/testdata/sequential.log
  sdk/python/tests/compiler/testdata/sidecar.log
  sdk/python/tests/compiler/testdata/timeout_pipelinerun.log
  sdk/python/tests/compiler/testdata/withitem_nested.log
Labels: approved, lgtm, size/L

#190 Generate long_description for PyPi from sdk/README.md
  Makefile
  sdk/README.md
  sdk/python/setup.py
Labels: approved, lgtm, size/L

#195 Tekton api patch
  README.md
  TEKTON_CHANGELOG.md
  backend/Dockerfile
  backend/Dockerfile.persistenceagent
  backend/metadata_writer/src/metadata_writer.py
  backend/src/agent/persistence/client/pipeline_client.go
  backend/src/agent/persistence/client/workflow_client.go
  backend/src/agent/persistence/main.go
  backend/src/agent/persistence/persistence_agent.go
  backend/src/agent/persistence/worker/metrics_reporter.go
  backend/src/apiserver/client/BUILD.bazel
  backend/src/apiserver/client/kubernetes_core_fake.go
  backend/src/apiserver/client/tekton.go
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/model/BUILD.bazel
  backend/src/apiserver/model/resource_reference_test.go
  backend/src/apiserver/resource/BUILD.bazel
  backend/src/apiserver/resource/model_converter.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_util.go
  backend/src/apiserver/server/BUILD.bazel
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/report_server.go
  backend/src/apiserver/server/test_util.go
  backend/src/apiserver/storage/BUILD.bazel
  backend/src/apiserver/storage/job_store_test.go
  backend/src/apiserver/storage/run_store.go
  backend/src/common/client/api_server/BUILD.bazel
  backend/src/common/client/api_server/pipeline_client.go
  backend/src/common/client/api_server/run_client.go
  backend/src/common/client/api_server/util.go
  backend/src/common/util/BUILD.bazel
  backend/src/common/util/formatter.go
  backend/src/common/util/scheduled_workflow.go
  backend/src/common/util/scheduled_workflow_test.go
  backend/src/common/util/template_util.go
  backend/src/common/util/template_util_test.go
  backend/src/common/util/workflow.go
  backend/src/crd/controller/scheduledworkflow/util/BUILD.bazel
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow.go
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow_test.go
  backend/src/crd/pkg/apis/scheduledworkflow/v1beta1/BUILD.bazel
  backend/src/crd/pkg/apis/scheduledworkflow/v1beta1/types.go
  backend/src/crd/pkg/client/clientset/versioned/typed/scheduledworkflow/v1beta1/BUILD.bazel
  backend/src/crd/pkg/client/clientset/versioned/typed/scheduledworkflow/v1beta1/scheduledworkflow_client.go
  go.mod
  go.sum
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/metadata/metadata-writer-deployment.yaml
  manifests/kustomize/base/metadata/metadata-writer-role.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-role.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-role.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-ui-role.yaml
  manifests/kustomize/base/pipeline/pipeline-runner-role.yaml
  manifests/kustomize/base/tekton/catalog-condition.yaml
  manifests/kustomize/base/tekton/kustomization.yaml
  tekton_dev_guide.md
Labels: approved, lgtm, size/XXL

#196 Tekton UI patch
  frontend/server/k8s-helper.ts
  frontend/src/components/Banner.tsx
  frontend/src/lib/StaticGraphParser.ts
  frontend/src/lib/StatusUtils.ts
  frontend/src/lib/Utils.tsx
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/RunList.tsx
  frontend/src/pages/Status.tsx
Labels: approved, lgtm, size/XL

#166 PipelineRun with embedded pipelineSpec and taskSpec
  samples/e2e-mnist/mnist.ipynb
  samples/lightweight-component/lightweight_component.ipynb
  sdk/FEATURES.md
  sdk/README.md
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/compiler/main.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/compiler_tests_e2e.py
  sdk/python/tests/compiler/testdata/affinity.py
  sdk/python/tests/compiler/testdata/affinity.yaml
  sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/compose.yaml
  sdk/python/tests/compiler/testdata/condition.yaml
  sdk/python/tests/compiler/testdata/exit_handler.yaml
  sdk/python/tests/compiler/testdata/hidden_output_file.py
  sdk/python/tests/compiler/testdata/hidden_output_file.yaml
  sdk/python/tests/compiler/testdata/imagepullsecrets.py
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
  sdk/python/tests/compiler/testdata/init_container.yaml
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
  sdk/python/tests/compiler/testdata/katib.yaml
  sdk/python/tests/compiler/testdata/loop_static.yaml
  sdk/python/tests/compiler/testdata/node_selector.yaml
  sdk/python/tests/compiler/testdata/parallel_join.yaml
  sdk/python/tests/compiler/testdata/parallel_join_pipelinerun.log
  sdk/python/tests/compiler/testdata/parallel_join_pipelinerun.yaml
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.yaml
  sdk/python/tests/compiler/testdata/parallel_join_with_artifacts.log
  sdk/python/tests/compiler/testdata/parallel_join_with_artifacts.yaml
  sdk/python/tests/compiler/testdata/pipeline_transformers.yaml
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic.py
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/retry.yaml
  sdk/python/tests/compiler/testdata/sequential.yaml
  sdk/python/tests/compiler/testdata/sidecar.yaml
  sdk/python/tests/compiler/testdata/timeout.yaml
  sdk/python/tests/compiler/testdata/timeout_pipelinerun.log
  sdk/python/tests/compiler/testdata/timeout_pipelinerun.yaml
  sdk/python/tests/compiler/testdata/tolerations.py
  sdk/python/tests/compiler/testdata/tolerations.yaml
  sdk/python/tests/compiler/testdata/volume.yaml
  sdk/python/tests/compiler/testdata/volume_op.log
  sdk/python/tests/compiler/testdata/volume_op.py
  sdk/python/tests/compiler/testdata/volume_op.yaml
  sdk/python/tests/compiler/testdata/volume_snapshot_op.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
Labels: approved, lgtm, size/XXL

#194 Further big_data_passing fixes after PR #166
  sdk/README.md
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/tests/compiler/testdata/big_data_passing.py
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
  sdk/python/tests/compiler/testdata/katib.yaml
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
Labels: approved, lgtm, size/XL

#201 Add TektonClient to SDK
  sdk/python/kfp_tekton/__init__.py
  sdk/python/kfp_tekton/_client.py
  sdk/python/kfp_tekton/compiler/__init__.py
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
Labels: approved, lgtm, size/M

#205 update architecture to reflect backend code integrated
  README.md
  images/kfp-tekton.png
Labels: approved, lgtm, size/S

#204 Enable artifacts as default
  README.md
  sdk/FEATURES.md
  sdk/README.md
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/compiler/main.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/basic_no_decorator.log
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/compose.log
  sdk/python/tests/compiler/testdata/compose.yaml
  sdk/python/tests/compiler/testdata/condition.log
  sdk/python/tests/compiler/testdata/condition.yaml
  sdk/python/tests/compiler/testdata/exit_handler.log
  sdk/python/tests/compiler/testdata/exit_handler.yaml
  sdk/python/tests/compiler/testdata/hidden_output_file.log
  sdk/python/tests/compiler/testdata/hidden_output_file.yaml
  sdk/python/tests/compiler/testdata/imagepullsecrets.log
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.log
  sdk/python/tests/compiler/testdata/katib.yaml
  sdk/python/tests/compiler/testdata/loop_static.log
  sdk/python/tests/compiler/testdata/loop_static.yaml
  sdk/python/tests/compiler/testdata/parallel_join.log
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.log
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.yaml
  sdk/python/tests/compiler/testdata/parallel_join_with_artifacts.log
  sdk/python/tests/compiler/testdata/pipelineparams.log
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic.log
  sdk/python/tests/compiler/testdata/retry.log
  sdk/python/tests/compiler/testdata/sidecar.log
  sdk/python/tests/compiler/testdata/sidecar.yaml
  sdk/python/tests/compiler/testdata/tolerations.yaml
  sdk/python/tests/compiler/testdata/volume.yaml
  sdk/python/tests/compiler/testdata/volume_op.log
  sdk/python/tests/compiler/testdata/volume_op.yaml
  sdk/python/tests/compiler/testdata/volume_snapshot_op.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.log
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
  tekton_kfp_guide.md
Labels: approved, lgtm, size/XXL
