Repository kubeflow/kfp-tekton, pull requests merged in 2020-03, with the labels that each got.

#16 Refactor code to extend KFP SDK compiler
  .gitignore
  sdk/README.md
  sdk/python/build.sh
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp_tekton/__init__.py
  sdk/python/kfp_tekton/compiler/__init__.py
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/kfp_tekton/compiler/_k8s_helper.py
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/compiler/main.py
  sdk/python/requirements.txt
  sdk/python/setup.py
  sdk/python/tests/__init__.py
  sdk/python/tests/compiler/__init__.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/main.py
  sdk/python/tests/compiler/testdata/__init__.py
  sdk/python/tests/compiler/testdata/sequential.py
  sdk/python/tests/compiler/testdata/sequential.yaml
  sdk/python/tests/run_tests.sh
Labels: approved, lgtm, size/XXL

#15 add the design doc
  README.md
Labels: approved, lgtm, size/XS

#17 Generate Tekton Pipeline with Tasks
  sdk/README.md
  sdk/python/kfp_tekton/compiler/__init__.py
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/sequential.py
  sdk/python/tests/compiler/testdata/sequential.yaml
  sdk/samples/sequential/sequential.py
Labels: approved, lgtm, size/L

#21 make goal and deliverable more pointed
  README.md
Labels: approved, lgtm, size/S

#24 update samples and tests to also include parallel use case
  sdk/README.md
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/parallel_join.py
  sdk/python/tests/compiler/testdata/parallel_join.yaml
  sdk/samples/parallel_join.py
  sdk/samples/sequential.py
Labels: approved, lgtm, size/L

#25 Add ckadner as a reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#26 Initial Travis CI for sdk unittest
  .travis.yml
Labels: approved, lgtm, size/S

#27 Task output parameters as input for subsequent tasks
  sdk/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/kfp_tekton/compiler/__init__.py
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/parallel_join.py
  sdk/python/tests/compiler/testdata/parallel_join.yaml
  sdk/python/tests/compiler/testdata/sequential.py
  sdk/python/tests/compiler/testdata/sequential.yaml
  sdk/samples/parallel_join.py
  sdk/samples/sequential.py
Labels: approved, lgtm, size/L

#31 Add reviewer from IBM China
  OWNERS
Labels: approved, lgtm, size/XS

#30 Modify the path of sample to the correct one
  samples/kfp-tekton/flip-coin/README.md
  samples/kfp-tekton/flip-coin/tekton/flip-coin-tekton-resources.yaml
Labels: approved, lgtm, size/XS

#32 Add script to test all KFP samples
  .gitignore
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/tests/test_kfp_samples.sh
  sdk/python/tests/test_kfp_samples_report.txt
Labels: approved, lgtm, ok-to-test, size/L

#36 streamline and add to instructions
  README.md
  sdk/README.md
Labels: approved, lgtm, size/M

#40 Add volumemount support and fix parameter bugs
  sdk/README.md
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/sequential.py
  sdk/python/tests/compiler/testdata/volume.py
  sdk/python/tests/compiler/testdata/volume.yaml
  sdk/samples/parallel_join.py
  sdk/samples/sequential.py
Labels: approved, lgtm, size/L

#43 Use apps/v1 instead of extensions/v1beta1
  .gitignore
  samples/kfp-tfx/tfx-taxi-on-prem/pvc/filebrowser.yaml
Labels: approved, lgtm, size/XS

#42 Add support for sidecars
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/sidecar.py
  sdk/python/tests/compiler/testdata/sidecar.yaml
Labels: approved, lgtm, size/L

#47 add instructions to install tekton pipeline and storage
  samples/kfp-tekton/flip-coin/README.md
Labels: approved, lgtm, size/XS

#50 Add init_container support
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/init_container.py
  sdk/python/tests/compiler/testdata/init_container.yaml
Labels: approved, lgtm, size/M

#45 Add pipelineparams which contains multi params and sidecars support
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/pipelineparams.py
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/test_kfp_samples_report.txt
Labels: approved, lgtm, size/L

#46 Extend compiler to support timeout defining for pipeline tasks
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/timeout.py
  sdk/python/tests/compiler/testdata/timeout.yaml
Labels: approved, lgtm, size/L

#57 instructions to run tests
  sdk/README.md
  sdk/python/tests/README.md
Labels: approved, lgtm, size/M

#58 Point to the pre-reqs on WML pipeline
  sdk/README.md
Labels: approved, lgtm, size/XS

#55 Extend compiler to support retries for tasks
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/retry.py
  sdk/python/tests/compiler/testdata/retry.yaml
Labels: approved, lgtm, size/L

#60 Add compiler progress report to Travis
  .travis.yml
  sdk/python/tests/test_kfp_samples.sh
  sdk/python/tests/test_kfp_samples_report.txt
Labels: approved, lgtm, size/M

#62 Add initial pipelinerun support
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/compiler/main.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/init_container.py
  sdk/python/tests/compiler/testdata/init_container.yaml
  sdk/python/tests/compiler/testdata/parallel_join_pipelinerun.yaml
Labels: approved, lgtm, size/L

#68 Extend compiler to support workflow level timeout
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/timeout.py
  sdk/python/tests/compiler/testdata/timeout_pipelinerun.yaml
Labels: approved, lgtm, size/M

#69 enhance testdata scripts
  sdk/python/tests/compiler/testdata/init_container.py
  sdk/python/tests/compiler/testdata/pipelineparams.py
  sdk/python/tests/compiler/testdata/retry.py
  sdk/python/tests/compiler/testdata/sidecar.py
  sdk/python/tests/compiler/testdata/volume.py
Labels: approved, lgtm, size/S

#73 Update report card and fix typos
  README.md
  sdk/README.md
  sdk/python/tests/README.md
Labels: approved, lgtm, size/S

#65 Add more k8s resource support
  sdk/README.md
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/affinity.py
  sdk/python/tests/compiler/testdata/affinity.yaml
  sdk/python/tests/compiler/testdata/node_selector.py
  sdk/python/tests/compiler/testdata/node_selector.yaml
  sdk/python/tests/compiler/testdata/tolerations.py
  sdk/python/tests/compiler/testdata/tolerations.yaml
Labels: approved, lgtm, size/L
