Repository kubeflow/kfp-tekton, pull requests merged in 2020-04, with the labels that each got.

#76 Add transformer test for pod annotations and labels use case
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/pipeline_transformers.py
  sdk/python/tests/compiler/testdata/pipeline_transformers.yaml
Labels: approved, lgtm, size/L

#77 Add initial github template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/questions.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/issue_label_bot.yaml
Labels: approved, lgtm, size/M

#75 Copy param output files using emptyDir volumes
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/hidden_output_file.py
  sdk/python/tests/compiler/testdata/hidden_output_file.yaml
  sdk/python/tests/test_kfp_samples_report.txt
Labels: approved, lgtm, size/L

#79 Fix no default param bug on pipelinerun
  sdk/python/kfp_tekton/compiler/compiler.py
Labels: approved, lgtm, size/XS

#67 Extend compiler to support parallelFor with loop static params
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/loop_static.py
  sdk/python/tests/compiler/testdata/loop_static.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.py
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
  sdk/python/tests/test_kfp_samples_report.txt
Labels: approved, lgtm, ok-to-test, size/XL

#80 Add argo variable checking when compile to Tekton.
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.py
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.yaml
Labels: approved, lgtm, size/L

#81 Have Travis/CI enforce that the compilation report is updated
  sdk/python/tests/README.md
  sdk/python/tests/test_kfp_samples.sh
  sdk/python/tests/test_kfp_samples_report.txt
Labels: approved, lgtm, size/M

#84 Add support for conditions
  sdk/python/kfp_tekton/compiler/__init__.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/condition.py
  sdk/python/tests/compiler/testdata/condition.yaml
  sdk/python/tests/test_kfp_samples_report.txt
Labels: approved, lgtm, size/L

#83 Fix regular expression parsing to only fail on argo specific variables
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/katib.py
  sdk/python/tests/compiler/testdata/katib.yaml
Labels: approved, lgtm, size/L

#88 Add support for pulling the image secret
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/imagepullsecrets.py
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
Labels: approved, lgtm, size/L

#89 Add support for dsl.ResourceOp
  sdk/README.md
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/resourceop_basic.py
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/test_kfp_samples_report.txt
Labels: approved, lgtm, size/L

#91 Fix special compilation cases for kfp samples
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/config.yaml
  sdk/python/tests/test_kfp_samples.sh
  sdk/python/tests/test_kfp_samples_report.txt
  sdk/python/tests/test_util.py
Labels: approved, lgtm, size/L

#92 Support artifact outputs
  sdk/README.md
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/compiler/main.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/artifact_location.py
  sdk/python/tests/compiler/testdata/artifact_location.yaml
Labels: approved, lgtm, size/XL

#103 Promoting Christian and Tommy to be the approvers
  OWNERS
Labels: approved, lgtm, size/XS

#106 remove the dash - update latest
  sdk/python/tests/README.md
Labels: approved, lgtm, size/M

#95 Add README of ServiceAccount and RBAC
  sdk/README.md
  sdk/sa-and-rbac.md
Labels: approved, lgtm, size/L

#105 Add support for passing task outputs to conditions as parameters
  sdk/README.md
  sdk/python/kfp_tekton/compiler/__init__.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/condition.py
  sdk/python/tests/compiler/testdata/condition.yaml
  sdk/python/tests/test_kfp_samples_report.txt
Labels: approved, lgtm, size/L

#104 Support input artifact
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.py
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.txt
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
  sdk/python/tests/test_kfp_samples_report.txt
Labels: approved, lgtm, size/L

#110 Update compiler report card
  sdk/python/tests/README.md
  sdk/python/tests/test_kfp_samples.sh
Labels: approved, lgtm, size/M

#112 Organize
  README.md
  images/kfp-tekton-phase-one.png
  sdk/README.md
  sdk/sa-and-rbac.md
Labels: approved, lgtm, size/M

#98 create sdk/python makefile
  Makefile
Labels: approved, lgtm, size/M

#108 Code clean up and refactor
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
Labels: approved, lgtm, size/XL

#115 Update docs for building from master
  README.md
  sdk/README.md
Labels: approved, lgtm, size/S

#99 Add limitation doc
  sdk/README.md
  sdk/kfp-tekton-limitation.md
Labels: approved, lgtm, size/M

#119 Fix edge cases such as disable istio-inject for Tekton compiler
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/affinity.yaml
  sdk/python/tests/compiler/testdata/artifact_location.yaml
  sdk/python/tests/compiler/testdata/condition.yaml
  sdk/python/tests/compiler/testdata/hidden_output_file.yaml
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
  sdk/python/tests/compiler/testdata/init_container.yaml
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
  sdk/python/tests/compiler/testdata/katib.yaml
  sdk/python/tests/compiler/testdata/loop_static.yaml
  sdk/python/tests/compiler/testdata/node_selector.yaml
  sdk/python/tests/compiler/testdata/parallel_join.yaml
  sdk/python/tests/compiler/testdata/parallel_join_pipelinerun.yaml
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.yaml
  sdk/python/tests/compiler/testdata/pipeline_transformers.yaml
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/retry.yaml
  sdk/python/tests/compiler/testdata/sequential.yaml
  sdk/python/tests/compiler/testdata/sidecar.yaml
  sdk/python/tests/compiler/testdata/timeout.yaml
  sdk/python/tests/compiler/testdata/timeout_pipelinerun.yaml
  sdk/python/tests/compiler/testdata/tolerations.yaml
  sdk/python/tests/compiler/testdata/volume.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
  sdk/python/tests/compiler/testdata/volume_snapshot_op.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
Labels: approved, lgtm, size/L

#117 Re-arrange slip-coin example
  samples/flip-coin/README.md
  samples/flip-coin/condition.py
  samples/kfp-tekton/README.md
  samples/kfp-tekton/flip-coin/README.md
  samples/kfp-tekton/flip-coin/argo/flip-coin-argo.yaml
  samples/kfp-tekton/flip-coin/tekton/flip-coin-tekton-resources.yaml
  samples/kfp-tekton/flip-coin/tekton/flip-coin-tekton.yaml
Labels: approved, lgtm, size/XL

#111 Add unit tests for 'basic_no_decorator.py' and 'compose.py'
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/basic_no_decorator.py
  sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
  sdk/python/tests/compiler/testdata/compose.py
  sdk/python/tests/compiler/testdata/compose.yaml
  sdk/python/tests/compiler/testdata/condition.py
  sdk/python/tests/compiler/testdata/condition.yaml
  sdk/python/tests/test_kfp_samples.sh
  sdk/python/tests/test_util.py
Labels: approved, lgtm, size/XL

#122 Add docs for compiler feature details
  sdk/FEATURES.md
  sdk/README.md
  sdk/kfp-tekton-limitation.md
Labels: approved, lgtm, size/L

#125 Reinstate Tommy and Christian as reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#124 Add developer guide
  CONTRIBUTING.md
  README.md
  sdk/README.md
  sdk/python/README.md
  tools/mdtoc.sh
Labels: approved, area/docs, lgtm, size/L

#123 Add Simple Katib example
  samples/katib/README.md
  samples/katib/katib.py
Labels: approved, area/example, lgtm, size/L

#126 Use make commands for tests and report
  .travis.yml
  sdk/README.md
  sdk/python/tests/README.md
Labels: approved, area/usage, lgtm, size/M

#127 Feature doc patch
  sdk/FEATURES.md
Labels: approved, area/docs, lgtm, size/L

#128 Add myself as Reviewer
  OWNERS
Labels: approved, lgtm, size/XS
