Repository kubeflow/kfp-tekton, pull requests merged in 2020-10, with the labels that each got.

#320 chore: Update the README to expand and link to CRDs
  README.md
Labels: approved, lgtm, size/XS

#318 Fix big data annotations and update docs/samples
  samples/big_data_passing/big_data_passing_description.ipynb
  samples/big_data_passing/constant_to_consumer_pipeline.yaml
  samples/big_data_passing/pipeline_parameter_to_consumer_pipeline.yaml
  samples/big_data_passing/print_repeating_lines_pipeline.yaml
  samples/big_data_passing/processing_pipeline.yaml
  samples/big_data_passing/producers_to_consumers_pipeline.yaml
  samples/big_data_passing/sum_pipeline.yaml
  samples/big_data_passing/task_output_to_consumer_pipeline.yaml
  samples/big_data_passing/text_splitting_pipeline.yaml
  samples/big_data_passing/text_splitting_pipeline2.yaml
  sdk/README.md
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
Labels: approved, lgtm, size/XL

#322 fix(api): Update list of Tekton final status for api and persistent agent.
  backend/src/common/util/workflow.go
Labels: approved, lgtm, size/XS

#316 fix(samples): Add compilable python file for lightweight and e2e-mnist example
  samples/e2e-mnist/README.md
  samples/e2e-mnist/e2e-mnist.py
  samples/lightweight-component/README.md
  samples/lightweight-component/calc_pipeline.py
  samples/lightweight-component/lightweight_component.ipynb
Labels: approved, lgtm, size/L

#335 fix(backend): MetricsReporter fails on `nil` nodeStatus.Status
  backend/src/agent/persistence/worker/metrics_reporter.go
Labels: approved, lgtm, size/XS

#338 Add best practice for tekton and other argo executors
  samples/kfp-user-guide/README.md
Labels: approved, lgtm, size/S

#323 Add s3 endpoint instructions for admin use case
  kfp-admin-guide.md
Labels: approved, lgtm, size/S

#330 updated titanic-ml generated with kale 0.5.1
  samples/titanic-ml-dataset/titanic-ml.py
Labels: approved, lgtm, size/XL

#329 fix(backend): cover nil status race condition from Tekton
  backend/src/agent/persistence/worker/metrics_reporter.go
Labels: approved, lgtm, size/XS

#344 fix(sdk): Quick fix for sanitizing conditional variables
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/condition.py
  sdk/python/tests/compiler/testdata/condition.yaml
Labels: approved, lgtm, size/M

#346 Fix UI merge conflict that blocks the UI image build.
  frontend/src/pages/RunDetails.tsx
Labels: approved, lgtm, size/XS

#347 Add KFP Tekton release deployment yaml
  Makefile
  install/v0.4.0/kfp-tekton.yaml
  manifests/kustomize/env/kfp-template/kustomization.yaml
  manifests/kustomize/env/kfp-template/namespace.yaml
  release.md
  tekton_kfp_guide.md
Labels: approved, lgtm, size/XXL

#336 feat(backend): ARTIFACT_COPY_STEP_TEMPLATE - custom template for copy step
  backend/src/apiserver/common/config.go
  backend/src/apiserver/resource/resource_manager.go
Labels: approved, lgtm, size/M

#349 make user guide prominent
  README.md
  samples/README.md
  samples/kfp-user-guide/README.md
Labels: approved, size/XS

#350 add a warning label to kustomize page
  manifests/kustomize/README.md
Labels: approved, size/XS
