Repository kubeflow/kfp-tekton, pull requests merged in 2020-11, with the labels that each got.

#345 feat(sdk): added sanitizing k8s object process and test. Fixes: #332
  sdk/python/kfp_tekton/compiler/_k8s_helper.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/k8s_helper_tests.py
Labels: approved, lgtm, size/L

#354 fix(sdk): Address default pipeline timeout behavior
  sdk/FEATURES.md
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/affinity.yaml
  sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/compose.yaml
  sdk/python/tests/compiler/testdata/condition.yaml
  sdk/python/tests/compiler/testdata/exit_handler.yaml
  sdk/python/tests/compiler/testdata/hidden_output_file.yaml
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
  sdk/python/tests/compiler/testdata/init_container.yaml
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
  sdk/python/tests/compiler/testdata/katib.yaml
  sdk/python/tests/compiler/testdata/load_from_yaml.yaml
  sdk/python/tests/compiler/testdata/loop_static.yaml
  sdk/python/tests/compiler/testdata/node_selector.yaml
  sdk/python/tests/compiler/testdata/parallel_join.yaml
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.yaml
  sdk/python/tests/compiler/testdata/pipeline_transformers.yaml
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/retry.yaml
  sdk/python/tests/compiler/testdata/sequential.yaml
  sdk/python/tests/compiler/testdata/sidecar.yaml
  sdk/python/tests/compiler/testdata/timeout.yaml
  sdk/python/tests/compiler/testdata/tolerations.yaml
  sdk/python/tests/compiler/testdata/volume.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
  sdk/python/tests/compiler/testdata/volume_snapshot_op.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
Labels: approved, lgtm, size/L

#351 docs: migration from Argo
  samples/kfp-user-guide/README.md
Labels: approved, lgtm, size/M

#355 restructure installation and user instructions
  README.md
  guides/TEKTON_CHANGELOG.md
  guides/developer_guide.md
  guides/kfp-admin-guide.md
  guides/kfp-tekton-openshift.md
  guides/kfp-user-guide/README.md
  guides/kfp-user-guide/echo_pipeline.py
  guides/kfp-user-guide/images/experiment-page.png
  guides/kfp-user-guide/images/pipeline-page.png
  guides/kfp-user-guide/images/run-page.png
  guides/kfp-user-guide/images/upload-button.png
  guides/kfp-user-guide/images/upload-page.png
  guides/kfp_tekton_install.md
  guides/release.md
Labels: approved, lgtm, size/L

#357 Update docs for KFP 1.0.4 and prepare for release 0.4.0
  README.md
  VERSION
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
  sdk/python/tests/README.md
  sdk/python/tests/test_kfp_samples.sh
Labels: approved, lgtm, size/M

#359 SDK Packages Overview
  sdk/README.md
Labels: approved, lgtm, size/XS

#358 quick fix for SDK instructions
  sdk/README.md
Labels: approved, lgtm, size/M

#356 Making Andrew Butler a committer in KFP-Tekton project
  OWNERS
Labels: approved, lgtm, size/XS

#361 Fix broken doc links
  Makefile
  backend/src/apiserver/visualization/README.md
  guides/developer_guide.md
  guides/kfp-user-guide/README.md
  guides/kfp_tekton_install.md
  manifests/kustomize/README.md
  samples/README.md
  sdk/FEATURES.md
  sdk/README.md
  sdk/python/README.md
  sdk/python/setup.py
  sdk/python/tests/README.md
  sdk/sa-and-rbac.md
  tekton-catalog/kubectl-wrapper/README.md
  tools/mdtoc.sh
Labels: approved, lgtm, size/L

#360 Fix #340: handle big data passing with multi dependencies
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/create_component_from_func.py
  sdk/python/tests/compiler/testdata/create_component_from_func.yaml
  sdk/python/tests/compiler/testdata/create_component_from_func_component.yaml
Labels: approved, lgtm, size/L

#363 Verify all Markdown links are valid
  .travis.yml
  Makefile
  guides/kfp_tekton_install.md
  samples/kfp-tfx/tfx-taxi-on-prem/README.md
  samples/logging_s3/pipeline_log_to_s3_by_banzaicloud/pipeline_logging_output_s3_banzaicloud.md
  sdk/FEATURES.md
  sdk/python/setup.py
  tools/python/verify_doc_links.py
Labels: approved, lgtm, size/L

#328 feat(ui) Update UI to account for the When expression
  frontend/src/lib/StaticGraphParser.ts
  frontend/src/lib/WorkflowParser.ts
Labels: approved, lgtm, size/M

#370 add reference to watson blog post
  README.md
Labels: approved, lgtm, size/XS

#374 Simplify deployment docs for 1.2
  guides/kfp_tekton_install.md
Labels: approved, lgtm, size/L
