Repository kubeflow/kfp-tekton, pull requests merged in 2020-09, with the labels that each got.

#295 Address no logs achived to S3 with kubernets 1.6
  samples/logging_s3/pipeline_log_to_s3_by_fluentd_recommend/fluent-config.yaml
Labels: approved, lgtm, size/XS

#290 Make should use specified VENV
  .travis.yml
  Makefile
  sdk/python/tests/compiler/compiler_tests_e2e.py
Labels: approved, lgtm, size/S

#293 Fix permission typo in the e2e-mnist example
  samples/e2e-mnist/mnist.ipynb
Labels: approved, lgtm, size/XS

#281 Refactor artifact and logging client logics to server side
  backend/Dockerfile
  backend/metadata_writer/src/metadata_writer.py
  backend/src/apiserver/common/config.go
  backend/src/apiserver/common/const.go
  backend/src/apiserver/resource/resource_manager.go
  kfp-admin-guide.md
  manifests/kustomize/env/platform-agnostic/apiserver-deployment.yaml
  manifests/kustomize/env/platform-agnostic/kfp-pipeline-config.yaml
  manifests/kustomize/env/platform-agnostic/kfp-pipeline-install-config.yaml
  manifests/kustomize/env/platform-agnostic/kustomization.yaml
  manifests/kustomize/env/platform-agnostic/metadata-writer-deployment.yaml
  sdk/FEATURES.md
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/compiler/main.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/compiler_tests_e2e.py
  sdk/python/tests/compiler/testdata/affinity.yaml
  sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/compose.log
  sdk/python/tests/compiler/testdata/compose.yaml
  sdk/python/tests/compiler/testdata/condition.log
  sdk/python/tests/compiler/testdata/condition.yaml
  sdk/python/tests/compiler/testdata/exit_handler.log
  sdk/python/tests/compiler/testdata/exit_handler.yaml
  sdk/python/tests/compiler/testdata/hidden_output_file.log
  sdk/python/tests/compiler/testdata/hidden_output_file.yaml
  sdk/python/tests/compiler/testdata/imagepullsecrets.log
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
  sdk/python/tests/compiler/testdata/init_container.yaml
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
  sdk/python/tests/compiler/testdata/katib.yaml
  sdk/python/tests/compiler/testdata/load_from_yaml.log
  sdk/python/tests/compiler/testdata/load_from_yaml.yaml
  sdk/python/tests/compiler/testdata/loop_static.yaml
  sdk/python/tests/compiler/testdata/node_selector.yaml
  sdk/python/tests/compiler/testdata/parallel_join.yaml
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.log
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.yaml
  sdk/python/tests/compiler/testdata/parallel_join_with_artifacts.log
  sdk/python/tests/compiler/testdata/parallel_join_with_artifacts.yaml
  sdk/python/tests/compiler/testdata/parallel_join_with_logging.yaml
  sdk/python/tests/compiler/testdata/pipeline_transformers.yaml
  sdk/python/tests/compiler/testdata/pipelineparams.log
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic.log
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/retry.yaml
  sdk/python/tests/compiler/testdata/sequential.yaml
  sdk/python/tests/compiler/testdata/sidecar.log
  sdk/python/tests/compiler/testdata/sidecar.yaml
  sdk/python/tests/compiler/testdata/timeout.yaml
  sdk/python/tests/compiler/testdata/tolerations.yaml
  sdk/python/tests/compiler/testdata/volume.yaml
  sdk/python/tests/compiler/testdata/volume_logging.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
  sdk/python/tests/compiler/testdata/volume_snapshot_op.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
  tekton_kfp_guide.md
Labels: approved, lgtm, size/XXL

#302 restructure installation steps
  tekton_kfp_guide.md
Labels: size/S

#303 Prepare PyPi distribution for release 0.3.0
  sdk/README.md
  sdk/python/README.md
  sdk/python/setup.py
Labels: approved, lgtm, size/L

#311 updating the intro
  README.md
Labels: approved, lgtm, size/XS

#309 Remove persistentVolumeClaim by volumeClaimTemplate
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
Labels: approved, lgtm, size/M

#299 feat(backend): new server API to read run log. Fixes #298.
  backend/src/apiserver/archive/log.go
  backend/src/apiserver/archive/log_test.go
  backend/src/apiserver/archive/test/step-main_log.gz
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/config/config.json
  backend/src/apiserver/main.go
  backend/src/apiserver/resource/client_manager_fake.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/server/run_log_server.go
  backend/src/common/util/workflow.go
  frontend/server/app.ts
  frontend/server/configs.ts
  frontend/src/lib/Apis.ts
  frontend/src/pages/RunDetails.tsx
  go.mod
  go.sum
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-role.yaml
Labels: approved, lgtm, size/XL

#305 feat(ui) Update UI to get archived logs if available
  frontend/server/app.ts
  frontend/server/configs.ts
  frontend/server/handlers/pod-logs.ts
  frontend/server/workflow-helper.ts
  frontend/src/lib/Apis.ts
  frontend/src/pages/RunDetails.tsx
  kfp-admin-guide.md
Labels: approved, lgtm, size/L

#308 fix(sdk): fixes outputfile key formatting
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/hidden_output_file.log
  sdk/python/tests/compiler/testdata/hidden_output_file.py
  sdk/python/tests/compiler/testdata/hidden_output_file.yaml
Labels: approved, lgtm, size/M

#313 fix(sdk): Check whether the dependent component is a tekton task
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/condition_error.py
Labels: approved, lgtm, size/M

#314 Improve development manfests and docs
  README.md
  developer_guide.md
  manifests/kustomize/base/application/kustomization.yaml
  manifests/kustomize/base/cache-deployer/kustomization.yaml
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/env/platform-agnostic/metadata-writer-deployment.yaml
Labels: approved, lgtm, size/M
