Repository kubeflow/kfp-tekton, pull requests merged in 2021-03, with the labels that each got.

#479 Add 0.7.0 release template
  Makefile
  VERSION
  guides/kfp_tekton_install.md
  install/v0.7.0/kfp-tekton.yaml
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/tekton/catalog-condition.yaml
  manifests/kustomize/env/kfp-template/kustomization.yaml
  manifests/kustomize/env/kfp-template/tekton/kustomization.yaml
  manifests/kustomize/env/kfp-template/tekton/pipeline-loops/200-serviceaccount.yaml
  manifests/kustomize/env/kfp-template/tekton/pipeline-loops/201-clusterrole.yaml
  manifests/kustomize/env/kfp-template/tekton/pipeline-loops/201-role.yaml
  manifests/kustomize/env/kfp-template/tekton/pipeline-loops/201-rolebinding.yaml
  manifests/kustomize/env/kfp-template/tekton/pipeline-loops/202-clusterrolebinding.yaml
  manifests/kustomize/env/kfp-template/tekton/pipeline-loops/300-pipelineloop.yaml
  manifests/kustomize/env/kfp-template/tekton/pipeline-loops/500-controller.yaml
  manifests/kustomize/env/kfp-template/tekton/pipeline-loops/500-webhook-configuration.yaml
  manifests/kustomize/env/kfp-template/tekton/pipeline-loops/500-webhook.yaml
  manifests/kustomize/env/kfp-template/tekton/pipeline-loops/kustomization.yaml
  sdk/python/kfp_tekton/__init__.py
Labels: approved, lgtm, size/XXL

#483 fix: Migrate away from old katib api to ResourceOp.
  samples/trusted-ai/trusted-ai.py
Labels: approved, lgtm, size/M

#484 Add nested loops example
  samples/README.md
  samples/nested-loops/README.md
  samples/nested-loops/withitem_nested.py
Labels: approved, lgtm, size/M

#485 Add unique uuid to loop resources for pipeline versioning
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/conditions_and_loops.py
  sdk/python/tests/compiler/testdata/conditions_and_loops.yaml
  sdk/python/tests/compiler/testdata/conditions_and_loops_pipelineloop_cr1.yaml
  sdk/python/tests/compiler/testdata/loop_over_lightweight_output.py
  sdk/python/tests/compiler/testdata/loop_over_lightweight_output.yaml
  sdk/python/tests/compiler/testdata/loop_over_lightweight_output_pipelineloop_cr1.yaml
  sdk/python/tests/compiler/testdata/loop_static.py
  sdk/python/tests/compiler/testdata/loop_static.yaml
  sdk/python/tests/compiler/testdata/loop_static_pipelineloop_cr1.yaml
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.py
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving_pipelineloop_cr1.yaml
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving_pipelineloop_cr2.yaml
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving_pipelineloop_cr3.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.py
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
  sdk/python/tests/compiler/testdata/withitem_nested_pipelineloop_cr1.yaml
  sdk/python/tests/compiler/testdata/withitem_nested_pipelineloop_cr2.yaml
  sdk/python/tests/compiler/testdata/withparam_global.py
  sdk/python/tests/compiler/testdata/withparam_global.yaml
  sdk/python/tests/compiler/testdata/withparam_global_dict.py
  sdk/python/tests/compiler/testdata/withparam_global_dict.yaml
  sdk/python/tests/compiler/testdata/withparam_global_dict_pipelineloop_cr1.yaml
  sdk/python/tests/compiler/testdata/withparam_global_pipelineloop_cr1.yaml
  sdk/python/tests/compiler/testdata/withparam_output.py
  sdk/python/tests/compiler/testdata/withparam_output.yaml
  sdk/python/tests/compiler/testdata/withparam_output_dict.py
  sdk/python/tests/compiler/testdata/withparam_output_dict.yaml
  sdk/python/tests/compiler/testdata/withparam_output_dict_pipelineloop_cr1.yaml
  sdk/python/tests/compiler/testdata/withparam_output_pipelineloop_cr1.yaml
Labels: approved, lgtm, size/L

#491 fix(sdk): fix issue of nested dict param defined
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/withitem_nested.py
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
  sdk/python/tests/compiler/testdata/withitem_nested_pipelineloop_cr1.yaml
  sdk/python/tests/compiler/testdata/withitem_nested_pipelineloop_cr2.yaml
Labels: approved, lgtm, size/L

#494 Fix the copy result issue when it's already tekton result path
  sdk/python/kfp_tekton/compiler/_op_to_template.py
Labels: approved, lgtm, size/XS

#495 (ui) Fix duration of runs not showing
  backend/src/common/util/template_util.go
  frontend/src/lib/StatusUtils.ts
  frontend/src/lib/Utils.tsx
Labels: approved, lgtm, size/S

#502 Upgrade tekton version to v0.20.0 for pipeline-loop
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/S

#499 Enhance AnySequencer to make it an op
  sdk/FEATURES.md
  sdk/python/kfp_tekton/compiler/any_sequencer.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/compiler/pipeline_utils.py
  sdk/python/kfp_tekton/dsl/_any_seqencer.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/any_sequencer.log
  sdk/python/tests/compiler/testdata/any_sequencer.py
  sdk/python/tests/compiler/testdata/any_sequencer.yaml
Labels: approved, lgtm, size/L

#503 Fix any sequencer typo
  sdk/FEATURES.md
  sdk/python/kfp_tekton/tekton.py
  sdk/python/tests/compiler/testdata/any_sequencer.py
Labels: approved, lgtm, size/S

#510 Fix broken links from kubeflow website
  guides/kfp_tekton_install.md
Labels: approved, lgtm, size/XS

#517 Roll back the default_flow_style to fix the double quote issue
  sdk/python/kfp_tekton/compiler/yaml_utils.py
Labels: approved, lgtm, size/XS

#515 Support graph and recursion for tekton backend
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/recursion_while.py
  sdk/python/tests/compiler/testdata/recursion_while.yaml
  sdk/python/tests/compiler/testdata/recursion_while_pipelineloop_cr1.yaml
Labels: approved, lgtm, size/L
