Repository kubeflow/kfp-tekton, pull requests merged in 2021-01, with the labels that each got.

#400 fix(sdk): Fix nested condition bug
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/condition.py
  sdk/python/tests/compiler/testdata/condition.yaml
  sdk/python/tests/compiler/testdata/condition_dependency.yaml
Labels: approved, lgtm, size/M

#399 Any Sequencer implements
  sdk/FEATURES.md
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/kfp_tekton/compiler/any_sequencer.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/any_sequencer.py
  sdk/python/tests/compiler/testdata/any_sequencer.yaml
  tekton-catalog/any-sequencer/.gitignore
  tekton-catalog/any-sequencer/Dockerfile
  tekton-catalog/any-sequencer/Makefile
  tekton-catalog/any-sequencer/README.md
  tekton-catalog/any-sequencer/cmd/main.go
  tekton-catalog/any-sequencer/go.mod
  tekton-catalog/any-sequencer/go.sum
Labels: approved, lgtm, size/XXL

#401 fix(frontend): Any Sequencer UI support
  frontend/src/lib/StaticGraphParser.ts
  frontend/src/lib/WorkflowParser.ts
Labels: approved, lgtm, size/M

#404 Add a check for parent condition status in nested conditions
  frontend/src/lib/WorkflowParser.ts
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/condition.yaml
  sdk/python/tests/compiler/testdata/condition_dependency.yaml
Labels: approved, lgtm, size/M

#407 test: fix backend docker build used in travis. Fixes #405
  scripts/check_diff.sh
Labels: approved, lgtm, size/XS

#408 fix(frontend) fixes tasks being erroneously marked as 'skipped'
  frontend/src/lib/WorkflowParser.ts
Labels: approved, lgtm, size/XS

#386 Add SMTP server email notification example
  samples/exit-handler-email/README.md
  samples/exit-handler-email/component.yaml
  samples/exit-handler-email/pvc.yaml
  samples/exit-handler-email/secret.yaml
  samples/exit-handler-email/send-email.py
Labels: approved, lgtm, size/L

#395 Move argo fake client to Tekton fake client. Also update apiserver, common, and crd tests
  .travis.yml
  CONTRIBUTING.md
  Makefile
  backend/src/apiserver/client/argo.go
  backend/src/apiserver/client/tekton_fake.go
  backend/src/apiserver/client/workflow_fake.go
  backend/src/apiserver/resource/client_manager_fake.go
  backend/src/apiserver/resource/model_converter_test.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/resource/resource_manager_util_test.go
  backend/src/apiserver/server/experiment_server_test.go
  backend/src/apiserver/server/job_server_test.go
  backend/src/apiserver/server/pipeline_server_test.go
  backend/src/apiserver/server/pipeline_upload_server_test.go
  backend/src/apiserver/server/report_server_test.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/server/test/arguments-parameters.yaml
  backend/src/apiserver/server/test/invalid-workflow.yaml
  backend/src/apiserver/server/test/patched-arguments-parameters.yaml
  backend/src/apiserver/server/test/pipeline_plus_component/pipeline.yaml
  backend/src/apiserver/server/test_util.go
  backend/src/apiserver/server/util_test.go
  backend/src/common/client/api_server/pipeline_client_fake.go
  backend/src/common/client/api_server/run_client_fake.go
  backend/src/common/util/formatter_test.go
  backend/src/common/util/scheduled_workflow_test.go
  backend/src/common/util/template_util.go
  backend/src/common/util/template_util_test.go
  backend/src/common/util/workflow_test.go
  backend/src/crd/controller/scheduledworkflow/client/workflow_client_test.go
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow_test.go
  backend/src/crd/controller/viewer/main.go
  backend/src/crd/controller/viewer/reconciler/reconciler.go
  backend/src/crd/controller/viewer/reconciler/reconciler_test.go
  backend/src/crd/pkg/client/clientset/versioned/typed/scheduledworkflow/v1beta1/fake/fake_scheduledworkflow.go
Labels: approved, lgtm, size/XXL

#403 test: update persistence agent unit tests. Part of #388
  backend/src/agent/persistence/worker/metrics_reporter.go
  backend/src/agent/persistence/worker/metrics_reporter_test.go
  backend/src/agent/persistence/worker/persistence_worker_test.go
  backend/src/agent/persistence/worker/workflow_saver_test.go
Labels: approved, lgtm, size/L

#414 Enhance Any Sequencer
  tekton-catalog/any-sequencer/Makefile
  tekton-catalog/any-sequencer/cmd/main.go
Labels: approved, lgtm, size/M

#417 add any sequencer design pointer
  sdk/FEATURES.md
Labels: approved, lgtm, size/XS

#419 nit fix
  sdk/FEATURES.md
Labels: approved, size/XS

#420 test: include persistence agent unit tests in makefile run
  Makefile
Labels: approved, lgtm, size/XS

#421 Handle Tekton pipeline level variables
  sdk/FEATURES.md
  sdk/python/kfp_tekton/compiler/_tekton_hander.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.py
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.yaml
  sdk/python/tests/compiler/testdata/tekton_pipeline_variables.py
  sdk/python/tests/compiler/testdata/tekton_pipeline_variables.yaml
Labels: approved, lgtm, size/L

#422 Enhance Any Sequencer by using Tekton Pipeline Variables Fature
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/kfp_tekton/compiler/_tekton_hander.py
  sdk/python/kfp_tekton/compiler/any_sequencer.py
  sdk/python/tests/compiler/testdata/any_sequencer.yaml
Labels: approved, lgtm, size/M

#428 Add tekton 0.20 api support and update the corresponding go client packages
  README.md
  backend/README.md.rej.patch
  backend/src/apiserver/client/scheduled_workflow_fake.go
  backend/src/apiserver/client/subject_access_review.go
  backend/src/apiserver/client/subject_access_review_fake.go
  backend/src/apiserver/client/workflow_fake.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/resource/resource_manager_util.go
  backend/src/crd/controller/scheduledworkflow/client/swf_client.go
  backend/src/crd/controller/scheduledworkflow/client/workflow_client.go
  backend/src/crd/pkg/client/clientset/versioned/clientset.go
  backend/src/crd/pkg/client/clientset/versioned/typed/scheduledworkflow/v1beta1/fake/fake_scheduledworkflow.go
  backend/src/crd/pkg/client/clientset/versioned/typed/scheduledworkflow/v1beta1/scheduledworkflow.go
  backend/src/crd/pkg/client/clientset/versioned/typed/scheduledworkflow/v1beta1/scheduledworkflow_client.go
  backend/src/crd/pkg/client/informers/externalversions/scheduledworkflow/v1beta1/scheduledworkflow.go
  backend/test/integration/job_api_test.go
  backend/test/integration/pipeline_api_test.go
  backend/test/integration/pipeline_version_api_test.go
  backend/test/integration/upgrade_test.go
  go.mod
  go.sum
  guides/developer_guide.md
Labels: approved, lgtm, size/XXL

#434 generate init 0.6.0 release manifests
  install/v0.6.0/kfp-tekton.yaml
  manifests/kustomize/env/kfp-template/kustomization.yaml
Labels: approved, lgtm, size/XXL

#433 Update docs for release 0.6.0
  Makefile
  VERSION
  guides/kfp_tekton_install.md
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/setup.py
Labels: approved, lgtm, size/M

#437 fix(backend): Update python version in Dockerfile
  backend/Dockerfile
  backend/update_requirements.sh
Labels: approved, lgtm, platform/other, size/XS

#442 Move kubernetes from SDK requirements to test requirements
  sdk/python/requirements-test.txt
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
Labels: approved, lgtm, size/XS

#441 (ui) Fix status parser bug
  frontend/src/lib/WorkflowParser.ts
Labels: approved, lgtm, size/S

#445 fix references and syntax for Loops
  sdk/FEATURES.md
Labels: approved, size/XS

#446 followon- fix loops example syntax
  tekton-catalog/pipeline-loops/README.md
Labels: approved, lgtm, size/S

#448 Rephrase sidecars doc and fix some grammar
  sdk/FEATURES.md
Labels: approved, lgtm, size/M

#449 fix AnySequencer syntax
  tekton-catalog/any-sequencer/README.md
Labels: approved, lgtm, size/XS
