Repository kubeflow/kfp-tekton, pull requests merged in 2021-09, with the labels that each got.

#724 Update SDK versions
  sdk/python/README.md
  sdk/python/setup.py
Labels: approved, lgtm, size/XS

#723 Remove Argo template UI reference to avoid UX conflicts with v2 compatible mode
  frontend/src/lib/v2/WorkflowUtils.ts
  frontend/src/pages/PipelineDetails.tsx
Labels: approved, lgtm, size/S

#730 [test] update sample for katib
  samples/katib/early-stopping.ipynb
Labels: approved, lgtm, size/M

#732 Fix(sdk): chain nested conditions to work on non-dependable condition tasks.
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/condition_custom_task.py
  sdk/python/tests/compiler/testdata/condition_custom_task.yaml
  sdk/python/tests/compiler/testdata/condition_custom_task_noninlined.yaml
  sdk/python/tests/compiler/testdata/nested_custom_conditions.py
  sdk/python/tests/compiler/testdata/nested_custom_conditions.yaml
  sdk/python/tests/compiler/testdata/nested_custom_conditions_noninlined.yaml
Labels: approved, lgtm, size/L

#736 Optimize kfp-tekon SDK compile time
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/kfp_tekton/compiler/compiler.py
Labels: approved, lgtm, size/M

#739 fix(sdk) sanitize paths in artifact_items. Fixes #738
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/tests/compiler/testdata/many_results.yaml
  sdk/python/tests/compiler/testdata/many_results_noninlined.yaml
Labels: approved, size/XS

#740 [Only review]Fix #733 the pipeline parameter consumed as file
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/data_passing_pipeline_param_as_file.py
  sdk/python/tests/compiler/testdata/data_passing_pipeline_param_as_file.yaml
  sdk/python/tests/compiler/testdata/data_passing_pipeline_param_as_file_noninlined.yaml
Labels: approved, lgtm, size/XXL
