Repository kubeflow/kfp-tekton, pull requests merged in 2021-08, with the labels that each got.

#686 Update code to limit loop resource group name
  sdk/python/kfp_tekton/compiler/_k8s_helper.py
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/tekton.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/long_pipeline_name.yaml
  sdk/python/tests/compiler/testdata/long_pipeline_name_noninlined.yaml
  sdk/python/tests/compiler/testdata/long_recursive_group_name.py
  sdk/python/tests/compiler/testdata/long_recursive_group_name.yaml
  sdk/python/tests/compiler/testdata/long_recursive_group_name_noninlined.yaml
  sdk/python/tests/compiler/testdata/long_recursive_group_name_pipelineloop_cr1.yaml
  sdk/python/tests/compiler/testdata/loop_in_recursion.yaml
  sdk/python/tests/compiler/testdata/loop_in_recursion_noninlined.yaml
  sdk/python/tests/compiler/testdata/nested_recur_runafter.yaml
  sdk/python/tests/compiler/testdata/nested_recur_runafter_noninlined.yaml
  sdk/python/tests/compiler/testdata/recur_nested.yaml
  sdk/python/tests/compiler/testdata/recur_nested_noninlined.yaml
  sdk/python/tests/compiler/testdata/recur_nested_separate.yaml
  sdk/python/tests/compiler/testdata/recur_nested_separate_noninlined.yaml
  sdk/python/tests/compiler/testdata/recursion_while.yaml
  sdk/python/tests/compiler/testdata/recursion_while_noninlined.yaml
Labels: approved, lgtm, size/XL

#689 Enhance unit tests with local Tekton pipeline spec validation
  .github/workflows/kfp-tekton-unittests.yml
  Makefile
  tekton-catalog/pipeline-loops/cmd/cli/main.go
Labels: approved, lgtm, size/S

#685 remove ContainerOp from test cases - part 1
  sdk/python/tests/compiler/testdata/affinity.py
  sdk/python/tests/compiler/testdata/affinity.yaml
  sdk/python/tests/compiler/testdata/affinity_noninlined.yaml
  sdk/python/tests/compiler/testdata/any_sequencer.py
  sdk/python/tests/compiler/testdata/any_sequencer.yaml
  sdk/python/tests/compiler/testdata/any_sequencer_noninlined.yaml
  sdk/python/tests/compiler/testdata/artifact_passing_using_volume.py
  sdk/python/tests/compiler/testdata/basic_no_decorator.py
  sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
  sdk/python/tests/compiler/testdata/cache.py
  sdk/python/tests/compiler/testdata/cache.yaml
  sdk/python/tests/compiler/testdata/cache_noninlined.yaml
  sdk/python/tests/compiler/testdata/compose.py
  sdk/python/tests/compiler/testdata/compose.yaml
  sdk/python/tests/compiler/testdata/cond_recur.py
  sdk/python/tests/compiler/testdata/cond_recur.yaml
  sdk/python/tests/compiler/testdata/cond_recur_noninlined.yaml
  sdk/python/tests/compiler/testdata/condition.py
  sdk/python/tests/compiler/testdata/condition.yaml
  sdk/python/tests/compiler/testdata/condition_custom_task.py
  sdk/python/tests/compiler/testdata/condition_custom_task.yaml
  sdk/python/tests/compiler/testdata/condition_custom_task_noninlined.yaml
  sdk/python/tests/compiler/testdata/condition_dependency.py
  sdk/python/tests/compiler/testdata/condition_dependency.yaml
  sdk/python/tests/compiler/testdata/condition_dependency_noninlined.yaml
  sdk/python/tests/compiler/testdata/condition_noninlined.yaml
  sdk/python/tests/compiler/testdata/conditions_and_loops.py
  sdk/python/tests/compiler/testdata/conditions_and_loops.yaml
  sdk/python/tests/compiler/testdata/conditions_and_loops_noninlined.yaml
  sdk/python/tests/compiler/testdata/conditions_with_global_params.py
  sdk/python/tests/compiler/testdata/conditions_with_global_params.yaml
  sdk/python/tests/compiler/testdata/conditions_with_global_params_noninlined.yaml
  sdk/python/tests/compiler/testdata/create_component_from_func.py
  sdk/python/tests/compiler/testdata/create_component_from_func.yaml
  sdk/python/tests/compiler/testdata/create_component_from_func_noninlined.yaml
  sdk/python/tests/compiler/testdata/custom_task_recur_with_cond.py
  sdk/python/tests/compiler/testdata/custom_task_recur_with_cond.yaml
  sdk/python/tests/compiler/testdata/custom_task_recur_with_cond_noninlined.yaml
  sdk/python/tests/compiler/testdata/custom_task_ref.py
  sdk/python/tests/compiler/testdata/custom_task_ref.yaml
  sdk/python/tests/compiler/testdata/custom_task_spec.py
  sdk/python/tests/compiler/testdata/custom_task_spec.yaml
  sdk/python/tests/compiler/testdata/exit_handler.py
  sdk/python/tests/compiler/testdata/exit_handler.yaml
  sdk/python/tests/compiler/testdata/exit_handler_noninlined.yaml
  sdk/python/tests/compiler/testdata/hidden_output_file.py
  sdk/python/tests/compiler/testdata/hidden_output_file.yaml
  sdk/python/tests/compiler/testdata/hidden_output_file_noninlined.yaml
  sdk/python/tests/compiler/testdata/imagepullsecrets.py
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
  sdk/python/tests/compiler/testdata/imagepullsecrets_noninlined.yaml
Labels: approved, lgtm, size/XXL

#690 Add kfp name and id example
  samples/README.md
  samples/k8s-downstream-api/README.md
  samples/k8s-downstream-api/k8s-downstream-api.py
Labels: approved, lgtm, size/M

#691 remove ContainerOp from test cases - part 2
  sdk/python/tests/compiler/testdata/init_container.py
  sdk/python/tests/compiler/testdata/init_container.yaml
  sdk/python/tests/compiler/testdata/init_container_noninlined.yaml
  sdk/python/tests/compiler/testdata/katib.py
  sdk/python/tests/compiler/testdata/katib.yaml
  sdk/python/tests/compiler/testdata/katib_noninlined.yaml
  sdk/python/tests/compiler/testdata/long_param_name.py
  sdk/python/tests/compiler/testdata/long_param_name.yaml
  sdk/python/tests/compiler/testdata/long_param_name_noninlined.yaml
  sdk/python/tests/compiler/testdata/long_pipeline_name.py
  sdk/python/tests/compiler/testdata/long_pipeline_name.yaml
  sdk/python/tests/compiler/testdata/long_pipeline_name_noninlined.yaml
  sdk/python/tests/compiler/testdata/long_recursive_group_name.py
  sdk/python/tests/compiler/testdata/long_recursive_group_name.yaml
  sdk/python/tests/compiler/testdata/long_recursive_group_name_noninlined.yaml
  sdk/python/tests/compiler/testdata/long_recursive_group_name_pipelineloop_cr1.yaml
  sdk/python/tests/compiler/testdata/loop_in_recursion.py
  sdk/python/tests/compiler/testdata/loop_in_recursion.yaml
  sdk/python/tests/compiler/testdata/loop_in_recursion_noninlined.yaml
  sdk/python/tests/compiler/testdata/loop_over_lightweight_output.py
  sdk/python/tests/compiler/testdata/loop_over_lightweight_output.yaml
  sdk/python/tests/compiler/testdata/loop_over_lightweight_output_noninlined.yaml
  sdk/python/tests/compiler/testdata/loop_static.py
  sdk/python/tests/compiler/testdata/loop_static.yaml
  sdk/python/tests/compiler/testdata/loop_static_noninlined.yaml
  sdk/python/tests/compiler/testdata/loop_static_with_parallelism.py
  sdk/python/tests/compiler/testdata/loop_static_with_parallelism.yaml
  sdk/python/tests/compiler/testdata/loop_static_with_parallelism_noninlined.yaml
  sdk/python/tests/compiler/testdata/nested_recur_custom_task.py
  sdk/python/tests/compiler/testdata/nested_recur_custom_task.yaml
  sdk/python/tests/compiler/testdata/nested_recur_custom_task_noninlined.yaml
  sdk/python/tests/compiler/testdata/nested_recur_params.py
  sdk/python/tests/compiler/testdata/nested_recur_params.yaml
  sdk/python/tests/compiler/testdata/nested_recur_params_noninlined.yaml
  sdk/python/tests/compiler/testdata/nested_recur_runafter.py
  sdk/python/tests/compiler/testdata/nested_recur_runafter.yaml
  sdk/python/tests/compiler/testdata/nested_recur_runafter_noninlined.yaml
  sdk/python/tests/compiler/testdata/node_selector.py
  sdk/python/tests/compiler/testdata/node_selector.yaml
  sdk/python/tests/compiler/testdata/node_selector_noninlined.yaml
Labels: approved, lgtm, size/XXL

#693 remove ContainerOp from test cases - part 3
  sdk/python/tests/compiler/testdata/opsgroups.py
  sdk/python/tests/compiler/testdata/opsgroups.yaml
  sdk/python/tests/compiler/testdata/parallel_join.py
  sdk/python/tests/compiler/testdata/parallel_join.yaml
  sdk/python/tests/compiler/testdata/parallel_join_noninlined.yaml
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.py
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.yaml
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars_noninlined.yaml
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.py
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving_noninlined.yaml
  sdk/python/tests/compiler/testdata/pipeline_transformers.py
  sdk/python/tests/compiler/testdata/pipeline_transformers.yaml
  sdk/python/tests/compiler/testdata/pipeline_transformers_noninlined.yaml
  sdk/python/tests/compiler/testdata/pipelineparams.py
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/pipelineparams_noninlined.yaml
  sdk/python/tests/compiler/testdata/recur_cond.py
  sdk/python/tests/compiler/testdata/recur_cond.yaml
  sdk/python/tests/compiler/testdata/recur_cond_noninlined.yaml
  sdk/python/tests/compiler/testdata/recur_nested.py
  sdk/python/tests/compiler/testdata/recur_nested.yaml
  sdk/python/tests/compiler/testdata/recur_nested_noninlined.yaml
  sdk/python/tests/compiler/testdata/recur_nested_separate.yaml
  sdk/python/tests/compiler/testdata/recur_nested_separate_noninlined.yaml
  sdk/python/tests/compiler/testdata/recursion_while.py
  sdk/python/tests/compiler/testdata/recursion_while.yaml
  sdk/python/tests/compiler/testdata/recursion_while_noninlined.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic.py
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic_noninlined.yaml
  sdk/python/tests/compiler/testdata/retry.py
  sdk/python/tests/compiler/testdata/retry.yaml
  sdk/python/tests/compiler/testdata/retry_noninlined.yaml
  sdk/python/tests/compiler/testdata/sequential.py
  sdk/python/tests/compiler/testdata/sequential.yaml
  sdk/python/tests/compiler/testdata/sequential_noninlined.yaml
  sdk/python/tests/compiler/testdata/set_display_name.py
  sdk/python/tests/compiler/testdata/set_display_name.yaml
  sdk/python/tests/compiler/testdata/set_display_name_noninlined.yaml
  sdk/python/tests/compiler/testdata/sidecar.py
  sdk/python/tests/compiler/testdata/sidecar.yaml
  sdk/python/tests/compiler/testdata/sidecar_noninlined.yaml
  sdk/python/tests/compiler/testdata/tekton_custom_task.py
  sdk/python/tests/compiler/testdata/tekton_custom_task.yaml
  sdk/python/tests/compiler/testdata/tekton_custom_task_noninlined.yaml
  sdk/python/tests/compiler/testdata/tekton_pipeline_conf.py
  sdk/python/tests/compiler/testdata/tekton_pipeline_conf.yaml
  sdk/python/tests/compiler/testdata/tekton_pipeline_conf_noninlined.yaml
  sdk/python/tests/compiler/testdata/tekton_pipeline_variables.py
  sdk/python/tests/compiler/testdata/tekton_pipeline_variables.yaml
  sdk/python/tests/compiler/testdata/timeout.py
  sdk/python/tests/compiler/testdata/timeout.yaml
  sdk/python/tests/compiler/testdata/timeout_noninlined.yaml
  sdk/python/tests/compiler/testdata/tolerations.py
  sdk/python/tests/compiler/testdata/tolerations.yaml
  sdk/python/tests/compiler/testdata/tolerations_noninlined.yaml
  sdk/python/tests/compiler/testdata/uri_artifacts.py
Labels: approved, lgtm, size/XXL

#692 Migrate volume and loop unit tests to component.yaml and verify with v2
  sdk/FEATURES.md
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/volume.py
  sdk/python/tests/compiler/testdata/volume.yaml
  sdk/python/tests/compiler/testdata/volume_noninlined.yaml
  sdk/python/tests/compiler/testdata/volume_op.py
  sdk/python/tests/compiler/testdata/volume_op.yaml
  sdk/python/tests/compiler/testdata/volume_op_noninlined.yaml
  sdk/python/tests/compiler/testdata/volume_snapshot_op.log
  sdk/python/tests/compiler/testdata/volume_snapshot_op.py
  sdk/python/tests/compiler/testdata/volume_snapshot_op.yaml
  sdk/python/tests/compiler/testdata/volume_snapshot_op_noninlined.yaml
  sdk/python/tests/compiler/testdata/withitem_multi_nested.py
  sdk/python/tests/compiler/testdata/withitem_multi_nested.yaml
  sdk/python/tests/compiler/testdata/withitem_multi_nested_noninlined.yaml
  sdk/python/tests/compiler/testdata/withitem_multi_nested_pipelineloop_cr1.yaml
  sdk/python/tests/compiler/testdata/withitem_multi_nested_pipelineloop_cr2.yaml
  sdk/python/tests/compiler/testdata/withitem_multi_nested_pipelineloop_cr3.yaml
  sdk/python/tests/compiler/testdata/withitem_multi_nested_pipelineloop_cr4.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.py
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
  sdk/python/tests/compiler/testdata/withitem_nested_noninlined.yaml
  sdk/python/tests/compiler/testdata/withparam_global.py
  sdk/python/tests/compiler/testdata/withparam_global.yaml
  sdk/python/tests/compiler/testdata/withparam_global_dict.py
  sdk/python/tests/compiler/testdata/withparam_global_dict.yaml
  sdk/python/tests/compiler/testdata/withparam_global_dict_noninlined.yaml
  sdk/python/tests/compiler/testdata/withparam_global_dict_pipelineloop_cr1.yaml
  sdk/python/tests/compiler/testdata/withparam_global_noninlined.yaml
  sdk/python/tests/compiler/testdata/withparam_global_pipelineloop_cr1.yaml
  sdk/python/tests/compiler/testdata/withparam_output.py
  sdk/python/tests/compiler/testdata/withparam_output.yaml
  sdk/python/tests/compiler/testdata/withparam_output_dict.py
  sdk/python/tests/compiler/testdata/withparam_output_dict.yaml
  sdk/python/tests/compiler/testdata/withparam_output_dict_noninlined.yaml
  sdk/python/tests/compiler/testdata/withparam_output_dict_pipelineloop_cr1.yaml
  sdk/python/tests/compiler/testdata/withparam_output_noninlined.yaml
  sdk/python/tests/compiler/testdata/withparam_output_pipelineloop_cr1.yaml
Labels: approved, lgtm, size/XXL

#696 Fix e2e test case
  sdk/python/tests/compiler/testdata/resourceop_basic.py
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic_noninlined.yaml
Labels: approved, lgtm, size/S

#698 Fit unittest for loop
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/XS

#699 Update kfp sdk dependency to 1.7
  sdk/python/README.md
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
  sdk/python/tests/README.md
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/big_data_passing_noninlined.yaml
  sdk/python/tests/test_kfp_samples.sh
Labels: approved, lgtm, size/M

#700 Upgrade Tekton to 0.27
  README.md
  go.mod
  go.sum
  guides/developer_guide.md
  guides/kfp_tekton_install.md
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-dashboard/tekton-dashboard-release.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-release.yaml
  sdk/README.md
  sdk/python/README.md
Labels: approved, lgtm, size/L

#705 Move kfp sdk dependency to 1.7.1
  sdk/python/README.md
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
  sdk/python/tests/README.md
  sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
  sdk/python/tests/test_kfp_samples.sh
Labels: approved, lgtm, size/S

#707 define cancel patch as global var and initialize it at package init
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/M

#702 Make results to store in multi-steps if needed
  Makefile
  sdk/FEATURES.md
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/many_results.py
  sdk/python/tests/compiler/testdata/many_results.yaml
  sdk/python/tests/compiler/testdata/many_results_noninlined.yaml
  sdk/python/tests/compiler/testdata/many_results_with_warnings.py
  sdk/python/tests/compiler/testdata/many_results_with_warnings.yaml
  sdk/python/tests/compiler/testdata/many_results_with_warnings_noninlined.yaml
Labels: approved, lgtm, size/XL

#706 feat(pipelineloop): Upgrade Tekton to 0.27 for pipelineloop controller. (#703)
  tekton-catalog/pipeline-loops/cmd/webhook/main.go
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/M

#711 Fix(sdk): Tekton copy result step sanitization
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/many_results.py
  sdk/python/tests/compiler/testdata/many_results.yaml
  sdk/python/tests/compiler/testdata/many_results_noninlined.yaml
Labels: approved, lgtm, size/L

#708 Remove containerOp for pipelineparam and raw input samples
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.py
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
  sdk/python/tests/compiler/testdata/input_artifact_raw_value_noninlined.yaml
  sdk/python/tests/compiler/testdata/pipelineparams.py
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/pipelineparams_noninlined.yaml
Labels: approved, lgtm, size/L

#709 feat(sdk): Update SDK to support custom task timeout on Tekton 0.27
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/custom_task_ref_timeout.py
  sdk/python/tests/compiler/testdata/custom_task_ref_timeout.yaml
Labels: approved, lgtm, size/L

#717 name consistency
  README.md
Labels: approved, lgtm, size/S

#718 Update KFP SDK version to 1.7.2, create KFP-TEKTON 1.0.0 release
  .kfp-rebase-version
  Makefile
  VERSION
  guides/kfp_tekton_install.md
  install/v1.0.0/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  sdk/python/kfp_tekton/__init__.py
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
  sdk/python/tests/README.md
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic_noninlined.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
  sdk/python/tests/compiler/testdata/volume_op_noninlined.yaml
  sdk/python/tests/test_kfp_samples.sh
  sdk/python/tests/test_kfp_samples_report.txt
Labels: approved, lgtm, size/XXL

#719 Fix(sdk): fix KFP 1.7.2 SDK dependency
  sdk/python/requirements.txt
Labels: approved, lgtm, size/XS

#721 Update CI pipeline with new dependency flow
  .tekton/pipeline.yaml
Labels: approved, lgtm, size/S

#722 Update reference to 1.0 release
  README.md
Labels: approved, lgtm, size/XS
