Repository kubeflow/kfp-tekton, pull requests merged in 2021-04, with the labels that each got.

#521 fix(sdk): Fix long resource name
  sdk/python/kfp_tekton/compiler/_k8s_helper.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/k8s_helper_tests.py
  sdk/python/tests/compiler/testdata/long_pipeline_name.py
  sdk/python/tests/compiler/testdata/long_pipeline_name.yaml
  sdk/python/tests/compiler/testdata/long_pipeline_name_pipelineloop_cr1.yaml
  sdk/python/tests/compiler/testdata/recursion_while.yaml
Labels: approved, lgtm, size/L

#523 Make pipelineloop test cases work well after upgrade to tekton-v0.20
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
  tekton-catalog/pipeline-loops/test/build_logs.go
  tekton-catalog/pipeline-loops/test/clients.go
  tekton-catalog/pipeline-loops/test/e2e-common.sh
  tekton-catalog/pipeline-loops/test/e2e-taskloops.sh
  tekton-catalog/pipeline-loops/test/e2e-tests.sh
  tekton-catalog/pipeline-loops/test/presubmit-tests.sh
  tekton-catalog/pipeline-loops/test/wait.go
Labels: approved, lgtm, size/XL

#524 Clean up sdk
  sdk/python/kfp_tekton/compiler/compiler.py
Labels: approved, lgtm, size/S

#525 Fix(sdk): Fix nested loop params issue, and ensure multi nested loop works well
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/withitem_multi_nested.py
  sdk/python/tests/compiler/testdata/withitem_multi_nested.yaml
  sdk/python/tests/compiler/testdata/withitem_multi_nested_pipelineloop_cr1.yaml
  sdk/python/tests/compiler/testdata/withitem_multi_nested_pipelineloop_cr2.yaml
  sdk/python/tests/compiler/testdata/withitem_multi_nested_pipelineloop_cr3.yaml
  sdk/python/tests/compiler/testdata/withitem_multi_nested_pipelineloop_cr4.yaml
Labels: approved, lgtm, size/L

#526 feature(sdk): Add custom task definition support
  manifests/kustomize/env/platform-agnostic/kfp-pipeline-config.yaml
  samples/README.md
  samples/tekton-custom-task/README.md
  samples/tekton-custom-task/tekton-custom-task.py
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/tekton.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/tekton_custom_task.py
  sdk/python/tests/compiler/testdata/tekton_custom_task.yaml
Labels: approved, lgtm, size/L

#528 fix(sdk): Fix regex parsing for custom task to handle multiple pipeline params
  samples/tekton-custom-task/tekton-custom-task.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/tekton_custom_task.py
  sdk/python/tests/compiler/testdata/tekton_custom_task.yaml
Labels: approved, lgtm, size/M

#533 [test] fix tekton-catalog test script
  .tekton/tekton-catalog/pipeline.yaml
  scripts/deploy/iks/tekton-catalog/deploy-pipeline-loops-e2e.sh
Labels: approved, lgtm, size/XS

#538 [test] Remove tekton installation task
  .tekton/listener.yaml
  .tekton/pipeline.yaml
  .tekton/task.yaml
  scripts/deploy/iks/build-image.sh
  scripts/deploy/iks/publish-image.sh
Labels: approved, lgtm, size/L

#541 fix(sdk): fix artifacts of ops with long names
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/artifacts_of_ops_with_long_names.py
Labels: approved, lgtm, size/L

#543 Add extra label to sub pr
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/XS

#537 Fix viper flags and labels/annotations injections on custom task
  backend/src/apiserver/common/config.go
  backend/src/apiserver/resource/resource_manager.go
  guides/kfp-admin-guide.md
Labels: approved, lgtm, size/M

#544 (ui) Update UI to render custom tasks
  frontend/src/lib/ParserUtils.ts
  frontend/src/lib/StaticGraphParser.ts
  frontend/src/lib/StatusUtils.ts
  frontend/src/lib/Utils.tsx
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/Status.tsx
Labels: approved, lgtm, size/L

#545 Support Tekton PipelineRunStopping status
  backend/src/apiserver/storage/run_store.go
  frontend/src/lib/StatusUtils.ts
Labels: approved, lgtm, size/XS

#539 Support the simple condition for any sequencer
  sdk/python/kfp_tekton/tekton.py
  sdk/python/tests/compiler/testdata/any_sequencer.py
  sdk/python/tests/compiler/testdata/any_sequencer.yaml
  tekton-catalog/any-sequencer/Makefile
  tekton-catalog/any-sequencer/cmd/main.go
  tekton-catalog/any-sequencer/cmd/root.go
  tekton-catalog/any-sequencer/go.mod
  tekton-catalog/any-sequencer/go.sum
  tekton-catalog/any-sequencer/main.go
Labels: approved, lgtm, size/XXL

#550 Adjust the any sequencer example to make it more reasonable
  sdk/python/tests/compiler/testdata/any_sequencer.log
  sdk/python/tests/compiler/testdata/any_sequencer.py
  sdk/python/tests/compiler/testdata/any_sequencer.yaml
Labels: approved, lgtm, size/S

#549 Fix long param compile errors
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/artifacts_of_ops_with_long_names.py
  sdk/python/tests/compiler/testdata/long_param_name.py
  sdk/python/tests/compiler/testdata/long_param_name.yaml
Labels: approved, lgtm, size/L

#556 Fix recursive loop bug with no sub_group.ops
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/recur_cond.py
  sdk/python/tests/compiler/testdata/recur_cond.yaml
  sdk/python/tests/compiler/testdata/recur_cond_pipelineloop_cr1.yaml
Labels: approved, lgtm, size/L

#560 Update katib sample
  samples/katib/early-stopping.ipynb
Labels: approved, lgtm, size/L

#559 Create release 0.8.0 standalone install
  Makefile
  guides/kfp_tekton_install.md
  install/v0.8.0/kfp-tekton.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/env/kfp-template/application-crd.yaml
  manifests/kustomize/env/kfp-template/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  sdk/README.md
Labels: approved, lgtm, size/XXL

#557 Fix multiple any-sequencer issues
  sdk/FEATURES.md
  sdk/python/kfp_tekton/tekton.py
  tekton-catalog/any-sequencer/cmd/root.go
Labels: approved, lgtm, size/M

#563 Fix broken Kubeflow doc links to map with the KF 1.3 website
  sdk/python/README.md
Labels: approved, lgtm, size/XS

#564 (ui) Update any-sequencer dependency parsing
  frontend/src/lib/StaticGraphParser.ts
  frontend/src/lib/WorkflowParser.ts
Labels: approved, lgtm, size/L

#562 Fix the issue when there's a conditional loop
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/cond_recur.py
  sdk/python/tests/compiler/testdata/cond_recur.yaml
  sdk/python/tests/compiler/testdata/cond_recur_pipelineloop_cr1.yaml
Labels: approved, lgtm, size/L

#565 Apply to be reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#567 Clean up and revert cache image env on manifests
  install/v0.8.0/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/installs/generic/kustomization.yaml
  manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
Labels: approved, lgtm, size/S

#568 [test] add more test cases to toolchain pipelines
  .tekton/pipeline.yaml
  .tekton/task.yaml
  scripts/deploy/iks/build-image-dind.sh
  scripts/deploy/iks/publish-image.sh
  scripts/deploy/iks/tekton-catalog/build-binaries.sh
  scripts/deploy/iks/tekton-catalog/deploy-pipeline-loops-e2e.sh
Labels: approved, lgtm, size/XL

#571 [test] move kubeclient test case
  .tekton/listener.yaml
  .tekton/pipeline.yaml
  .tekton/task.yaml
  scripts/deploy/iks/helper-functions.sh
  scripts/deploy/iks/tekton-catalog/cleanup.sh
  scripts/deploy/iks/tekton-catalog/deploy-kubectl-wrapper-e2e.sh
Labels: approved, lgtm, size/L

#573 Add bagdes to SDK Readme
  sdk/README.md
  sdk/python/README.md
Labels: approved, lgtm, size/XS

#572 Enhance error messages for resource op and artifact tracking
  manifests/kustomize/base/pipeline/kfp-pipeline-config.yaml
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/tests/compiler/testdata/artifact_passing_using_volume.log
  sdk/python/tests/compiler/testdata/load_from_yaml.log
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/volume_op.log
  sdk/python/tests/compiler/testdata/volume_op.yaml
  sdk/python/tests/compiler/testdata/volume_snapshot_op.yaml
  tekton-catalog/kubectl-wrapper/cmd/client/main.go
  tekton-catalog/kubectl-wrapper/deploy/kubectl-deploy.yaml
Labels: approved, lgtm, size/M

#575 Update release manifests and openshift docs
  guides/kfp-tekton-openshift.md
  guides/kfp_tekton_install.md
  install/v0.8.0/kfp-tekton.yaml
  manifests/kustomize/third-party/openshift/standalone/anyuid-scc.yaml
  manifests/kustomize/third-party/openshift/standalone/kustomization.yaml
  manifests/kustomize/third-party/openshift/standalone/privileged-scc.yaml
Labels: approved, lgtm, size/L

#500 feat(script): Deploy kubeflow to IBM Cloud IKS vpc-gen2, using this script.
  scripts/deploy/iks/README.md
  scripts/deploy/iks/deploy-ibm-vpc.sh
  scripts/deploy/iks/deploy-kfp-ibm-vpc.sh
Labels: approved, lgtm, size/XL
