Repository kubeflow/kfp-tekton, pull requests merged in 2021-02, with the labels that each got.

#435 Add iks deployment scripts
  scripts/deploy/deploy-kfp.sh
  scripts/deploy/deploy-tekton.sh
  scripts/deploy/helper_functions.sh
  scripts/deploy/undeploy-kfp.sh
  scripts/deploy/undeploy-tekton.sh
Labels: approved, lgtm, size/L

#444 Enhance Email notification according to feedback
  components/notification/component.yaml
  samples/exit-handler-email/README.md
  samples/exit-handler-email/component.yaml
  samples/exit-handler-email/send-email.py
Labels: approved, lgtm, size/L

#452 Fix loop issue that the loop param is from task output
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/loop_over_lightweight_output.py
  sdk/python/tests/compiler/testdata/loop_over_lightweight_output.yaml
  sdk/python/tests/compiler/testdata/loop_over_lightweight_output_pipelineloop_cr1.yaml
  sdk/python/tests/compiler/testdata/withparam_output.log
  sdk/python/tests/compiler/testdata/withparam_output.py
  sdk/python/tests/compiler/testdata/withparam_output.yaml
  sdk/python/tests/compiler/testdata/withparam_output_pipelineloop_cr1.yaml
Labels: approved, lgtm, size/L

#451 fix(ui) Use task_display_name annotation when displaying run metrics
  frontend/src/lib/CompareUtils.ts
  frontend/src/lib/ParserUtils.ts
Labels: approved, lgtm, size/S

#455 fix(backend): Fix condition with multi parameter issue
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/conditions_with_global_params.log
  sdk/python/tests/compiler/testdata/conditions_with_global_params.py
  sdk/python/tests/compiler/testdata/conditions_with_global_params.yaml
Labels: approved, lgtm, size/L

#450 test: Add IKS toolchains scripts
  scripts/deploy/deploy-kfp.sh
  scripts/deploy/deploy-tekton.sh
  scripts/deploy/iks/Dockerfile
  scripts/deploy/iks/README.md
  scripts/deploy/iks/build-image-dind.sh
  scripts/deploy/iks/build-image.sh
  scripts/deploy/iks/deploy-dind.sh
  scripts/deploy/iks/deploy-kfp.sh
  scripts/deploy/iks/deploy-tekton.sh
  scripts/deploy/iks/e2e-test.sh
  scripts/deploy/iks/helper-functions.sh
  scripts/deploy/iks/run-test.sh
  scripts/deploy/iks/test.sh
  scripts/deploy/iks/undeploy-kfp.sh
  scripts/deploy/iks/undeploy-tekton.sh
  scripts/deploy/iks/workflow.png
  scripts/deploy/undeploy-kfp.sh
  scripts/deploy/undeploy-tekton.sh
Labels: approved, lgtm, size/XXL

#456 fix(backend): Fix condition with loop together issue
  .gitignore
  sdk/python/kfp_tekton/compiler/_tekton_hander.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/conditions_and_loops.log
  sdk/python/tests/compiler/testdata/conditions_and_loops.py
  sdk/python/tests/compiler/testdata/conditions_and_loops.yaml
  sdk/python/tests/compiler/testdata/conditions_and_loops_pipelineloop_cr1.yaml
Labels: approved, lgtm, size/XL

#424 Enable cache server for tekton
  backend/src/cache/client/pod_fake.go
  backend/src/cache/client/tekton.go
  backend/src/cache/client/tekton_fake.go
  backend/src/cache/client_manager.go
  backend/src/cache/deployer/deploy-cache-service.sh
  backend/src/cache/server/client_manager_fake.go
  backend/src/cache/server/mutation.go
  backend/src/cache/server/mutation_test.go
  backend/src/cache/server/watcher.go
  go.sum
  manifests/kustomize/base/cache/cache-role.yaml
Labels: approved, lgtm, size/XL

#458 Add CI and makefile tests for cache server
  Makefile
  guides/developer_guide.md
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/env/kfp-template/kustomization.yaml
Labels: approved, lgtm, size/S

#459 test: Add pipeline yaml for tekton pipeline
  .tekton/listener.yaml
  .tekton/pipeline.yaml
  .tekton/task.yaml
  scripts/deploy/iks/build-image.sh
  scripts/deploy/iks/e2e-test.sh
Labels: approved, lgtm, size/XL

#462 fix: failed to build api-server image
  backend/Dockerfile
Labels: approved, lgtm, size/XS

#460 feat(backend): Support loop pipelineruns of defining dictionaries params
  sdk/FEATURES.md
  sdk/python/kfp_tekton/compiler/_tekton_hander.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.py
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving_pipelineloop_cr1.yaml
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving_pipelineloop_cr2.yaml
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving_pipelineloop_cr3.yaml
  sdk/python/tests/compiler/testdata/withparam_global_dict.log
  sdk/python/tests/compiler/testdata/withparam_global_dict.py
  sdk/python/tests/compiler/testdata/withparam_global_dict.yaml
  sdk/python/tests/compiler/testdata/withparam_global_dict_pipelineloop_cr1.yaml
  sdk/python/tests/compiler/testdata/withparam_output_dict.log
  sdk/python/tests/compiler/testdata/withparam_output_dict.py
  sdk/python/tests/compiler/testdata/withparam_output_dict.yaml
  sdk/python/tests/compiler/testdata/withparam_output_dict_pipelineloop_cr1.yaml
  tekton-catalog/pipeline-loops/examples/pipelinespec-with-nested-loop.yaml
  tekton-catalog/pipeline-loops/examples/pipelinespec-with-run-dict-value.yaml
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/XXL

#463 Remove python 3.5 support
  .travis.yml
  sdk/README.md
  sdk/python/README.md
Labels: approved, lgtm, size/S

#465 Remove Python 3.5 support (2)
  api/v2alpha1/python/setup.py
  sdk/python/setup.py
  sdk/python/tests/compiler/testdata/basic_no_decorator.py
  sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
  sdk/python/tests/compiler/testdata/compose.py
  sdk/python/tests/compiler/testdata/compose.yaml
  sdk/python/tests/compiler/testdata/imagepullsecrets.py
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
Labels: approved, lgtm, size/S

#466 test: Send results to slack channel
  .tekton/listener.yaml
  .tekton/pipeline.yaml
  .tekton/task.yaml
  scripts/deploy/iks/e2e-test.sh
Labels: approved, lgtm, size/M

#464 docs: Fixed the code formatting of the echo example.
  guides/kfp-user-guide/README.md
Labels: approved, lgtm, size/XS

#471 Fix parallel_join_with_argo_vars pipeline (#470)
  guides/kfp_tekton_install.md
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.log
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.py
  sdk/python/tests/compiler/testdata/parallel_join_with_argo_vars.yaml
Labels: approved, lgtm, size/S

#473 Fix deprecated link
  guides/kfp_tekton_install.md
Labels: approved, lgtm, size/XS

#472 test: Add delivery pipeline scripts for tekton-catalog images.
  .tekton/tekton-catalog/README.md
  .tekton/tekton-catalog/listener.yaml
  .tekton/tekton-catalog/pipeline.yaml
  .tekton/tekton-catalog/tasks.yaml
  scripts/deploy/iks/Dockerfile
  scripts/deploy/iks/helper-functions.sh
  scripts/deploy/iks/tekton-catalog/build-binaries.sh
  scripts/deploy/iks/tekton-catalog/cleanup.sh
  scripts/deploy/iks/tekton-catalog/create-dockerconfig-secret.sh
  scripts/deploy/iks/tekton-catalog/deploy-any-sequencer-e2e.sh
  scripts/deploy/iks/tekton-catalog/deploy-kubectl-wrapper-e2e.sh
  scripts/deploy/iks/tekton-catalog/deploy-pipeline-loops-e2e.sh
  scripts/deploy/iks/tekton-catalog/iks-authenticate.sh
  scripts/deploy/iks/tekton-catalog/publish-any-sequencer-image.sh
  scripts/deploy/iks/tekton-catalog/publish-kubectl-wrapper-image.sh
  scripts/deploy/iks/tekton-catalog/publish-pipeline-loops-images.sh
  scripts/deploy/iks/tekton-catalog/setup-kubectl-wrapper-deploy.sh
  scripts/deploy/iks/tekton-catalog/setup-pipeline-loops-deploy.sh
  tekton-catalog/any-sequencer/Dockerfile
  tekton-catalog/kubectl-wrapper/Dockerfile
  tekton-catalog/kubectl-wrapper/Makefile
  tekton-catalog/pipeline-loops/Dockerfile
  tekton-catalog/pipeline-loops/Makefile
Labels: approved, lgtm, size/XXL

#476 Update Tekton API client to 0.21
  README.md
  go.mod
  go.sum
  guides/developer_guide.md
  guides/kfp-tekton-openshift.md
  guides/kfp_tekton_install.md
  sdk/README.md
  sdk/python/README.md
Labels: approved, lgtm, size/L
