Repository kubeflow/kfp-tekton, pull requests merged in 2021-11, with the labels that each got.

#753 Add csi-s3 storage class as big data passing storage
  guides/developer_guide.md
  manifests/kustomize/README.md
  manifests/kustomize/env/plain/kustomization.yaml
  manifests/kustomize/third-party/kfp-csi-s3/csi-s3-deployment.yaml
  manifests/kustomize/third-party/kfp-csi-s3/csi-s3-secret.yaml
  manifests/kustomize/third-party/kfp-csi-s3/kustomization.yaml
  manifests/kustomize/third-party/kfp-csi-s3/params.yaml
  sdk/README.md
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/create_component_from_func.yaml
  sdk/python/tests/compiler/testdata/data_passing_pipeline_complete.yaml
  sdk/python/tests/compiler/testdata/data_passing_pipeline_param_as_file.yaml
Labels: approved, lgtm, size/XL

#768 Add UI backward compatibility for dsl.container syntax
  frontend/src/lib/WorkflowParser.ts
  sdk/python/kfp_tekton/compiler/compiler.py
Labels: approved, lgtm, size/S

#773 Add performance test script
  sdk/python/tests/compiler/performance_tests.py
Labels: area/testing, approved, lgtm, size/L

#777 Fix archived logs for custom tasks
  backend/src/apiserver/resource/resource_manager.go
Labels: approved, lgtm, size/L

#776 expose current iteration item to pipelinerun's annotation
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/M

#782 feat(sdk): factor out the images to use in copying steps
  sdk/python/kfp_tekton/compiler/_op_to_template.py
Labels: approved, lgtm, size/XS

#781 feat(pipelineloop): Implement retry for pipelineloop controller.
  tekton-catalog/pipeline-loops/cmd/webhook/main.go
  tekton-catalog/pipeline-loops/examples/loop-example-basic.yaml
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/L

#787 feat(pipelineloop): Support workspaces for pipelineLoop.
  README.md
  tekton-catalog/pipeline-loops/examples/loop-example-workspaces.yaml
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/L

#785 [test] Add taskRun and run into the report
  sdk/python/tests/compiler/performance_tests.py
Labels: approved, lgtm, size/M

#790 support separator string for iteration string param
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/L

#794 Update workflow.go
  backend/src/common/util/workflow.go
Labels: approved, lgtm, size/XS
