Repository kubeflow/kfp-tekton, pull requests merged in 2021-07, with the labels that each got.

#649 add mlx-reference
  README.md
Labels: approved, lgtm, size/XS

#648 Remove runid labels from pipelineloop's child pipelinerun
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/XS

#650 Fix the issue when loop/graph inside a graph
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/loop_in_recursion.py
  sdk/python/tests/compiler/testdata/loop_in_recursion.yaml
  sdk/python/tests/compiler/testdata/loop_in_recursion_noninlined.yaml
  sdk/python/tests/compiler/testdata/loop_in_recursion_pipelineloop_cr1.yaml
Labels: approved, lgtm, size/XL

#646 Fix: go tests for pipelineLoop controller.
  .github/workflows/kfp-tekton-unittests.yml
  samples/watson-train-serve/README.md
  tekton-catalog/pipeline-loops/Makefile
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/L

#636 feat(sdk): inline user defined custom tasks
  guides/advanced_user_guide.md
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/custom_task_ref.py
  sdk/python/tests/compiler/testdata/custom_task_ref.yaml
  sdk/python/tests/compiler/testdata/custom_task_ref_customtask_cr1.yaml
  sdk/python/tests/compiler/testdata/custom_task_spec.yaml
Labels: approved, lgtm, size/L

#654 Fix argo redirect link in the docs
  guides/kfp-user-guide/README.md
Labels: approved, lgtm, size/XS

#653 Enhance Any Sequencer to hanle cases that some tasks skipped
  frontend/src/lib/StaticGraphParser.ts
  frontend/src/lib/WorkflowParser.ts
  sdk/FEATURES.md
  sdk/python/kfp_tekton/tekton.py
  sdk/python/tests/compiler/testdata/any_sequencer.yaml
  sdk/python/tests/compiler/testdata/any_sequencer_noninlined.yaml
  tekton-catalog/any-sequencer/Dockerfile
  tekton-catalog/any-sequencer/Makefile
  tekton-catalog/any-sequencer/README.md
  tekton-catalog/any-sequencer/cmd/root.go
  tekton-catalog/any-sequencer/main.go
Labels: approved, lgtm, size/L

#657 fix(sdk): loop argument jsonified, not stringified
  sdk/python/kfp_tekton/compiler/compiler.py
Labels: approved, lgtm, size/XS

#655 Add Prashant(scrapcodes) to reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#631 Make default terminate API configurable to support graceful termination
  backend/src/apiserver/common/config.go
  backend/src/apiserver/common/const.go
  backend/src/apiserver/resource/resource_manager.go
  guides/kfp-admin-guide.md
  manifests/kustomize/base/pipeline/apiserver-deployment.yaml
  manifests/kustomize/base/pipeline/kfp-pipeline-config.yaml
Labels: approved, lgtm, size/M

#662 fix(sdk): sort params to fix flaky tests.
  sdk/python/kfp_tekton/compiler/compiler.py
Labels: approved, lgtm, size/XS

#663 fix(pipelineloop): restored pipelineloop conditions test.
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/M

#660 feat(sdk): Add pipelineloop validation for testdata yamls.
  Makefile
  sdk/python/tests/compiler/testdata/conditions_and_loops.py
  sdk/python/tests/compiler/testdata/conditions_and_loops.yaml
  sdk/python/tests/compiler/testdata/conditions_and_loops_noninlined.yaml
  sdk/python/tests/compiler/testdata/conditions_with_global_params.py
  sdk/python/tests/compiler/testdata/conditions_with_global_params.yaml
  sdk/python/tests/compiler/testdata/conditions_with_global_params_noninlined.yaml
  tekton-catalog/pipeline-loops/Makefile
  tekton-catalog/pipeline-loops/cmd/cli/main.go
Labels: approved, lgtm, size/L

#665 Fix the yaml dump issue of boolean value
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/conditions_and_loops.py
  sdk/python/tests/compiler/testdata/conditions_and_loops.yaml
  sdk/python/tests/compiler/testdata/conditions_and_loops_noninlined.yaml
  sdk/python/tests/compiler/testdata/conditions_with_global_params.py
  sdk/python/tests/compiler/testdata/conditions_with_global_params.yaml
  sdk/python/tests/compiler/testdata/conditions_with_global_params_noninlined.yaml
Labels: approved, lgtm, size/XXL

#658 Update loop instructions to use inline spec
  samples/nested-loops/README.md
Labels: approved, lgtm, size/XS

#669 fix(pipelineloop): sort params to fix flakiness in tests.
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/M

#667 Update sdk and release tags to 0.9.0
  Makefile
  VERSION
  guides/kfp_tekton_install.md
  install/v0.9.0/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/setup.py
  sdk/python/tests/README.md
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic_noninlined.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
  sdk/python/tests/compiler/testdata/volume_op_noninlined.yaml
  sdk/python/tests/compiler/testdata/volume_snapshot_op.yaml
  sdk/python/tests/compiler/testdata/volume_snapshot_op_noninlined.yaml
  tekton-catalog/kubectl-wrapper/deploy/kubectl-deploy.yaml
Labels: approved, lgtm, size/XXL

#671 Convert user custom task from containerOp to component yaml
  sdk/python/kfp_tekton/tekton.py
Labels: approved, lgtm, size/M

#674 Fix merging issue from #512
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/conditions_and_loops.yaml
  sdk/python/tests/compiler/testdata/long_pipeline_name.yaml
  sdk/python/tests/compiler/testdata/loop_in_recursion.yaml
  sdk/python/tests/compiler/testdata/loop_over_lightweight_output.yaml
  sdk/python/tests/compiler/testdata/loop_static.yaml
  sdk/python/tests/compiler/testdata/loop_static_with_parallelism.yaml
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
  sdk/python/tests/compiler/testdata/withitem_multi_nested.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
  sdk/python/tests/compiler/testdata/withparam_global.yaml
  sdk/python/tests/compiler/testdata/withparam_global_dict.yaml
  sdk/python/tests/compiler/testdata/withparam_output.yaml
  sdk/python/tests/compiler/testdata/withparam_output_dict.yaml
Labels: approved, lgtm, size/XL

#676 remove ContainerOp in some samples
  samples/flip-coin/condition.py
  samples/nested-pipeline/compose.py
  samples/trusted-ai/trusted-ai.py
Labels: approved, lgtm, size/L

#677 Convert loop and lightweight example to component yaml
  samples/lightweight-component/calc_pipeline.py
  samples/nested-loops/withitem_nested.py
Labels: approved, lgtm, size/L

#679 Add check for missing pod in cache
  frontend/src/pages/RunDetails.tsx
Labels: approved, lgtm, size/S

#681 Fix broken link
  samples/e2e-mnist/README.md
Labels: approved, lgtm, size/XS

#675 Change to use component to replace containerOp for any sequencer
  sdk/python/kfp_tekton/tekton.py
  sdk/python/tests/compiler/testdata/any_sequencer.py
  sdk/python/tests/compiler/testdata/any_sequencer.yaml
  sdk/python/tests/compiler/testdata/any_sequencer_noninlined.yaml
Labels: approved, lgtm, size/L

#680 Update custom task to work with v2 compiler
  samples/e2e-mnist/README.md
  samples/flip-coin-custom-task/condition.py
  samples/tekton-custom-task/tekton-custom-task.py
  sdk/python/kfp_tekton/tekton.py
Labels: approved, lgtm, size/M

#684 Update Argo link
  sdk/README.md
Labels: approved, lgtm, size/XS
