Repository kubeflow/kfp-tekton, pull requests merged in 2021-06, with the labels that each got.

#600 Fix and verify nested recursive workflow
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/recur_nested.py
  sdk/python/tests/compiler/testdata/recur_nested.yaml
  sdk/python/tests/compiler/testdata/recur_nested_pipelineloop_cr1.yaml
  sdk/python/tests/compiler/testdata/recur_nested_pipelineloop_cr2.yaml
Labels: approved, lgtm, size/XL

#604 Change status for successful from "Succeeded" to "Completed"
  tekton-catalog/any-sequencer/cmd/root.go
Labels: approved, lgtm, size/XS

#602 feat(pipelineloop) : Support latest tektoncd pipeline version.
  tekton-catalog/pipeline-loops/README.md
  tekton-catalog/pipeline-loops/cmd/webhook/main.go
  tekton-catalog/pipeline-loops/examples/loop-example-basic_taskspec.yaml
  tekton-catalog/pipeline-loops/examples/simplepipelineloop_taskspec.yaml
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/L

#613 [test] Add pipeline-loop flag
  .tekton/listener.yaml
  .tekton/pipeline.yaml
  scripts/deploy/iks/tekton-catalog/deploy-pipeline-loops-e2e.sh
Labels: approved, lgtm, size/S

#617 Upgrade Python SDK to kfp==1.6.3
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
  sdk/python/tests/README.md
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
  sdk/python/tests/compiler/testdata/volume_snapshot_op.yaml
  sdk/python/tests/test_kfp_samples.sh
Labels: approved, area/sdk, lgtm, python, size/L

#614 feat(pipelineLoop): Create a validation CLI for commonly used Tekton custom task CRDs
  tekton-catalog/pipeline-loops/Makefile
  tekton-catalog/pipeline-loops/README.md
  tekton-catalog/pipeline-loops/cmd/cli/main.go
Labels: approved, lgtm, size/L

#616 doc: Update README.md typos
  guides/kfp-user-guide/README.md
  sdk/README.md
Labels: approved, lgtm, size/XS

#622 fix(scripts): deploy-ibm-vpc.sh public gateway detection.
  scripts/deploy/iks/deploy-ibm-vpc.sh
Labels: approved, lgtm, size/XS

#626 Update tekton client and deployment to 0.25.0
  README.md
  backend/src/apiserver/resource/resource_manager.go
  backend/src/common/util/workflow.go
  frontend/src/lib/StatusUtils.ts
  frontend/src/pages/Status.tsx
  go.mod
  go.sum
  guides/developer_guide.md
  manifests/kustomize/third-party/tekton/README.md
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-dashboard/cluster-role-binding.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-dashboard/cluster-role.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-dashboard/crds.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-dashboard/deployment.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-dashboard/kustomization.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-dashboard/role-binding.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-dashboard/service-account.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-dashboard/service.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-dashboard/tekton-dashboard-release.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/cluster-role-binding.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/cluster-role.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/config-map.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/crds.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/deployment.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/horizontal-pod-autoscaler.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/kustomization.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/namespace.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/params.env
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/params.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/pod-security-policy.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/policy.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/role-binding.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/role.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/secret.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/service-account.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/service.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-config.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-release.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/webhook-configuration.yaml
  sdk/README.md
Labels: approved, lgtm, size/XXL

#628 Add original PipelineRun name
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/S

#629 Make kustomize patch backward compatible with v3.2
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-config.yaml
Labels: approved, lgtm, size/XS

#619 Migrate Travis tests to Github Actions
  .github/workflows/kfp-tekton-unittests.yml
  .travis.yml
  Makefile
  sdk/python/tests/test_kfp_samples.sh
Labels: approved, lgtm, size/L

#623 fix(pipelineLoop): Update to latest tekton release v0.25.0.
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_validation_test.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/S

#632 Update Github Action PR trigger
  .github/workflows/kfp-tekton-unittests.yml
Labels: approved, lgtm, size/XS

#641 Enhance Any Sequencer
  tekton-catalog/any-sequencer/cmd/root.go
Labels: approved, lgtm, size/M

#642 Support custom image for any Seq
  sdk/python/kfp_tekton/tekton.py
Labels: approved, lgtm, size/XS

#638 fix: PipelineLoop nested validation logic fixed.
  tekton-catalog/pipeline-loops/cmd/cli/main.go
  tekton-catalog/pipeline-loops/examples/pipelinespec-with-nested-loop-embedded.yaml
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/L

#635 Update manifests and standalone deployment to 0.9.0-rc0
  Makefile
  guides/kfp_tekton_install.md
  install/v0.9.0-rc0/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/env/kfp-template/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
Labels: approved, lgtm, size/XXL

#643 Add jinchihe in the OWNER list
  OWNERS
Labels: approved, lgtm, size/XS

#645 Add Gang Pu as approver
  OWNERS
Labels: approved, lgtm, size/XS
