Repository kubeflow/kfp-tekton, pull requests merged in 2021-05, with the labels that each got.

#574 fix(ui, backend) Add pipelineRun to cache to assist in finding artifact data
  backend/src/cache/server/mutation.go
  backend/src/cache/server/mutation_test.go
  backend/src/cache/server/watcher.go
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/RunDetails.tsx
Labels: approved, lgtm, size/M

#576 Add taskSpec check to account for custom tasks without a taskSpec
  frontend/src/lib/StaticGraphParser.ts
Labels: approved, lgtm, size/XS

#579 Sanitize Tekton result parameters when passing to custom task inputs
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/tekton_custom_task.log
  sdk/python/tests/compiler/testdata/tekton_custom_task.py
  sdk/python/tests/compiler/testdata/tekton_custom_task.yaml
Labels: approved, lgtm, size/M

#581 Add instructions on upgrade kfp-tekton multi-users and fix new multi-users permission
  guides/kfp_tekton_install.md
  manifests/kustomize/base/installs/multi-user/cache/cluster-role.yaml
Labels: approved, lgtm, size/S

#582 Fix /logs api and add tests
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
Labels: approved, lgtm, size/S

#583 Enhance Any Sequencer to support watching run
  tekton-catalog/any-sequencer/cmd/root.go
Labels: approved, lgtm, size/L

#586 [test] Add trusted-ai into e2e testing
  .tekton/listener.yaml
  .tekton/pipeline.yaml
  .tekton/task.yaml
  scripts/deploy/iks/e2e-test.sh
  scripts/deploy/iks/tekton-catalog/deploy-any-sequencer-e2e.sh
  scripts/deploy/iks/test-flip-coin.sh
  scripts/deploy/iks/test-trusted-ai.sh
Labels: approved, lgtm, size/L

#589 Add Parallelism support on backend.
  tekton-catalog/pipeline-loops/README.md
  tekton-catalog/pipeline-loops/examples/loop-example-with-parallelism.yaml
  tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_defaults.go
  tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go
  tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_validation.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/L

#592 Support parallelism feature on DSL side
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/loop_static_with_parallelism.py
  sdk/python/tests/compiler/testdata/loop_static_with_parallelism.yaml
  sdk/python/tests/compiler/testdata/loop_static_with_parallelism_pipelineloop_cr1.yaml
  tekton-catalog/pipeline-loops/.gitignore
Labels: approved, lgtm, size/L

#593 Add support to generate custom task with custom task cr
  scripts/check_diff.sh
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/custom_task_spec.py
  sdk/python/tests/compiler/testdata/custom_task_spec.yaml
  sdk/python/tests/compiler/testdata/custom_task_spec_customtask_cr1.yaml
  sdk/python/tests/e2e_test_config.yaml
Labels: approved, lgtm, size/L

#596 Permit pipeline-runner to operate on runs
  manifests/kustomize/base/pipeline/pipeline-runner-role.yaml
Labels: approved, lgtm, size/XS

#598 Support expose status for any sequencer(DSL side)
  sdk/python/kfp_tekton/tekton.py
  sdk/python/tests/compiler/testdata/any_sequencer.py
  sdk/python/tests/compiler/testdata/any_sequencer.yaml
Labels: approved, lgtm, size/M

#588 Add Custom Task Docs and Usage
  README.md
  guides/advanced_user_guide.md
  images/condition-dependency.png
Labels: approved, lgtm, size/L

#597 Support expose status for any sequencer(backend)
  sdk/FEATURES.md
  tekton-catalog/any-sequencer/cmd/root.go
  tekton-catalog/any-sequencer/go.sum
Labels: approved, lgtm, size/L
