Repository kubeflow/kfp-tekton, pull requests merged in 2022-03, with the labels that each got.

#861 feat(pipelineloop): Add caching configuration support through config-map.
  guides/release.md
  tekton-catalog/pipeline-loops/config/201-role.yaml
  tekton-catalog/pipeline-loops/config/204-cache-config.yaml
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/L

#866 Fix Tekton conditional dependency on sub-dag
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/loop_empty.yaml
  sdk/python/tests/compiler/testdata/loop_with_conditional_dependency.py
  sdk/python/tests/compiler/testdata/loop_with_conditional_dependency.yaml
  sdk/python/tests/compiler/testdata/loop_with_conditional_dependency_noninlined.yaml
Labels: approved, lgtm, size/XL

#854 Feat(pipelineloop): Break task as custom task.
  tekton-catalog/pipeline-loops/config/301-breaktask.yaml
  tekton-catalog/pipeline-loops/examples/break-task-example.yaml
  tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/controller.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/L

#868 Update kfp sdk dependency to 1.8.10+
  .github/workflows/kfp-tekton-unittests.yml
  .kfp-rebase-version
  README.md
  sdk/README.md
  sdk/python/README.md
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
  sdk/python/tests/README.md
  sdk/python/tests/compiler/testdata/any_sequencer.yaml
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/conditions_and_loops.yaml
  sdk/python/tests/compiler/testdata/conditions_and_loops_noninlined.yaml
  sdk/python/tests/compiler/testdata/conditions_with_global_params.yaml
  sdk/python/tests/compiler/testdata/data_passing_pipeline_complete.yaml
  sdk/python/tests/compiler/testdata/loop_with_params_in_json.yaml
  sdk/python/tests/compiler/testdata/many_results.yaml
  sdk/python/tests/compiler/testdata/many_results_with_warnings.yaml
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving_noninlined.yaml
  sdk/python/tests/test_kfp_samples.sh
Labels: approved, lgtm, size/L

#870 Add caching labels for inline loops and custom tasks
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/conditions_and_loops.yaml
  sdk/python/tests/compiler/testdata/long_pipeline_name.yaml
  sdk/python/tests/compiler/testdata/loop_empty.yaml
  sdk/python/tests/compiler/testdata/loop_in_recursion.yaml
  sdk/python/tests/compiler/testdata/loop_literal_separator.yaml
  sdk/python/tests/compiler/testdata/loop_over_lightweight_output.yaml
  sdk/python/tests/compiler/testdata/loop_static.yaml
  sdk/python/tests/compiler/testdata/loop_static_with_parallelism.yaml
  sdk/python/tests/compiler/testdata/loop_with_conditional_dependency.yaml
  sdk/python/tests/compiler/testdata/loop_with_numeric.yaml
  sdk/python/tests/compiler/testdata/loop_with_params_in_json.yaml
  sdk/python/tests/compiler/testdata/loop_with_step.yaml
  sdk/python/tests/compiler/testdata/nested_recur_runafter.yaml
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
  sdk/python/tests/compiler/testdata/recur_nested.yaml
  sdk/python/tests/compiler/testdata/recursion_while.yaml
  sdk/python/tests/compiler/testdata/tekton_loop_dsl.yaml
  sdk/python/tests/compiler/testdata/withitem_multi_nested.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
  sdk/python/tests/compiler/testdata/withparam_global.yaml
  sdk/python/tests/compiler/testdata/withparam_global_dict.yaml
  sdk/python/tests/compiler/testdata/withparam_output.yaml
  sdk/python/tests/compiler/testdata/withparam_output_dict.yaml
Labels: approved, lgtm, size/L

#872 Patch kfp 1.8.1 new config
  backend/api/python_http_client/README.md
  backend/api/python_http_client/kfp_server_api/__init__.py
  backend/api/python_http_client/kfp_server_api/api_client.py
  backend/api/python_http_client/kfp_server_api/configuration.py
  backend/api/python_http_client/setup.py
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/src/apiserver/common/config.go
  backend/src/apiserver/config/config.json
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/template/template.go
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
  manifests/gcp_marketplace/schema.yaml
  manifests/kustomize/base/cache-deployer/kustomization.yaml
  manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
  manifests/kustomize/base/metadata/base/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/base/pipeline/metadata-writer/kustomization.yaml
  manifests/kustomize/env/gcp/inverse-proxy/kustomization.yaml
Labels: approved, lgtm, size/M

#875 Add 1.2 release changes
  Makefile
  VERSION
  guides/kfp_tekton_install.md
  install/v1.2.0/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  sdk/README.md
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/setup.py
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
Labels: approved, lgtm, size/XXL

#876 feat(objectstore) Metadata object store
  tekton-catalog/objectstore/README.md
  tekton-catalog/objectstore/go.mod
  tekton-catalog/objectstore/pkg/writer/objectstore_writer.go
Labels: approved, lgtm, size/L

#881 fix(sdk) add test for custom-tasks with literals. Fixes #880
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/literal_params_test.py
  sdk/python/tests/compiler/testdata/literal_params_test.yaml
Labels: approved, lgtm, size/L

#883 fix(PipelineLoop): integer divide by zero
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/XS

#884 chore: Objectstore package refactoring.
  tekton-catalog/objectstore/README.md
  tekton-catalog/objectstore/pkg/writer/objectstore_writer.go
  tekton-catalog/objectstore/pkg/writer/objectstorelogger.go
  tekton-catalog/objectstorelogger/README.md
  tekton-catalog/objectstorelogger/go.mod
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go
Labels: approved, lgtm, size/L

#888 [test] Update mnist-e2e sample
  samples/e2e-mnist/README.md
  samples/e2e-mnist/e2e-mnist.py
  samples/e2e-mnist/mnist.ipynb
Labels: approved, lgtm, size/M

#887 fix: objectstore refactoring
  tekton-catalog/objectstore/pkg/writer/objectstorelogger.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go
Labels: approved, lgtm, size/S

#894 Add current iteration item to the PipelineLoopPipelineRunStatus
  tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/M

#893 Add yhwang as approver
  OWNERS
Labels: approved, lgtm, size/XS

#896 fix(sdk) add tests for non-literal separator
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/tekton.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/separator_from_param.py
  sdk/python/tests/compiler/testdata/separator_from_param.yaml
  sdk/python/tests/compiler/testdata/separator_from_param_noninlined.yaml
  sdk/python/tests/compiler/testdata/separator_from_task.py
  sdk/python/tests/compiler/testdata/separator_from_task.yaml
  sdk/python/tests/compiler/testdata/separator_from_task_noninlined.yaml
Labels: approved, lgtm, size/XL

#891 fix(controller): Added fields serviceAccountName and PodTemplate to PipelineLoop.
  tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/L

#897 Add missing openshift standalone permission
  manifests/kustomize/third-party/openshift/standalone/anyuid-scc.yaml
  manifests/kustomize/third-party/openshift/standalone/privileged-scc.yaml
Labels: approved, lgtm, size/XS

#899 Add missing csi plugin for multi-user manifests
  manifests/kustomize/env/plain-multi-user/kustomization.yaml
Labels: approved, lgtm, size/XS
