Repository kubeflow/kfp-tekton, pull requests merged in 2022-05, with the labels that each got.

#928 Fix multiple nested condition in loops issue
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/multi_nested_loop_condi.py
  sdk/python/tests/compiler/testdata/multi_nested_loop_condi.yaml
Labels: approved, lgtm, size/L

#929 Update sdk release to 1.2.1
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/setup.py
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
Labels: approved, lgtm, size/S

#920 feat(sdk): Add helper class AddOnGroup
  guides/advanced_user_guide.md
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/tekton.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/exception.py
  sdk/python/tests/compiler/testdata/exception.yaml
Labels: approved, lgtm, size/XL

#936 wait for pipelineloop-break-operation task final status
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/M

#937 [build] update toolchain image
  .tekton/task.yaml
Labels: approved, lgtm, size/S

#939 [build] update github workflow to use go v1.17
  .github/workflows/kfp-tekton-unittests.yml
  tekton-catalog/pipeline-loops/Makefile
Labels: approved, lgtm, size/S

#941 Loop ranges should handle from = to, and generate one iteration.
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelineloop_range_test.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/M

#944 iteration limit support, default limit is 10000
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/S

#946 fix: typo in frontend message
  frontend/src/lib/Buttons.ts
Labels: approved, lgtm, size/XS

#948 Update manifests with 1.2.1 release
  Makefile
  VERSION
  guides/kfp_tekton_install.md
  install/v1.2.1/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
Labels: approved, lgtm, size/XXL

#952 fix(sdk): Fix param prefix replacement
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/param_same_prefix.py
  sdk/python/tests/compiler/testdata/param_same_prefix.yaml
  sdk/python/tests/compiler/testdata/param_same_prefix_noninlined.yaml
Labels: approved, lgtm, size/XL

#949 feat(backend): update go version and license files
  backend/Dockerfile
  backend/Dockerfile.cacheserver
  backend/Dockerfile.persistenceagent
  backend/Dockerfile.scheduledworkflow
  backend/Dockerfile.viewercontroller
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  backend/third_party_licenses/viewer.csv
  hack/install-go-licenses.sh
Labels: approved, lgtm, size/XXL

#942 fix(backend): refine copy-artifacts step
  backend/src/apiserver/common/config.go
  backend/src/apiserver/common/const.go
  backend/src/apiserver/template/tekton_template.go
  manifests/kustomize/base/pipeline/kfp-pipeline-config.yaml
Labels: approved, lgtm, size/M

#956 feat(test): add backend integration test
  .github/workflows/kfp-tekton-unittests.yml
  backend/Dockerfile
  manifests/kustomize/env/platform-agnostic-kind/kustomization.yaml
  scripts/deploy/github/build-images.sh
  scripts/deploy/github/deploy-kfp.sh
  scripts/deploy/github/e2e-test.sh
Labels: approved, lgtm, size/L

#961 fix 954, trim whitespace and newline char for range input
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelineloop_range_test.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/L

#963 fix(pipeline-loops): PipelineLoop consumes significant amount of memory
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/S

#965 update install guide
  guides/kfp_tekton_install.md
Labels: approved, lgtm, size/XS
