Repository kubeflow/kfp-tekton, pull requests merged in 2022-02, with the labels that each got.

#842 fix(sdk) separator param. Part of #791
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/tests/compiler/testdata/loop_literal_separator.yaml
  sdk/python/tests/compiler/testdata/loop_literal_separator_noninlined.yaml
Labels: approved, lgtm, size/S

#838 Add loop numeric sdk support
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/tekton.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/loop_with_numeric.py
  sdk/python/tests/compiler/testdata/loop_with_numeric.yaml
  sdk/python/tests/compiler/testdata/loop_with_numeric_noninlined.yaml
  sdk/python/tests/compiler/testdata/loop_with_step.py
  sdk/python/tests/compiler/testdata/loop_with_step.yaml
  sdk/python/tests/compiler/testdata/loop_with_step_noninlined.yaml
Labels: approved, lgtm, size/XL

#846 Update manifests for multi-users k8s 1.22 support
  manifests/kustomize/base/cache-deployer/kustomization.yaml
  manifests/kustomize/third-party/application/cluster-scoped/application-crd.yaml
  manifests/kustomize/third-party/metacontroller/base/crd.yaml
Labels: approved, lgtm, size/XXL

#847 Add KFP-Tekton 1.1.1 release
  Makefile
  VERSION
  guides/kfp_tekton_install.md
  install/v1.1.1/kfp-tekton.yaml
  manifests/kustomize/base/cache-deployer/kustomization.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/installs/multi-user/scheduled-workflow/cluster-role.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-role.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  sdk/python/kfp_tekton/__init__.py
  sdk/python/setup.py
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
Labels: approved, lgtm, size/XXL

#852 feat: caching for custom task.
  tekton-catalog/cache/README.md
  tekton-catalog/cache/go.mod
  tekton-catalog/cache/pkg/db/db_conn_manager.go
  tekton-catalog/cache/pkg/db/mysql.go
  tekton-catalog/cache/pkg/db/sqlite.go
  tekton-catalog/cache/pkg/model/task_cache.go
  tekton-catalog/cache/pkg/task_cache_store.go
  tekton-catalog/cache/pkg/task_cache_store_test.go
  tekton-catalog/pipeline-loops/examples/loop-example-basic.yaml
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go
  tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/zz_generated.deepcopy.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/XL

#860 [test] fix typo in pipeline-loop example
  tekton-catalog/pipeline-loops/examples/loop-example-basic.yaml
Labels: approved, lgtm, size/XS

#864 fix(sdk) add test for empty loops
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/loop_empty.py
  sdk/python/tests/compiler/testdata/loop_empty.yaml
Labels: approved, lgtm, size/L
