Repository kubeflow/kfp-tekton, pull requests merged in 2022-01, with the labels that each got.

#807 feat(pipelineloop): Break operation for pipelineloop.
  .github/workflows/kfp-tekton-unittests.yml
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/S

#809 update pipelineloop operator to check break tasks with taskrun
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/S

#808 fix(pipelineloop): Nested call stack depth limit
  tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/L

#812 Chore: regenerate python tests
  sdk/python/tests/compiler/testdata/tekton_loop_dsl.yaml
  sdk/python/tests/compiler/testdata/tekton_loop_dsl_noninlined.yaml
Labels: approved, lgtm, size/M

#813 Update pipelineloop and manifests with k8s 1.22 API
  manifests/kustomize/base/installs/multi-user/api-service/cluster-role-binding.yaml
  manifests/kustomize/base/installs/multi-user/api-service/cluster-role.yaml
  manifests/kustomize/base/pipeline/cluster-scoped/scheduled-workflow-crd.yaml
  manifests/kustomize/base/pipeline/cluster-scoped/viewer-crd.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/201-rolebinding.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/202-clusterrolebinding.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/300-pipelineloop.yaml
  tekton-catalog/pipeline-loops/config/201-rolebinding.yaml
  tekton-catalog/pipeline-loops/config/202-clusterrolebinding.yaml
  tekton-catalog/pipeline-loops/config/300-pipelineloop.yaml
Labels: approved, lgtm, size/L

#815 Move postcss to version 8 and fix Tekton UI dependency chain
  frontend/.eslintrc.yaml
  frontend/Dockerfile
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/TestUtils.ts
  frontend/src/components/MinioArtifactPreview.tsx
  frontend/src/components/viewers/Tensorboard.test.tsx
  frontend/src/lib/CompareUtils.ts
  frontend/src/lib/RunUtils.ts
  frontend/src/lib/StaticGraphParser.test.ts
  frontend/src/lib/StatusUtils.ts
  frontend/src/lib/Utils.test.ts
  frontend/src/lib/Utils.tsx
  frontend/src/lib/WorkflowParser.test.ts
  frontend/src/lib/WorkflowParser.ts
  frontend/src/lib/v2/WorkflowUtils.ts
  frontend/src/mlmd/MlmdUtils.ts
  frontend/src/pages/Compare.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/third_party/mlmd/argo_template.ts
  frontend/src/third_party/mlmd/kubernetes.ts
  frontend/tailwind.config.js
  frontend/tsconfig.json
Labels: approved, lgtm, size/XXL

#810 Add option to produce pipelinerun taskspec as taskref
  manifests/kustomize/base/installs/multi-user/api-service/cluster-role.yaml
  manifests/kustomize/base/installs/multi-user/pipelines-ui/cluster-role.yaml
  manifests/kustomize/base/installs/multi-user/scheduled-workflow/cluster-role.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-role.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-role.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-ui-role.yaml
  manifests/kustomize/base/pipeline/pipeline-runner-role.yaml
  samples/flip-coin/condition-with-taskref.py
  sdk/python/kfp_tekton/compiler/compiler.py
Labels: approved, lgtm, size/L

#814 kfp-tekton 1.1 release
  Makefile
  README.md
  VERSION
  guides/developer_guide.md
  guides/kfp_tekton_install.md
  install/v1.1.0/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/env/kfp-template/scheduled-workflow-crd.yaml
  manifests/kustomize/env/kfp-template/viewer-crd.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/201-role.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/202-clusterrolebinding.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/203-object-store-config.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/500-webhook-configuration.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/kustomization.yaml
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/setup.py
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
  tekton-catalog/pipeline-loops/config/202-clusterrolebinding.yaml
  tekton-catalog/pipeline-loops/config/500-webhook-configuration.yaml
Labels: approved, lgtm, size/XXL

#824 fix(pipelineloop): break loop should cancel all pipeline runs.
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/M

#825 Enable pipelineparam for container env
  sdk/python/kfp_tekton/compiler/_k8s_helper.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/pipelineparam_env.py
  sdk/python/tests/compiler/testdata/pipelineparam_env.yaml
Labels: approved, lgtm, size/L

#827 Clean up owners file
  OWNERS
Labels: approved, lgtm, size/XS

#828 Additional param to enable running copies of same pipeline concurrently
  sdk/python/tests/perf_test_config.yaml
  sdk/python/tests/performance_tests.py
Labels: approved, lgtm, size/XS

#829 feat(objectstorelogger): objectstorelogger as a separate module.
  tekton-catalog/objectstorelogger/README.md
  tekton-catalog/objectstorelogger/go.mod
  tekton-catalog/objectstorelogger/pkg/objectstorelogger/objectstorelogger.go
  tekton-catalog/pipeline-loops/config/203-object-store-config.yaml
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/objectstore_logger.go
Labels: approved, lgtm, size/L

#837 feat(sdk): implement loop DSL ext: from_string. Part of #791
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/tekton.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/loop_literal_separator.py
  sdk/python/tests/compiler/testdata/loop_literal_separator.yaml
  sdk/python/tests/compiler/testdata/loop_literal_separator_noninlined.yaml
Labels: approved, lgtm, size/L

#836 Update KFP-Tekton installation to give guidance on GPU worker nodes.
  guides/kfp_tekton_install.md
Labels: approved, lgtm, size/XS

#841 Add support to parse pipeline param in json string
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/loop_literal_separator.yaml
  sdk/python/tests/compiler/testdata/loop_literal_separator_noninlined.yaml
  sdk/python/tests/compiler/testdata/loop_with_params_in_json.py
  sdk/python/tests/compiler/testdata/loop_with_params_in_json.yaml
  sdk/python/tests/test_kfp_samples_report.txt
Labels: approved, lgtm, size/XL
