Repository kubeflow/kfp-tekton, pull requests merged in 2022-10, with the labels that each got.

#1050 Update kfp-sdk to 1.8.14
  sdk/python/README.md
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
  sdk/python/tests/README.md
  sdk/python/tests/test_kfp_samples.sh
Labels: approved, lgtm, size/M

#1055 feature(backend): Add QPS and Burst settings
  install/v1.3.1/kfp-tekton.yaml
  manifests/kustomize/base/pipeline/apiserver-deployment.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/kustomization.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-controller.yaml
Labels: approved, lgtm, size/M

#1057 fix(manifests): Patch cache config and break ct to default pl deployment
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/204-cache-config.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/301-breaktask.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/kustomization.yaml
Labels: approved, lgtm, size/M

#1059 feat(sdk): add iterateParamPassStyle and itemPassStyle params to loop
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/tekton.py
  sdk/python/tests/compiler/testdata/loop_with_numeric.py
  sdk/python/tests/compiler/testdata/loop_with_numeric.yaml
  sdk/python/tests/compiler/testdata/loop_with_numeric_noninlined.yaml
Labels: approved, lgtm, size/M

#1056 fix(pipelineloop): caching should include the params for making caching key.
  tekton-catalog/cache/go.mod
  tekton-catalog/cache/pkg/db/db_conn_manager.go
  tekton-catalog/cache/pkg/db/mysql.go
  tekton-catalog/cache/pkg/db/sqlite.go
  tekton-catalog/cache/pkg/task_cache_store.go
  tekton-catalog/cache/pkg/task_cache_store_test.go
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelineloop_range_test.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/L

#1052 fix(sdk): update loop dsl to handle same argument in nested loop
  sdk/python/kfp_tekton/tekton.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/any_sequencer_looped.yaml
  sdk/python/tests/compiler/testdata/any_sequencer_looped_noninlined.yaml
  sdk/python/tests/compiler/testdata/loop_with_enumerate_basic.yaml
  sdk/python/tests/compiler/testdata/loop_with_enumerate_basic_noninlined.yaml
  sdk/python/tests/compiler/testdata/loop_with_enumerate_withitem_multi_nested.yaml
  sdk/python/tests/compiler/testdata/loop_with_enumerate_withitem_multi_nested_noninlined.yaml
  sdk/python/tests/compiler/testdata/multi_nested_loop_condi.yaml
  sdk/python/tests/compiler/testdata/nested_loop_same_arg.py
  sdk/python/tests/compiler/testdata/nested_loop_same_arg.yaml
  sdk/python/tests/compiler/testdata/nested_loop_same_arg_noninlined.yaml
  sdk/python/tests/compiler/testdata/param_same_prefix.yaml
  sdk/python/tests/compiler/testdata/param_same_prefix_noninlined.yaml
  sdk/python/tests/compiler/testdata/separator_from_param.yaml
  sdk/python/tests/compiler/testdata/separator_from_param_noninlined.yaml
  sdk/python/tests/compiler/testdata/separator_from_task.yaml
  sdk/python/tests/compiler/testdata/separator_from_task_noninlined.yaml
  sdk/python/tests/compiler/testdata/tekton_loop_dsl.yaml
  sdk/python/tests/compiler/testdata/tekton_loop_dsl_noninlined.yaml
Labels: approved, lgtm, size/XL

#1063 chore(release): add 1.4.0 release changes
  Makefile
  VERSION
  guides/kfp_tekton_install.md
  install/v1.4.0/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  sdk/README.md
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/setup.py
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
Labels: approved, lgtm, size/XXL

#1064 chore(OWNERS): Remove Animesh as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#1065 feat(backend): add new annotation flags to enable artifact tracking at pipeline and task level
  backend/src/apiserver/common/const.go
  backend/src/apiserver/template/tekton_template.go
  samples/lightweight-component/calc_pipeline.py
  sdk/FEATURES.md
Labels: approved, lgtm, size/M

#1067 chore(docs): Move loop to custom feature since it's not Tekton native
  sdk/FEATURES.md
Labels: approved, lgtm, size/M
