Repository kubeflow/kfp-tekton, pull requests merged in 2022-08, with the labels that each got.

#1025 Update tekton to 0.38.3 to resolve pipeline cancel issue with custom task
  README.md
  backend/src/apiserver/template/tekton_template.go
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  go.mod
  go.sum
  guides/kfp_tekton_install.md
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-dashboard/tekton-dashboard-release.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-release.yaml
  sdk/README.md
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
  tekton-catalog/pipeline-loops/test/controller.go
Labels: approved, lgtm, size/XL

#1026 Add test cases for sequence and cache
  .tekton/pipeline.yaml
  scripts/deploy/iks/expect-cache.json
  scripts/deploy/iks/expect-condition-depend.json
  scripts/deploy/iks/test-cache.sh
  scripts/deploy/iks/test-condition-depend.sh
  sdk/python/tests/verify_result.py
Labels: approved, lgtm, size/L

#1028 sdk(feat): add metadata support for loop
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/tekton.py
  sdk/python/tests/compiler/testdata/loop_with_step.py
  sdk/python/tests/compiler/testdata/loop_with_step_noninlined.yaml
Labels: approved, lgtm, size/M

#1029 optimize(sdk): Rewrite data passing script into more optimized code
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/tests/compiler/testdata/artifact_outputs.yaml
  sdk/python/tests/compiler/testdata/artifact_passing_using_volume.yaml
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/create_component_from_func.yaml
  sdk/python/tests/compiler/testdata/data_passing_pipeline_complete.yaml
  sdk/python/tests/compiler/testdata/many_results.yaml
  sdk/python/tests/compiler/testdata/many_results_with_warnings.yaml
Labels: approved, lgtm, size/L

#1032 feat(sdk): Add alpha env flag to opt out artifact tracking annotations
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, lgtm, size/M

#1033 Update kfp-tekton release to 1.3.1
  .kfp-rebase-version
  Makefile
  VERSION
  guides/kfp_tekton_install.md
  install/v1.3.1/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/setup.py
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
Labels: approved, lgtm, size/XXL

#1035 fix(sdk) include finally tasks in placeholder indir
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
Labels: approved, lgtm, size/S

#1036 Add finally context var test case for #1035
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/finally_context_var.py
  sdk/python/tests/compiler/testdata/finally_context_var.yaml
Labels: approved, lgtm, size/L

#1037 do not mark failed until all running PRs are done
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/S

#1040 fix(backend): add check for casting
  backend/src/cache/server/watcher.go
Labels: approved, lgtm, size/XS

#1042 Update tekton default timeout in global config
  guides/kfp_tekton_install.md
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/kustomization.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-default.yaml
Labels: approved, lgtm, size/S
