Repository kubeflow/kfp-tekton, pull requests merged in 2022-04, with the labels that each got.

#898 feat: New variable iterationNumberParam to track current item.
  tekton-catalog/pipeline-loops/examples/loop-example-numeric-param.yaml
  tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/L

#900 Parameterize kubelet path for s3-csi manifests
  install/v1.2.0/kfp-tekton.yaml
  manifests/kustomize/third-party/kfp-csi-s3/csi-s3-deployment.yaml
  manifests/kustomize/third-party/kfp-csi-s3/kustomization.yaml
  manifests/kustomize/third-party/kfp-csi-s3/params.yaml
Labels: approved, lgtm, size/M

#901 feat(sdk): extension function `Loop.enumerate()`
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/tekton.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/loop_with_enumerate_basic.py
  sdk/python/tests/compiler/testdata/loop_with_enumerate_basic.yaml
  sdk/python/tests/compiler/testdata/loop_with_enumerate_basic_noninlined.yaml
  sdk/python/tests/compiler/testdata/loop_with_enumerate_withitem_multi_nested.py
  sdk/python/tests/compiler/testdata/loop_with_enumerate_withitem_multi_nested.yaml
  sdk/python/tests/compiler/testdata/loop_with_enumerate_withitem_multi_nested_noninlined.yaml
  sdk/python/tests/compiler/testdata/loop_with_numeric_enumerate.py
  sdk/python/tests/compiler/testdata/loop_with_numeric_enumerate.yaml
  sdk/python/tests/compiler/testdata/loop_with_numeric_enumerate_noninlined.yaml
Labels: approved, lgtm, size/XXL

#904 IterateNumeric behavior changed to contain the value of current interation item.
  tekton-catalog/pipeline-loops/examples/pipelinespec-with-run-iterate-numeric.yaml
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/M

#905 Update Tekton client and manifests to v0.31.4
  README.md
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  go.mod
  go.sum
  guides/kfp_tekton_install.md
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-dashboard/tekton-dashboard-release.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-release.yaml
  sdk/README.md
Labels: approved, lgtm, size/XXL

#909 pass down the podTemplate and serviceAccount from run to loopSpec
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/L

#916 fix(sdk): handle the node selectors
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/node_selector_from_pipeline.py
  sdk/python/tests/compiler/testdata/node_selector_from_pipeline.yaml
  sdk/python/tests/compiler/testdata/node_selector_from_pipeline_override.py
  sdk/python/tests/compiler/testdata/node_selector_from_pipeline_override.yaml
Labels: approved, lgtm, size/L

#918 fix(sdk): Apply node_selector in PipelineConf
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/imagepullsecrets_with_node_selector.py
  sdk/python/tests/compiler/testdata/imagepullsecrets_with_node_selector.yaml
  sdk/python/tests/compiler/testdata/node_selector_from_pipeline.yaml
  sdk/python/tests/compiler/testdata/node_selector_from_pipeline_override.yaml
  tekton-catalog/pipeline-loops/Makefile
Labels: approved, lgtm, size/L

#911 feat: Support loop ranges with -ve values.
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelineloop_range_test.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/L

#921 Support the comma as default string param separator
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/M

#919 fix(SDK): Update sanitization logic to sync with kfp dsl
  sdk/python/kfp_tekton/compiler/_k8s_helper.py
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/custom_task_long_name.py
  sdk/python/tests/compiler/testdata/custom_task_long_name.yaml
Labels: approved, lgtm, size/L

#925 Add necessary env variables for resource op owner reference
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
Labels: approved, lgtm, size/M
