Repository kubeflow/kfp-tekton, pull requests merged in 2022-06, with the labels that each got.

#964 handle step from task results
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/XS

#970 fix(pipelineloop): Add param with empty space test
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/M

#973 fix(docs): Add explicit commands for Tekton versoned deployment to avoid doc con…
  guides/kfp_tekton_install.md
Labels: approved, lgtm, size/XS

#975 fix(sdk): update condition template
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/condition.yaml
  sdk/python/tests/compiler/testdata/condition_dependency.yaml
  sdk/python/tests/compiler/testdata/conditions_and_loops.yaml
  sdk/python/tests/compiler/testdata/conditions_and_loops_noninlined.yaml
  sdk/python/tests/compiler/testdata/conditions_with_global_params.yaml
  sdk/python/tests/compiler/testdata/loop_in_recursion.yaml
  sdk/python/tests/compiler/testdata/loop_in_recursion_noninlined.yaml
  sdk/python/tests/compiler/testdata/nested_recur_runafter.yaml
  sdk/python/tests/compiler/testdata/nested_recur_runafter_noninlined.yaml
  sdk/python/tests/compiler/testdata/recur_nested.yaml
  sdk/python/tests/compiler/testdata/recur_nested_noninlined.yaml
  sdk/python/tests/compiler/testdata/recursion_while.yaml
  sdk/python/tests/compiler/testdata/recursion_while_noninlined.yaml
Labels: approved, lgtm, size/L

#976 feature(backend): support embedded-status: minimal
  backend/src/agent/persistence/client/workflow_client.go
  backend/src/agent/persistence/main.go
  backend/src/agent/persistence/persistence_agent.go
  frontend/src/lib/WorkflowParser.ts
  guides/advanced_user_guide.md
  manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-role.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-config.yaml
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/L

#979 Update sdk dependency and release version to address private python package pull
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
Labels: approved, lgtm, size/M

#982 fix(backend): nil ptr exception for empty run status in pipeline-loops, fixes #981
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/XS

#967 feat(sdk): Add labels for artifact outputs when tasks are not referred
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/artifact_outputs.py
  sdk/python/tests/compiler/testdata/artifact_outputs.yaml
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/hidden_output_file.yaml
Labels: approved, lgtm, size/L
