Repository kubeflow/kfp-tekton, pull requests merged in 2022-07, with the labels that each got.

#985 fix(sdk): Verify binary data in step copy-results-artifacts. Fixes #984
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/tests/compiler/testdata/artifact_outputs.yaml
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/create_component_from_func.yaml
  sdk/python/tests/compiler/testdata/data_passing_pipeline_complete.yaml
  sdk/python/tests/compiler/testdata/many_results.yaml
  sdk/python/tests/compiler/testdata/many_results_with_warnings.yaml
Labels: approved, lgtm, size/M

#992 eliminate the use of `taskSpec.script`
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/tests/compiler/testdata/artifact_outputs.yaml
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/create_component_from_func.yaml
  sdk/python/tests/compiler/testdata/data_passing_pipeline_complete.yaml
  sdk/python/tests/compiler/testdata/data_passing_pipeline_param_as_file.yaml
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
  sdk/python/tests/compiler/testdata/many_results.yaml
  sdk/python/tests/compiler/testdata/many_results_with_warnings.yaml
  sdk/python/tests/compiler/testdata/nested_custom_conditions.yaml
Labels: approved, lgtm, size/L

#999 `chore(sdk) Bump kfp dependency to 1.8.13`
  sdk/python/requirements.txt
  sdk/python/setup.py
Labels: approved, lgtm, size/XS

#1002 Update sdk version to 1.2.3
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/setup.py
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
Labels: approved, lgtm, size/S

#995 sdk(feat): Add big data passing with custom volume on kfp-tekton
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/artifact_passing_using_volume.py
  sdk/python/tests/compiler/testdata/artifact_passing_using_volume.yaml
Labels: approved, lgtm, size/L

#977 chore(apiserver): Object Storage connection abstraction
  backend/src/apiserver/client/minio.go
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/common/config.go
  manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
  manifests/kustomize/base/pipeline/apiserver-deployment.yaml
  v2/objectstore/object_store.go
  v2/objectstore/object_store_test.go
Labels: approved, lgtm, size/L

#1005 Remove old build dependencies
  package-lock.json
  package.json
  requirements.txt
Labels: approved, lgtm, size/XXL

#997 fix(sdk): Support passing directories in step-copy-results-artifacts and step-copy-artifacts. Fixes #996
  manifests/kustomize/base/pipeline/kfp-pipeline-config.yaml
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/tests/compiler/testdata/artifact_outputs.yaml
  sdk/python/tests/compiler/testdata/artifact_passing_using_volume.yaml
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/create_component_from_func.yaml
  sdk/python/tests/compiler/testdata/data_passing_pipeline_complete.yaml
  sdk/python/tests/compiler/testdata/many_results.yaml
  sdk/python/tests/compiler/testdata/many_results_with_warnings.yaml
Labels: approved, lgtm, size/L

#1006 fix(sdk): Fix big data passing with multiple type of volume templates
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/big_data_multi_volumes_1.py
  sdk/python/tests/compiler/testdata/big_data_multi_volumes_1.yaml
  sdk/python/tests/compiler/testdata/big_data_multi_volumes_2.py
  sdk/python/tests/compiler/testdata/big_data_multi_volumes_2.yaml
Labels: approved, lgtm, size/XL

#993 Add alpha feature to output big data passing file path instead of task run name
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
Labels: approved, lgtm, size/M

#1013 Update result name to be case sensitive
  sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py
  sdk/python/kfp_tekton/compiler/_k8s_helper.py
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/tekton.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/any_sequencer.yaml
  sdk/python/tests/compiler/testdata/artifact_passing_using_volume.yaml
  sdk/python/tests/compiler/testdata/big_data_passing.yaml
  sdk/python/tests/compiler/testdata/conditions_and_loops.yaml
  sdk/python/tests/compiler/testdata/conditions_and_loops_noninlined.yaml
  sdk/python/tests/compiler/testdata/conditions_with_global_params.yaml
  sdk/python/tests/compiler/testdata/create_component_from_func.yaml
  sdk/python/tests/compiler/testdata/custom_task_long_name.yaml
  sdk/python/tests/compiler/testdata/custom_task_output.py
  sdk/python/tests/compiler/testdata/custom_task_output.yaml
  sdk/python/tests/compiler/testdata/data_passing_pipeline_complete.yaml
  sdk/python/tests/compiler/testdata/katib.yaml
  sdk/python/tests/compiler/testdata/loop_with_params_in_json.yaml
  sdk/python/tests/compiler/testdata/many_results.yaml
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving_noninlined.yaml
Labels: approved, lgtm, size/XL

#1015 fix(sdk): fix exit handler param with empty exit task
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/custom_task_exit.py
  sdk/python/tests/compiler/testdata/custom_task_exit.yaml
Labels: approved, lgtm, size/L

#1016 fix(sdk): Add new logic to cover new tekton runafter condition
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/condition_depend.py
  sdk/python/tests/compiler/testdata/condition_depend.yaml
  sdk/python/tests/compiler/testdata/loop_with_conditional_dependency.yaml
  sdk/python/tests/compiler/testdata/loop_with_conditional_dependency_noninlined.yaml
  sdk/python/tests/compiler/testdata/multi_nested_loop_condi.yaml
Labels: approved, lgtm, size/L

#1011 Add kfp-tekton 1.3.0 release template
  Makefile
  VERSION
  guides/kfp_tekton_install.md
  install/v1.3.0/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/setup.py
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
Labels: approved, lgtm, size/XXL

#1017 fix(sdk): fix unit test merging conflicts
  sdk/python/tests/compiler/testdata/condition_depend.yaml
Labels: approved, lgtm, size/XS

#1018 fix(backend): fix cache server output
  backend/src/cache/server/mutation.go
Labels: approved, lgtm, size/XS

#1019 Update s3 csi deployment
  manifests/kustomize/third-party/kfp-csi-s3/csi-s3-deployment.yaml
Labels: approved, lgtm, size/M
