Repository kubeflow/kfp-tekton, pull requests merged in 2022-11, with the labels that each got.

#1069 chore(CI): Update go version in CI to 1.19.x
  .github/workflows/kfp-tekton-unittests.yml
Labels: approved, lgtm, size/XS

#1071 update toolchain image
  .tekton/task.yaml
Labels: approved, lgtm, size/S

#1076 fix(sdk): fix nested loop underscore param
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/nested_loop_with_underscore.py
  sdk/python/tests/compiler/testdata/nested_loop_with_underscore.yaml
  sdk/python/tests/compiler/testdata/nested_loop_with_underscore_noninlined.yaml
Labels: approved, lgtm, size/L

#1077 fix(bug): fix underscore param by checking pipeline param instead of task param
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/tests/compiler/testdata/nested_loop_with_underscore.py
  sdk/python/tests/compiler/testdata/nested_loop_with_underscore.yaml
  sdk/python/tests/compiler/testdata/nested_loop_with_underscore_noninlined.yaml
Labels: approved, lgtm, size/M

#1078 fix(sdk): add default labels for caching
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
  sdk/python/tests/compiler/testdata/compose.yaml
Labels: approved, lgtm, size/S

#1072 chore(PipelineLoop): upgrade to tekton v0.41.0
  .github/workflows/kfp-tekton-unittests.yml
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/M

#1070 update tekton version to 0.41
  .github/workflows/kfp-tekton-unittests.yml
  README.md
  backend/Dockerfile
  backend/Dockerfile.cacheserver
  backend/Dockerfile.persistenceagent
  backend/Dockerfile.scheduledworkflow
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  go.mod
  go.sum
  guides/developer_guide.md
  manifests/kustomize/env/platform-agnostic-kind/kustomization.yaml
  manifests/kustomize/env/platform-agnostic-kind/plain-kind/kustomization.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-dashboard/tekton-dashboard-release.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-release.yaml
  sdk/README.md
Labels: approved, lgtm, size/XXL

#1080 fix(sdk): fix nested loop counter param bug
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/nested_loop_counter_param.py
  sdk/python/tests/compiler/testdata/nested_loop_counter_param.yaml
  sdk/python/tests/compiler/testdata/nested_loop_counter_param_noninlined.yaml
Labels: approved, lgtm, size/L

#1082 cheerypick(sdk): Fix counter param cherrypick (#1080)
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/nested_loop_counter_param.py
  sdk/python/tests/compiler/testdata/nested_loop_counter_param.yaml
  sdk/python/tests/compiler/testdata/nested_loop_counter_param_noninlined.yaml
Labels: approved, lgtm, size/L

#1087 fix(sdk): Fix inline spec for iterateParamPassStyle and itemPassStyle
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/tests/compiler/testdata/loop_with_numeric.yaml
  sdk/python/tests/compiler/testdata/loop_with_numeric_noninlined.yaml
Labels: approved, lgtm, size/M

#1088 chore(cherrypick): fix inline spec for new features
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/tests/compiler/testdata/loop_with_numeric.yaml
  sdk/python/tests/compiler/testdata/loop_with_numeric_noninlined.yaml
Labels: approved, lgtm, size/M

#1091 fix(sdk): fix nested param logic for pl
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/tests/compiler/testdata/loop_with_enumerate_withitem_multi_nested.yaml
  sdk/python/tests/compiler/testdata/loop_with_enumerate_withitem_multi_nested_noninlined.yaml
  sdk/python/tests/compiler/testdata/nested_loop_counter.yaml
  sdk/python/tests/compiler/testdata/nested_loop_counter_noninlined.yaml
  sdk/python/tests/compiler/testdata/nested_loop_global_param.yaml
  sdk/python/tests/compiler/testdata/nested_loop_global_param_noninlined.yaml
  sdk/python/tests/compiler/testdata/nested_loop_param.yaml
  sdk/python/tests/compiler/testdata/nested_loop_param_noninlined.yaml
  sdk/python/tests/compiler/testdata/nested_loop_same_arg.yaml
  sdk/python/tests/compiler/testdata/nested_loop_same_arg_noninlined.yaml
  sdk/python/tests/compiler/testdata/nested_loop_with_underscore.yaml
  sdk/python/tests/compiler/testdata/nested_loop_with_underscore_noninlined.yaml
  sdk/python/tests/compiler/testdata/withitem_multi_nested.yaml
  sdk/python/tests/compiler/testdata/withitem_multi_nested_noninlined.yaml
Labels: approved, lgtm, size/L

#1092 cherrypick(sdk): fix nested param logic for pl (#1091)
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/tests/compiler/testdata/loop_with_enumerate_withitem_multi_nested.yaml
  sdk/python/tests/compiler/testdata/loop_with_enumerate_withitem_multi_nested_noninlined.yaml
  sdk/python/tests/compiler/testdata/nested_loop_counter.yaml
  sdk/python/tests/compiler/testdata/nested_loop_counter_noninlined.yaml
  sdk/python/tests/compiler/testdata/nested_loop_global_param.yaml
  sdk/python/tests/compiler/testdata/nested_loop_global_param_noninlined.yaml
  sdk/python/tests/compiler/testdata/nested_loop_param.yaml
  sdk/python/tests/compiler/testdata/nested_loop_param_noninlined.yaml
  sdk/python/tests/compiler/testdata/nested_loop_same_arg.yaml
  sdk/python/tests/compiler/testdata/nested_loop_same_arg_noninlined.yaml
  sdk/python/tests/compiler/testdata/nested_loop_with_underscore.yaml
  sdk/python/tests/compiler/testdata/nested_loop_with_underscore_noninlined.yaml
  sdk/python/tests/compiler/testdata/withitem_multi_nested.yaml
  sdk/python/tests/compiler/testdata/withitem_multi_nested_noninlined.yaml
Labels: approved, lgtm, size/L
