Repository kubeflow/kfp-tekton, pull requests merged in 2023-10, with the labels that each got.

#1352 fix(manifest): update manifests for proper third party app role
  manifests/kustomize/env/plain-multi-user/kustomization.yaml
  manifests/kustomize/env/plain/kustomization.yaml
  manifests/kustomize/env/platform-agnostic-tekton-multi-user/kustomization.yaml
  manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml
Labels: approved, lgtm, size/M

#1353 (cherrypick): fix(manifest): update manifests for proper third party app role (#1352)
  manifests/kustomize/env/plain-multi-user/kustomization.yaml
  manifests/kustomize/env/plain/kustomization.yaml
  manifests/kustomize/env/platform-agnostic-tekton-multi-user/kustomization.yaml
  manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml
Labels: approved, lgtm, size/M

#1354 v2(images): update image tag to 2.0.1
  manifests/kustomize/env/platform-agnostic-tekton-multi-user/kustomization.yaml
  manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml
  manifests/kustomize/env/platform-openshift-pipelines/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
Labels: approved, lgtm, size/S

#1355 Update openshift manifests for kfp-tekton v2
  manifests/kustomize/env/platform-openshift-pipelines/kustomization.yaml
Labels: approved, size/XS

#1359 feat(backend): Parameterizing v2 Launcher Image. Resolves #1358
  backend/src/v2/compiler/tektoncompiler/container.go
  backend/src/v2/compiler/tektoncompiler/tekton.go
Labels: approved, lgtm, size/S

#1363 fix(manifests): Update istio-authorization-config.yaml
  manifests/kustomize/v1/base/installs/multi-user/istio-authorization-config.yaml
Labels: size/S

#1362 fix(manifests): Update istio-authorization-config.yaml for multi-user
  manifests/kustomize/base/installs/multi-user/istio-authorization-config.yaml
Labels: approved, lgtm, size/S

#1367 chore(docs): Update kfp_tekton_install.md with kfp-tekton v2 install instructions
  guides/kfp_tekton_install.md
Labels: approved, lgtm, size/M

#1368 chore(docs): Add SECURITY.md to tell supporting kfp-tekton version
  SECURITY.md
Labels: approved, lgtm, size/S

#1370 feat(tekton-catalog): Move v2 tekton-exithandler custom task to tekton catalog
  .github/workflows/kfp-tekton-unittests.yml
  .gitignore
  Makefile
  tekton-catalog/tekton-exithandler/Dockerfile.tekton-exithandler.controller
  tekton-catalog/tekton-exithandler/Dockerfile.tekton-exithandler.webhook
  tekton-catalog/tekton-exithandler/VERSION
  tekton-catalog/tekton-exithandler/cmd/controller/main.go
  tekton-catalog/tekton-exithandler/cmd/webhook/main.go
  tekton-catalog/tekton-exithandler/examples/simple-exithandler.yaml
  tekton-catalog/tekton-exithandler/go.mod
  tekton-catalog/tekton-exithandler/go.sum
  tekton-catalog/tekton-exithandler/pkg/apis/exithandler/register.go
  tekton-catalog/tekton-exithandler/pkg/apis/exithandler/v1alpha1/defaults.go
  tekton-catalog/tekton-exithandler/pkg/apis/exithandler/v1alpha1/doc.go
  tekton-catalog/tekton-exithandler/pkg/apis/exithandler/v1alpha1/register.go
  tekton-catalog/tekton-exithandler/pkg/apis/exithandler/v1alpha1/types.go
  tekton-catalog/tekton-exithandler/pkg/apis/exithandler/v1alpha1/validation.go
  tekton-catalog/tekton-exithandler/pkg/apis/exithandler/v1alpha1/zz_generated.deepcopy.go
  tekton-catalog/tekton-exithandler/pkg/client/clientset/versioned/clientset.go
  tekton-catalog/tekton-exithandler/pkg/client/clientset/versioned/doc.go
  tekton-catalog/tekton-exithandler/pkg/client/clientset/versioned/fake/clientset_generated.go
  tekton-catalog/tekton-exithandler/pkg/client/clientset/versioned/fake/doc.go
  tekton-catalog/tekton-exithandler/pkg/client/clientset/versioned/fake/register.go
  tekton-catalog/tekton-exithandler/pkg/client/clientset/versioned/scheme/doc.go
  tekton-catalog/tekton-exithandler/pkg/client/clientset/versioned/scheme/register.go
  tekton-catalog/tekton-exithandler/pkg/client/clientset/versioned/typed/exithandler/v1alpha1/doc.go
  tekton-catalog/tekton-exithandler/pkg/client/clientset/versioned/typed/exithandler/v1alpha1/exithandler.go
  tekton-catalog/tekton-exithandler/pkg/client/clientset/versioned/typed/exithandler/v1alpha1/exithandler_client.go
  tekton-catalog/tekton-exithandler/pkg/client/clientset/versioned/typed/exithandler/v1alpha1/fake/doc.go
  tekton-catalog/tekton-exithandler/pkg/client/clientset/versioned/typed/exithandler/v1alpha1/fake/fake_exithandler.go
  tekton-catalog/tekton-exithandler/pkg/client/clientset/versioned/typed/exithandler/v1alpha1/fake/fake_exithandler_client.go
  tekton-catalog/tekton-exithandler/pkg/client/clientset/versioned/typed/exithandler/v1alpha1/generated_expansion.go
  tekton-catalog/tekton-exithandler/pkg/client/informers/externalversions/exithandler/interface.go
  tekton-catalog/tekton-exithandler/pkg/client/informers/externalversions/exithandler/v1alpha1/exithandler.go
  tekton-catalog/tekton-exithandler/pkg/client/informers/externalversions/exithandler/v1alpha1/interface.go
  tekton-catalog/tekton-exithandler/pkg/client/informers/externalversions/factory.go
  tekton-catalog/tekton-exithandler/pkg/client/informers/externalversions/generic.go
  tekton-catalog/tekton-exithandler/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  tekton-catalog/tekton-exithandler/pkg/client/injection/client/client.go
  tekton-catalog/tekton-exithandler/pkg/client/injection/client/fake/fake.go
  tekton-catalog/tekton-exithandler/pkg/client/injection/informers/exithandler/v1alpha1/exithandler/exithandler.go
  tekton-catalog/tekton-exithandler/pkg/client/injection/informers/exithandler/v1alpha1/exithandler/fake/fake.go
  tekton-catalog/tekton-exithandler/pkg/client/injection/informers/exithandler/v1alpha1/exithandler/filtered/exithandler.go
  tekton-catalog/tekton-exithandler/pkg/client/injection/informers/exithandler/v1alpha1/exithandler/filtered/fake/fake.go
  tekton-catalog/tekton-exithandler/pkg/client/injection/informers/factory/factory.go
  tekton-catalog/tekton-exithandler/pkg/client/injection/informers/factory/fake/fake.go
  tekton-catalog/tekton-exithandler/pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  tekton-catalog/tekton-exithandler/pkg/client/injection/informers/factory/filtered/filtered_factory.go
  tekton-catalog/tekton-exithandler/pkg/client/listers/exithandler/v1alpha1/exithandler.go
  tekton-catalog/tekton-exithandler/pkg/client/listers/exithandler/v1alpha1/expansion_generated.go
  tekton-catalog/tekton-exithandler/pkg/reconciler/exithandler/controller.go
  tekton-catalog/tekton-exithandler/pkg/reconciler/exithandler/reconciler.go
Labels: approved, lgtm, size/XXL

#1371 chore(cleanup): remove old manifests and tools to reduce security checklist
  install/v0.4.0/kfp-tekton.yaml
  install/v0.5.0/kfp-tekton.yaml
  install/v0.6.0/kfp-tekton.yaml
  tools/bazel_builder/BUILD
  tools/bazel_builder/Dockerfile
  tools/bazel_builder/README.md
  tools/bazel_builder/bazelrc
  tools/benchmarks/pipeline_service_api.ipynb
  tools/benchmarks/run_service_api.ipynb
  tools/diagnose/kfp.sh
  tools/metadatastore-upgrade/README.md
  tools/metadatastore-upgrade/main.go
Labels: approved, lgtm, size/XXL

#1377 chore(deps): Fix golang.org/x/net vulnerability
  Makefile
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  go.mod
  go.sum
  tekton-catalog/tekton-exithandler/go.mod
  tekton-catalog/tekton-exithandler/go.sum
  tekton-catalog/tekton-kfptask/go.mod
  tekton-catalog/tekton-kfptask/go.sum
Labels: approved, lgtm, size/L

#1383 chore(github): Update github action deps
  .github/workflows/kfp-tekton-unittests.yml
Labels: approved, lgtm, size/M

#1382 fix(deps): Update to Tekton 0.50.2 to fix regression and security bugs
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  go.mod
  go.sum
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-release.yaml
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/tekton-exithandler/go.mod
  tekton-catalog/tekton-exithandler/go.sum
  tekton-catalog/tekton-kfptask/go.mod
  tekton-catalog/tekton-kfptask/go.sum
Labels: approved, lgtm, size/L

#1385 chore(release): Add kfp-tekton 1.8.1 release
  Makefile
  README.md
  VERSION
  guides/kfp_tekton_install.md
  install/v1.8.1/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  sdk/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/setup.py
Labels: approved, lgtm, size/XXL

#1386 feat(Tekton CI): add v2 ci image publish pipeline tasks
  .tekton/listener.yaml
  .tekton/pipeline.yaml
  .tekton/task.yaml
  scripts/deploy/iks/publish-image.sh
  tekton-catalog/pipeline-loops/VERSION
  tekton-catalog/tekton-exithandler/VERSION
  tekton-catalog/tekton-kfptask/VERSION
Labels: approved, lgtm, size/L

#1387 chore(docs): update manual release process and minor ci display name change
  .tekton/pipeline.yaml
  guides/release.md
  scripts/deploy/iks/publish-image.sh
Labels: approved, lgtm, size/S

#1389 fix(tekton-catalog): fix kfptask custom task
  tekton-catalog/tekton-kfptask/cmd/controller/main.go
  tekton-catalog/tekton-kfptask/cmd/webhook/main.go
  tekton-catalog/tekton-kfptask/go.mod
  tekton-catalog/tekton-kfptask/go.sum
Labels: approved, lgtm, size/S

#1378 feat(Tekton-compiler): Add env vars in kfp-driver to parametrize Object storage host and port
  backend/src/v2/compiler/tektoncompiler/container.go
  backend/src/v2/compiler/tektoncompiler/testdata/exit_handler.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/hello_world.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/loop_static.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/mnist_pipeline.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/nestedloop.yaml
Labels: approved, lgtm, size/L

#1391 feat(tekton-catalog): Move kfp-tekton v2 driver to master branch
  .tekton/listener.yaml
  .tekton/pipeline.yaml
  Makefile
  tekton-catalog/tekton-driver/Dockerfile.tektondriver
  tekton-catalog/tekton-driver/VERSION
  tekton-catalog/tekton-driver/cmd/controller/main.go
  tekton-catalog/tekton-driver/cmd/driver/main.go
  tekton-catalog/tekton-driver/go.mod
  tekton-catalog/tekton-driver/go.sum
  tekton-catalog/tekton-driver/pkg/controller/controller.go
  tekton-catalog/tekton-driver/pkg/controller/klog.patch
  tekton-catalog/tekton-driver/pkg/controller/run.go
Labels: approved, lgtm, size/XXL

#1393 chore(docs): Update main readme entrypoint
  README.md
Labels: approved, lgtm, size/XS

#1395 feat(backend): Add CA injection to step-copy-artifacts step. Fixes #1394.
  backend/src/apiserver/common/config.go
  backend/src/apiserver/template/tekton_template.go
Labels: approved, lgtm, size/M

#1397 chore(docs): Update kfp-tekton install versions
  guides/kfp_tekton_install.md
Labels: approved, lgtm, size/S

#1404 chore(deps): update golang grpc deps to 1.56.3
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  go.mod
  go.sum
  tekton-catalog/tekton-driver/go.mod
  tekton-catalog/tekton-driver/go.sum
  tekton-catalog/tekton-exithandler/go.mod
  tekton-catalog/tekton-exithandler/go.sum
  tekton-catalog/tekton-kfptask/go.mod
  tekton-catalog/tekton-kfptask/go.sum
Labels: approved, lgtm, size/M

#1405 fix(tekton-catalog): sync pipeline package to 2.0.3 release
  tekton-catalog/tekton-driver/VERSION
  tekton-catalog/tekton-driver/go.mod
  tekton-catalog/tekton-driver/go.sum
  tekton-catalog/tekton-exithandler/VERSION
  tekton-catalog/tekton-kfptask/VERSION
Labels: approved, lgtm, size/S

#1407 chore(CI/manifests): Update CI and move manifests to 2.0.3
  backend/src/v2/compiler/tektoncompiler/testdata/mnist_pipeline.yaml
  manifests/kustomize/env/platform-agnostic-tekton-multi-user/kustomization.yaml
  manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  scripts/deploy/github/build-images.sh
  scripts/deploy/github/manifests/kustomization.yaml
Labels: approved, lgtm, size/M

#1409 core(v2): cherry-pick changes from 2.0.2
  README.md
  backend/src/v2/compiler/tektoncompiler/container.go
  backend/src/v2/compiler/tektoncompiler/tekton.go
  backend/src/v2/compiler/tektoncompiler/testdata/exit_handler.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/hello_world.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/loop_static.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/mnist_pipeline.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/nestedloop.yaml
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  backend/third_party_licenses/tekton-driver.csv
  backend/third_party_licenses/tekton-exithandler-controller.csv
  backend/third_party_licenses/tekton-exithandler-webhook.csv
  backend/third_party_licenses/tekton-kfptask-controller.csv
  backend/third_party_licenses/tekton-kfptask-webhook.csv
  go.mod
  go.sum
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-role.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-role.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-role.yaml
  manifests/kustomize/env/plain/kustomization.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-release.yaml
  scripts/deploy/github/manifests/kustomization.yaml
Labels: approved, size/L
