Repository kubeflow/kfp-tekton, pull requests merged in 2023-08, with the labels that each got.

#1297 backend(chore): update backend to tekton 0.50
  README.md
  backend/src/agent/persistence/worker/persistence_worker.go
  backend/src/agent/persistence/worker/persistence_worker_test.go
  backend/src/cache/server/mutation.go
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  go.mod
  go.sum
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-dashboard/tekton-dashboard-release.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-release.yaml
Labels: approved, lgtm, size/XXL

#1309 feature(backend): Tekton v1 migration
  backend/src/agent/persistence/client/workflow_client.go
  backend/src/agent/persistence/persistence_agent.go
  backend/src/agent/persistence/worker/metrics_reporter_test.go
  backend/src/agent/persistence/worker/persistence_worker_test.go
  backend/src/agent/persistence/worker/workflow_saver_test.go
  backend/src/apiserver/archive/log_test.go
  backend/src/apiserver/client/tekton.go
  backend/src/apiserver/client/tekton_fake.go
  backend/src/apiserver/client/workflow_fake.go
  backend/src/apiserver/common/config.go
  backend/src/apiserver/resource/model_converter.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/pipeline_upload_server_test.go
  backend/src/apiserver/server/report_server.go
  backend/src/apiserver/server/report_server_test.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/server/test_util.go
  backend/src/apiserver/template/tekton_template.go
  backend/src/apiserver/template/template.go
  backend/src/cache/client/tekton.go
  backend/src/cache/client/tekton_fake.go
  backend/src/cache/server/mutation.go
  backend/src/cache/server/watcher.go
  backend/src/common/client/api_server/pipeline_client_fake.go
  backend/src/common/client/api_server/run_client.go
  backend/src/common/client/api_server/run_client_fake.go
  backend/src/common/util/formatter.go
  backend/src/common/util/formatter_test.go
  backend/src/common/util/template_util.go
  backend/src/common/util/workflow.go
  backend/src/common/util/workflow_test.go
  backend/src/crd/controller/scheduledworkflow/client/workflow_client.go
  backend/src/crd/controller/scheduledworkflow/client/workflow_client_test.go
  backend/src/crd/controller/scheduledworkflow/controller.go
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow.go
  backend/src/crd/pkg/apis/scheduledworkflow/v1beta1/types.go
  scripts/deploy/github/build-images.sh
  sdk/python/tests/compiler/compiler_tests_e2e.py
Labels: approved, lgtm, size/L

#1312 feature(pipelineloop): Tekton v1 migration pipelineloop
  tekton-catalog/pipeline-loops/cmd/cli/main.go
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go
  tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_validation_test.go
  tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/zz_generated.deepcopy.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelineloop_range_test.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
  tekton-catalog/pipeline-loops/test/controller.go
Labels: approved, lgtm, size/XL

#1314 v2(backend): fix persistence agent
  backend/src/agent/persistence/client/pipeline_client.go
  backend/src/agent/persistence/worker/swf_saver.go
  backend/src/apiserver/main.go
Labels: approved, lgtm, size/S

#1315 v2(backend): fix scheduledworkflow
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/template/template_test.go
  backend/src/apiserver/template/v2_template.go
  backend/src/crd/controller/scheduledworkflow/controller.go
  backend/src/crd/controller/scheduledworkflow/main.go
  backend/src/crd/pkg/apis/scheduledworkflow/v1beta1/types.go
  scripts/deploy/github/manifests/kustomization.yaml
Labels: approved, lgtm, size/L

#1319 cherrypick task image into 1.5.x branch
  guides/advanced_user_guide.md
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/compiler/pipeline_utils.py
  sdk/python/setup.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/condition.yaml
  sdk/python/tests/compiler/testdata/condition_depend.yaml
  sdk/python/tests/compiler/testdata/conditions_and_loops.yaml
  sdk/python/tests/compiler/testdata/conditions_and_loops_noninlined.yaml
  sdk/python/tests/compiler/testdata/conditions_with_global_params.yaml
  sdk/python/tests/compiler/testdata/loop_in_recursion.yaml
  sdk/python/tests/compiler/testdata/loop_in_recursion_noninlined.yaml
  sdk/python/tests/compiler/testdata/nested_recur_runafter.yaml
  sdk/python/tests/compiler/testdata/nested_recur_runafter_noninlined.yaml
  sdk/python/tests/compiler/testdata/recur_nested.yaml
  sdk/python/tests/compiler/testdata/recur_nested_noninlined.yaml
  sdk/python/tests/compiler/testdata/recursion_while.yaml
  sdk/python/tests/compiler/testdata/recursion_while_noninlined.yaml
Labels: approved, size/L

#1318 v2(backend): fix multi-user issue in swf
  backend/src/crd/controller/scheduledworkflow/client/kube_client.go
  backend/src/crd/controller/scheduledworkflow/controller.go
  manifests/kustomize/base/installs/multi-user/scheduled-workflow/cluster-role.yaml
  manifests/kustomize/base/installs/multi-user/scheduled-workflow/deployment-patch.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-role.yaml
Labels: approved, lgtm, size/M

#1322 update OWNERS files
  OWNERS
  backend/OWNERS
  manifests/kustomize/OWNERS
Labels: approved, lgtm, size/M

#1324 feature(backend): update backend to be backward compatible with old status
  backend/src/agent/persistence/client/workflow_client.go
  backend/src/common/util/workflow.go
Labels: approved, lgtm, size/M

#1325 chore(docs): Update dead links and v2 information
  README.md
Labels: approved, lgtm, size/XS

#1327 feat(sdk): add tekton pipeline config into sdk client function
  sdk/python/kfp_tekton/_client.py
Labels: approved, lgtm, size/XS

#1328 chore(build): Update .readthedocs.yml to build.os format to avoid warning.
  .readthedocs.yml
Labels: approved, lgtm, size/XS

#1329 chore(test): update ci script
  .tekton/listener.yaml
  .tekton/pipeline.yaml
  .tekton/task.yaml
  scripts/deploy/iks/test-many-edges.sh
  tekton-catalog/pipeline-loops/examples/break-task-example.yaml
  tekton-catalog/pipeline-loops/examples/loop-example-basic-retry.yaml
  tekton-catalog/pipeline-loops/examples/loop-example-basic.yaml
  tekton-catalog/pipeline-loops/examples/loop-example-basic_taskspec.yaml
  tekton-catalog/pipeline-loops/examples/loop-example-numeric-param.yaml
  tekton-catalog/pipeline-loops/examples/loop-example-with-parallelism.yaml
  tekton-catalog/pipeline-loops/examples/loop-example-workspaces.yaml
  tekton-catalog/pipeline-loops/examples/pipelinespec-with-nested-loop-embedded.yaml
  tekton-catalog/pipeline-loops/examples/pipelinespec-with-nested-loop.yaml
  tekton-catalog/pipeline-loops/examples/simplepipelineloop.yaml
  tekton-catalog/pipeline-loops/examples/simplepipelineloop_taskspec.yaml
Labels: approved, lgtm, size/M

#1330 fix(pipelineloop): update pipelineloop v1 bug
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/XS

#1331 chore(release): kfp-tekton 1.8 release patch and tekton 0.50.1 patch
  Makefile
  README.md
  VERSION
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  go.mod
  go.sum
  guides/kfp_tekton_install.md
  install/v1.8.0/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-release.yaml
  sdk/README.md
  sdk/python/README.md
  tekton-catalog/pipeline-loops/go.mod
Labels: approved, lgtm, size/XXL

#1259 feat(backend): Source ObjStore Creds from Env in Tekton Template
  backend/src/apiserver/common/config.go
  backend/src/apiserver/common/const.go
  backend/src/apiserver/template/tekton_template.go
Labels: approved, lgtm, size/M

#1333 chore(cleanup): clean up visualization repo to reduce false positive scan
  backend/Dockerfile.visualization
  backend/Makefile
  backend/src/apiserver/visualization/.gitignore
  backend/src/apiserver/visualization/README.md
  backend/src/apiserver/visualization/exporter.py
  backend/src/apiserver/visualization/requirements-test.txt
  backend/src/apiserver/visualization/requirements.in
  backend/src/apiserver/visualization/requirements.txt
  backend/src/apiserver/visualization/server.py
  backend/src/apiserver/visualization/snapshots/snap_test_exporter.py
  backend/src/apiserver/visualization/templates/basic.tpl
  backend/src/apiserver/visualization/templates/full.tpl
  backend/src/apiserver/visualization/test_exporter.py
  backend/src/apiserver/visualization/test_server.py
  backend/src/apiserver/visualization/types/roc_curve.py
  backend/src/apiserver/visualization/types/table.py
  backend/src/apiserver/visualization/types/test.py
  backend/src/apiserver/visualization/types/tfdv.py
  backend/src/apiserver/visualization/types/tfma.py
  backend/src/apiserver/visualization/update_requirements.sh
  guides/developer_guide.md
Labels: approved, lgtm, size/XXL

#1334 feat(sdk): add bash script name config
  guides/advanced_user_guide.md
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/compiler/pipeline_utils.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/nested_custom_conditions.yaml
Labels: approved, lgtm, size/M

#1340 fix(sdk): update pyyaml dependencies
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
Labels: approved, lgtm, size/S

#1336 feat(sdk): update new image config via env variables
  sdk/README.md
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
Labels: approved, lgtm, size/S
