Repository kubeflow/kfp-tekton, pull requests merged in 2023-03, with the labels that each got.

#1175 chore(manifests): upgrade mysql image to kfp v2 standards for cves mitigation
  manifests/kustomize/third-party/mysql/base/mysql-deployment.yaml
Labels: approved, lgtm, size/M

#1178 chore(cleanup): Remove unnecessary cloud build files from google and travis
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  .travis.yml
Labels: approved, lgtm, size/XXL

#1177 feat(sdk): make metadata component spec gen flag configurable on pipeline level
  guides/advanced_user_guide.md
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/compiler/pipeline_utils.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/pipelineparam_env.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/tekton_pipeline_conf.py
  sdk/python/tests/compiler/testdata/tekton_pipeline_conf.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
Labels: approved, lgtm, size/M

#1179 fix(sdk): fix v1 api sdk client package bug
  sdk/python/kfp_tekton/_client.py
Labels: approved, lgtm, size/S

#1180 fix(sdk): fix v1 api package typo
  sdk/python/kfp_tekton/_client.py
Labels: approved, lgtm, size/XS

#1182 chore(release): Add sdk 1.5.2 patch
  sdk/python/kfp_tekton/__init__.py
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
Labels: approved, lgtm, size/S

#1184 chore(release): Add 1.6.2 backend release, 1.6.3 sdk release
  Makefile
  VERSION
  guides/kfp_tekton_install.md
  install/v1.6.2/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/500-controller.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/500-webhook.yaml
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/setup.py
Labels: approved, lgtm, size/XXL

#1187 chore(docs): Update docs on custom task parameters
  guides/advanced_user_guide.md
Labels: approved, lgtm, size/XS

#1186 fix(sdk): Update aipipeline images to quay
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/tekton.py
  sdk/python/tests/compiler/testdata/any_sequencer.yaml
  sdk/python/tests/compiler/testdata/any_sequencer_looped.yaml
  sdk/python/tests/compiler/testdata/any_sequencer_looped_noninlined.yaml
  sdk/python/tests/compiler/testdata/finally_context_var.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
Labels: approved, lgtm, size/M

#1189 fix(test): update toolchain image/script
  .tekton/listener.yaml
  .tekton/pipeline.yaml
  .tekton/task.yaml
  .tekton/tekton-catalog/tasks.yaml
  scripts/deploy/iks/deploy-kfp.sh
  scripts/deploy/iks/publish-image.sh
  scripts/deploy/iks/tekton-catalog/deploy-any-sequencer-e2e.sh
Labels: approved, lgtm, size/L

#1188 chore(tekton-catalog): Remove legacy v1alpha1 condtion since it is no longer supported
  tekton-catalog/condition/README.md
  tekton-catalog/condition/condition.yaml
Labels: approved, lgtm, size/M

#1190 fix(test): fix typo in the toolchain task
  .tekton/task.yaml
Labels: approved, lgtm, size/XS

#1194 feat(manifests): use kustomize v5
  guides/release.md
  manifests/kustomize/base/cache-deployer/kustomization.yaml
  manifests/kustomize/base/installs/generic/kustomization.yaml
  manifests/kustomize/base/installs/multi-user/kustomization.yaml
  manifests/kustomize/base/metadata/overlays/db/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/env/kfp-template/kustomization.yaml
  manifests/kustomize/env/plain-multi-user/kustomization.yaml
  manifests/kustomize/env/plain/kustomization.yaml
  manifests/kustomize/env/platform-agnostic-emissary/kustomization.yaml
  manifests/kustomize/env/platform-agnostic-kind/kustomization.yaml
  manifests/kustomize/env/platform-agnostic-kind/plain-kind/kustomization.yaml
  manifests/kustomize/env/platform-agnostic-multi-user-emissary/kustomization.yaml
  manifests/kustomize/env/platform-agnostic-multi-user/kustomization.yaml
  manifests/kustomize/env/platform-agnostic/kustomization.yaml
  manifests/kustomize/third-party/kfp-csi-s3/csi-s3-deployment.yaml
  manifests/kustomize/third-party/kfp-csi-s3/kustomization.yaml
  manifests/kustomize/third-party/kfp-csi-s3/params.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  manifests/kustomize/third-party/tekton/base/kustomization.yaml
  manifests/kustomize/third-party/tekton/installs/cluster/kustomization.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/kustomization.yaml
Labels: approved, lgtm, size/L

#1193 fix(backend): Fix metadata writer dependencies
  backend/metadata_writer/Dockerfile
  backend/metadata_writer/requirements.in
  backend/metadata_writer/requirements.txt
  backend/metadata_writer/src/metadata_helpers.py
  backend/metadata_writer/src/metadata_writer.py
Labels: approved, lgtm, size/M

#1196 chore(release): Add 1.6.3 backend and 1.6.4 sdk release
  Makefile
  VERSION
  guides/kfp_tekton_install.md
  install/v1.6.3/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/setup.py
Labels: approved, lgtm, size/XXL

#1198 fix(sdk): Remove print statement for compiler to reduce log size
  sdk/python/kfp_tekton/compiler/main.py
Labels: approved, lgtm, size/XS
