Repository kubeflow/kfp-tekton, pull requests merged in 2023-06, with the labels that each got.

#1252 v2(tekton compiler): add env vars for caching
  backend/src/v2/compiler/tektoncompiler/container.go
  manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml
  manifests/kustomize/env/platform-openshift-pipelines/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
Labels: size/L

#1253 Fix(backend): Upgrade Tekton 0.47.1 to address timeout bug
  README.md
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  go.mod
  go.sum
  guides/kfp_tekton_install.md
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-release.yaml
  sdk/README.md
  tekton-catalog/pipeline-loops/go.mod
Labels: approved, lgtm, size/L

#1254 fix(test): update docker image for dind
  .tekton/task.yaml
Labels: approved, lgtm, size/XS

#1256 Upload huggingface demo for tutorial
  samples/huggingface-prompt-tuning/prompt-tuning-demo.py
Labels: approved, lgtm, size/L

#1257 samples(fix): update lightweight component sample
  samples/lightweight-component/calc_pipeline.py
  samples/lightweight-component/lightweight_component.ipynb
Labels: approved, lgtm, size/M

#1258 feat(samples): add peft sample with modelmesh
  samples/peft-modelmesh-pipeline/Dockerfile
  samples/peft-modelmesh-pipeline/inferenceservice.yaml
  samples/peft-modelmesh-pipeline/input.json
  samples/peft-modelmesh-pipeline/peft_model_server.py
  samples/peft-modelmesh-pipeline/prompt-tuning-pipeline.py
  samples/peft-modelmesh-pipeline/prompt-tuning-serving.py
  samples/peft-modelmesh-pipeline/servingruntime.yaml
Labels: approved, lgtm, size/XL

#1261 feat(v2 backend): support loop parallelism
  backend/src/v2/compiler/tektoncompiler/dag.go
  backend/src/v2/compiler/tektoncompiler/testdata/nestedloop_ir.yaml
Labels: size/XS

#1262 v2: update apiserver image
  manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml
  manifests/kustomize/env/platform-openshift-pipelines/kustomization.yaml
Labels: size/XS

#1263 fix(fronted): Fix Tensorboard.tsx endpoint
  frontend/src/components/viewers/Tensorboard.tsx
Labels: approved, lgtm, size/XS

#1265 feat(sdk): Parametrize Tekton condition "task" image name
  guides/advanced_user_guide.md
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/compiler/pipeline_utils.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/condition.yaml
  sdk/python/tests/compiler/testdata/condition_depend.yaml
  sdk/python/tests/compiler/testdata/conditions_and_loops.yaml
  sdk/python/tests/compiler/testdata/conditions_and_loops_noninlined.yaml
  sdk/python/tests/compiler/testdata/conditions_with_global_params.yaml
  sdk/python/tests/compiler/testdata/loop_in_recursion.yaml
  sdk/python/tests/compiler/testdata/loop_in_recursion_noninlined.yaml
  sdk/python/tests/compiler/testdata/nested_recur_runafter.yaml
  sdk/python/tests/compiler/testdata/nested_recur_runafter_noninlined.yaml
  sdk/python/tests/compiler/testdata/recur_nested.yaml
  sdk/python/tests/compiler/testdata/recur_nested_noninlined.yaml
  sdk/python/tests/compiler/testdata/recursion_while.yaml
  sdk/python/tests/compiler/testdata/recursion_while_noninlined.yaml
Labels: approved, lgtm, size/L

#1267 chore(sdk): Add sdk 1.7.1 release
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/setup.py
Labels: approved, lgtm, size/S

#1268 fix(v2 backend): progagate MLMD host/port to the driver
  backend/src/v2/compiler/tektoncompiler/container.go
  backend/src/v2/compiler/tektoncompiler/dag.go
  backend/src/v2/compiler/tektoncompiler/tekton.go
  backend/src/v2/compiler/tektoncompiler/testdata/exit_handler.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/mnist_pipeline.yaml
  manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml
  manifests/kustomize/env/platform-openshift-pipelines/kustomization.yaml
Labels: size/XXL

#1269 test(v2): add test case for tekton compiler
  backend/src/v2/compiler/tektoncompiler/tekton_test.go
  backend/src/v2/compiler/tektoncompiler/testdata/loop_static.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/nestedloop.yaml
Labels: size/XXL

#1270 test(v2): fix failed test cases
  backend/src/apiserver/client/argo_fake.go
  backend/src/common/util/execution_spec_test.go
  backend/src/v2/compiler/tektoncompiler/tekton_test.go
  backend/src/v2/compiler/tektoncompiler/testdata/hello_world.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/importer.yaml
  backend/src/v2/component/launcher_v2_test.go
  backend/src/v2/expression/expression_test.go
  backend/src/v2/objectstore/object_store.go
Labels: size/L
