Repository kubeflow/kfp-tekton, pull requests merged in 2023-07, with the labels that each got.

#1274 test(v2): enable ghaction for v2 branch
  .github/workflows/backend.yml
  .github/workflows/codeql.yml
  .github/workflows/pipelineloop.yml
  tekton-catalog/pipeline-loops/test/controller.go
Labels: size/L

#1276 v2: remote metadata-writer
  manifests/kustomize/base/pipeline/kustomization.yaml
Labels: size/XS

#1278 chore(docs): Update kfp-tekton openshift instructions for openshift v1.11
  guides/kfp_tekton_install.md
Labels: approved, lgtm, size/S

#1275 test(v2): add end-2-end test
  .github/workflows/backend.yml
  scripts/deploy/github/build-images.sh
  scripts/deploy/github/deploy-kfp.sh
  scripts/deploy/github/e2e-test.sh
  scripts/deploy/github/helper-functions.sh
  scripts/deploy/github/manifests/kustomization.yaml
  scripts/deploy/github/test-flip-coin.sh
Labels: size/XL

#1282 feat(v2:backend): update tekton version
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  backend/third_party_licenses/tekton-driver.csv
  backend/third_party_licenses/tekton-exithandler-controller.csv
  backend/third_party_licenses/tekton-exithandler-webhook.csv
  backend/third_party_licenses/tekton-kfptask-controller.csv
  backend/third_party_licenses/tekton-kfptask-webhook.csv
  go.mod
  go.sum
  manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml
  manifests/kustomize/env/platform-openshift-pipelines/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/configmap.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-release.yaml
Labels: approved, lgtm, size/L

#1287 fix(v2:backend): fix importer
  backend/src/v2/compiler/tektoncompiler/importer.go
  backend/src/v2/compiler/tektoncompiler/testdata/importer.yaml
Labels: approved, lgtm, size/M

#1288 feat(v2:backend): update api-server image
  manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml
  manifests/kustomize/env/platform-openshift-pipelines/kustomization.yaml
Labels: approved, lgtm, size/XS

#1289 test(v2): add dynamic loop test case
  .github/workflows/backend.yml
  scripts/deploy/github/test-dynamic-loop.sh
Labels: approved, lgtm, size/M

#1295 chore(release): add 1.7.1 backend release
  Makefile
  VERSION
  guides/kfp_tekton_install.md
  install/v1.7.1/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
Labels: approved, lgtm, size/XXL

#1300 fix(ci): fix end to end github action test
  scripts/deploy/github/build-images.sh
Labels: approved, lgtm, size/XS

#1302 test(v2): secret as volume
  .github/workflows/backend.yml
  scripts/deploy/github/test-secret-as-volume.sh
Labels: approved, lgtm, size/M

#1304 chore(samples): Add readme for prompt tuning samples
  samples/README.md
  samples/huggingface-prompt-tuning/README.md
  samples/peft-modelmesh-pipeline/README.md
Labels: approved, lgtm, size/XS

#1305 chore(readme): Add kfp-tekton v2 branch link
  README.md
Labels: approved, lgtm, size/XS

#1303 test(v2): add env test case
  .github/workflows/backend.yml
  scripts/deploy/github/test-env.sh
Labels: approved, lgtm, size/M

#1306 test(v2): use volume
  .github/workflows/backend.yml
  manifests/kustomize/third-party/tekton-custom-task/driver-controller/201-clusterrole.yaml
  scripts/deploy/github/test-volume.sh
Labels: approved, lgtm, size/M

#1307 fix(deployment): Update image name and version for pipelineloop controllers
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/500-controller.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/500-webhook.yaml
Labels: approved, lgtm, size/XS
