Repository kubeflow/kfp-tekton, pull requests merged in 2023-04, with the labels that each got.

#1200 fix(test): enhance build scripts
  .tekton/pipeline.yaml
  scripts/deploy/iks/expect-condition-depend.json
  scripts/deploy/iks/helper-functions.sh
  scripts/deploy/iks/test-cache.sh
  scripts/deploy/iks/test-condition-depend.sh
  scripts/deploy/iks/test-flip-coin.sh
  scripts/deploy/iks/test-many-edges.sh
Labels: approved, lgtm, size/M

#1201 feat(CI): Create periodic codeql code scan to detect possible static bugs
  .github/workflows/codeql.yml
Labels: approved, lgtm, size/M

#1202 fix(deps): Tekton 0.44.2 patch and dependencies update
  backend/src/apiserver/client/minio.go
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/storage/minio_client.go
  backend/src/apiserver/storage/minio_client_fake.go
  backend/src/apiserver/storage/object_store.go
  backend/src/apiserver/storage/object_store_test.go
  backend/src/apiserver/template/tekton_template.go
  backend/src/apiserver/template/template.go
  backend/src/common/client/api_server/run_client.go
  backend/src/common/util/template_util.go
  backend/test/integration/pipeline_api_test.go
  backend/test/integration/pipeline_version_api_test.go
  backend/test/integration/upgrade_test.go
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  go.mod
  go.sum
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-release.yaml
  tekton-catalog/any-sequencer/go.mod
  tekton-catalog/any-sequencer/go.sum
  tekton-catalog/pipeline-loops/go.mod
Labels: approved, lgtm, size/L

#1203 chore(release): Add backend 1.6.4 release
  Makefile
  README.md
  VERSION
  guides/kfp_tekton_install.md
  install/v1.6.4/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  sdk/README.md
Labels: approved, lgtm, size/XXL

#1204 chore(cleanup): Remove deprecated api directory
  api/.gitignore
  api/Makefile
  api/README.md
  api/go.mod
  api/go.sum
  api/v2alpha1/cache_key.proto
  api/v2alpha1/go/cachekey/cache_key.pb.go
  api/v2alpha1/go/pipelinespec/pipeline_spec.pb.go
  api/v2alpha1/pipeline_spec.proto
  api/v2alpha1/python/kfp/pipeline_spec/__init__.py
  api/v2alpha1/python/setup.py
  guides/kfp-rebase-guide.md
Labels: approved, lgtm, size/XXL

#1205 chore(samples): Remove deprecated samples
  samples/README.md
  samples/titanic-ml-dataset/data/test.csv
  samples/titanic-ml-dataset/data/train.csv
  samples/titanic-ml-dataset/requirements.txt
  samples/titanic-ml-dataset/titanic-ml.py
  samples/watson-train-serve/README.md
  samples/watson-train-serve/watson_train_serve_pipeline.py
Labels: approved, lgtm, size/XXL

#1206 fix(sdk): Update sdk to 1.6.5 with new kfp 1.8.20 to address kubernetes cves
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
  sdk/python/tests/compiler/k8s_helper_tests.py
Labels: approved, lgtm, size/S

#1207 fix(python): Remove python 3.7 support
  .github/workflows/kfp-tekton-unittests.yml
  backend/update_requirements.sh
  guides/advanced_user_guide.md
  sdk/README.md
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/setup.py
Labels: approved, lgtm, size/S

#1208 Properly add WhenExpress to handle condition
  backend/src/v2/compiler/tektoncompiler/container.go
  backend/src/v2/compiler/tektoncompiler/dag.go
  backend/src/v2/compiler/tektoncompiler/tekton.go
Labels: size/M

#1209 chore(samples): Update data passing samples to a more meaningful folder
  samples/data-passing-conformance/README.md
  samples/data-passing-conformance/data_passing.py
Labels: approved, lgtm, size/S

#1211 fix(backend): Use childReference instead of taskRuns
  backend/src/agent/persistence/worker/metrics_reporter.go
  backend/src/common/util/workflow.go
Labels: approved, lgtm, size/M

#1213 chore(requirements.txt): Remove unused lock files to better scan security vulnerability
  backend/requirements.txt
  sdk/python/requirements.txt
Labels: approved, lgtm, size/L

#1214 chore(release): Add backend 1.6.5 release
  Makefile
  VERSION
  guides/kfp_tekton_install.md
  install/v1.6.5/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
Labels: approved, lgtm, size/XXL

#1215 feat(backend):Update backend to support Tekton 0.47
  README.md
  backend/src/cache/server/watcher.go
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  go.mod
  go.sum
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-dashboard/tekton-dashboard-release.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-config.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-release.yaml
  sdk/README.md
  sdk/python/README.md
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/XXL

#1216 fix(backend): Fix integration test template object bugs
  backend/test/integration/pipeline_api_test.go
  backend/test/integration/pipeline_version_api_test.go
  backend/test/integration/upgrade_test.go
Labels: approved, lgtm, size/XS

#1218 chore(docs): Remove inactive community links
  README.md
Labels: approved, lgtm, size/XS

#1217 fix(test): update ibmcloud command
  .tekton/task.yaml
  scripts/deploy/iks/build-image-dind.sh
  scripts/deploy/iks/build-image.sh
  scripts/deploy/iks/deploy-dind.sh
  scripts/deploy/iks/deploy-kfp.sh
  scripts/deploy/iks/deploy-tekton.sh
  scripts/deploy/iks/e2e-test.sh
  scripts/deploy/iks/publish-image.sh
  scripts/deploy/iks/run-test.sh
  scripts/deploy/iks/undeploy-kfp.sh
  scripts/deploy/iks/undeploy-tekton.sh
Labels: approved, lgtm, size/S
