Repository kubeflow/kfp-tekton, pull requests merged in 2023-01, with the labels that each got.

#1114 fix(sdk): Update custom task arg parsing for dash arguments
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/custom_task_dash_args.py
  sdk/python/tests/compiler/testdata/custom_task_dash_args.yaml
Labels: approved, lgtm, size/L

#1117 chore(release): Add 1.4.1 release patch
  Makefile
  VERSION
  guides/kfp_tekton_install.md
  install/v1.4.1/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
Labels: approved, lgtm, size/XXL

#1118 chore(release): Add 1.5.0 release patch
  Makefile
  VERSION
  guides/kfp_tekton_install.md
  install/v1.5.0/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/setup.py
Labels: approved, lgtm, size/XXL

#1123 chore(backend): Update Tekton version to 0.43.2
  backend/src/agent/persistence/client/workflow_client.go
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  go.mod
  go.sum
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-dashboard/tekton-dashboard-release.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-release.yaml
Labels: approved, lgtm, size/XXL

#1119 Feat(pipelineloop): upgrade to tekton version 0.43.2, tekton v1beta1 customRun .
  backend/src/agent/persistence/client/workflow_client.go
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelineloop_range_test.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
  tekton-catalog/pipeline-loops/test/controller.go
Labels: approved, lgtm, size/XXL

#1127 chore(sdk): Update sdk requirement packages
  sdk/python/requirements.txt
Labels: approved, lgtm, size/XS

#1128 chore(sdk): Update sdk comments
  sdk/python/kfp_tekton/compiler/_tekton_handler.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/k8s_client_helper.py
Labels: approved, lgtm, size/M

#1131 Revert "Feat(pipelineloop): upgrade to tekton version 0.43.2, tekton v1beta1 customRun ."
  backend/src/agent/persistence/client/workflow_client.go
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelineloop_range_test.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
  tekton-catalog/pipeline-loops/test/controller.go
Labels: approved, lgtm, size/XXL

#1132 fix(backend): Add securitycontext for k8s 1.25
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/500-controller.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/500-webhook.yaml
Labels: approved, lgtm, size/S

#1133 chore(release): add 1.5.1 release patch
  Makefile
  VERSION
  guides/kfp_tekton_install.md
  install/v1.5.1/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  sdk/python/kfp_tekton/__init__.py
  sdk/python/setup.py
Labels: approved, lgtm, size/XXL

#1134 fix(sdk): add command to resource op spec
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/volume_op.yaml
Labels: approved, lgtm, size/S

#1135 fix(backend): Add format arg to printf command
  backend/src/cache/server/mutation.go
Labels: approved, lgtm, size/XS

#1136 Revert "Revert "Feat(pipelineloop): upgrade to tekton version 0.43.2, tekton v1beta1 customRun .""
  backend/src/agent/persistence/client/workflow_client.go
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_types.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelineloop_range_test.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
  tekton-catalog/pipeline-loops/test/controller.go
Labels: approved, lgtm, size/XXL

#1137 Fix(pipelineloop): Manifest flag patch and api version change for pipelineloop
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/201-clusterrole.yaml
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-config.yaml
  tekton-catalog/pipeline-loops/config/201-clusterrole.yaml
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelineloop_range_test.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/M
