Repository kubeflow/kfp-tekton, pull requests merged in 2023-05, with the labels that each got.

#1220 feat(manifest): Add openshift pipelines kustomize integration
  guides/kfp_tekton_install.md
  images/openshift-pipelines.png
  install/v1.6.5/kfp-tekton.yaml
  manifests/kustomize/env/kfp-template-openshift-pipelines/kustomization.yaml
  manifests/kustomize/env/kfp-template-openshift-pipelines/namespace.yaml
  manifests/kustomize/env/kfp-template-openshift-pipelines/scheduled-workflow-crd.yaml
  manifests/kustomize/env/kfp-template-openshift-pipelines/viewer-crd.yaml
  manifests/kustomize/third-party/openshift-pipelines-custom-task/kustomization.yaml
  manifests/kustomize/third-party/openshift/standalone/anyuid-scc.yaml
  manifests/kustomize/third-party/openshift/standalone/privileged-scc.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/201-clusterrole.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/201-role.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/300-pipelineloop.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/301-breaktask.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/500-controller.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/500-webhook.yaml
Labels: approved, lgtm, size/L

#1222 fix(backend): add license files
  tekton-catalog/cache/LICENSE
  tekton-catalog/cache/VERSION
  tekton-catalog/objectstore/LICENSE
  tekton-catalog/objectstore/VERSION
  tekton-catalog/pipeline-loops/LICENSE
  tekton-catalog/pipeline-loops/VERSION
Labels: approved, lgtm, size/XL

#1221 feat(backend): Add metadata field to scheduled workflow
  backend/src/apiserver/template/tekton_template.go
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow.go
  backend/src/crd/pkg/apis/scheduledworkflow/v1beta1/types.go
  backend/src/crd/pkg/apis/scheduledworkflow/v1beta1/zz_generated.deepcopy.go
  sdk/python/requirements.in
  sdk/python/setup.py
Labels: approved, lgtm, size/S

#1225 v2: support static loop
  backend/src/v2/compiler/tektoncompiler/container.go
  backend/src/v2/compiler/tektoncompiler/dag.go
  backend/src/v2/compiler/tektoncompiler/tekton.go
  backend/src/v2/compiler/tektoncompiler/tekton_test.go
  backend/src/v2/compiler/tektoncompiler/testdata/condition_ir.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/loop_static_ir.yaml
  backend/src/v2/controller/run.go
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  backend/third_party_licenses/tekton-driver.csv
  backend/third_party_licenses/tekton-exithandler-controller.csv
  backend/third_party_licenses/tekton-exithandler-webhook.csv
  backend/third_party_licenses/viewer.csv
  go.mod
  go.sum
Labels: size/XXL

#1224 fix(backend): Fix global cache flag
  backend/src/apiserver/common/config.go
  backend/src/apiserver/template/tekton_template.go
Labels: approved, lgtm, size/S

#1229 fix(manifests): fix unsaved kustomization.yaml for openshift pipelines
  manifests/kustomize/env/kfp-template-openshift-pipelines/kustomization.yaml
Labels: approved, lgtm, size/XS

#1233 v2: update images
  manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml
  manifests/kustomize/env/platform-openshift-pipelines/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
Labels: size/S

#1230 feat(manifests): opt-out sidecar injection feature flag to increase performance
  guides/kfp_tekton_install.md
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-config.yaml
Labels: approved, lgtm, size/XS

#1235 fix(sdk): Update kfp version to fix appengine bug
  sdk/python/README.md
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
  sdk/python/tests/test_kfp_samples.sh
Labels: approved, lgtm, size/S

#1234 fix(sdk): Update wait_for_run_completion function to handle tekton status;
  sdk/python/kfp_tekton/_client.py
Labels: approved, lgtm, size/M

#1239 fix(manifests): Update manifests to make it work on both k8s and openshift
  guides/kfp_tekton_install.md
  install/v1.6.5/kfp-tekton.yaml
  install/v1.6.6/kfp-tekton.yaml
  install/v1.7.0/kfp-tekton.yaml
  manifests/kustomize/third-party/openshift-pipelines-custom-task/kustomization.yaml
  manifests/kustomize/third-party/openshift-pipelines-custom-task/pipelineloop-controller-patch.yaml
  manifests/kustomize/third-party/openshift-pipelines-custom-task/pipelineloop-webhook-patch.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/500-controller.yaml
  manifests/kustomize/third-party/tekton-custom-task/pipeline-loops/500-webhook.yaml
Labels: approved, lgtm, size/M

#1241 chore(sdk): bump kfp sdk version to 1.8.22
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
Labels: approved, lgtm, size/XS

#1243 v2: fix kfp driver
  backend/src/v2/compiler/tektoncompiler/container.go
  backend/src/v2/compiler/tektoncompiler/dag.go
  manifests/kustomize/env/platform-agnostic-tekton/kustomization.yaml
  manifests/kustomize/env/platform-openshift-pipelines/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
Labels: size/S

#1246 v2: support platform spec
  backend/src/apiserver/template/v2_template.go
  backend/src/v2/compiler/tektoncompiler/container.go
  backend/src/v2/compiler/tektoncompiler/tekton.go
  backend/src/v2/compiler/tektoncompiler/tekton_test.go
  backend/src/v2/controller/run.go
  samples/v2/pipeline_with_secret_as_env.py
  samples/v2/pipeline_with_secret_as_volume.py
Labels: size/L

#1247 feat(backend): Use Informer in persistence agent
  backend/src/agent/persistence/client/workflow_client.go
  backend/src/agent/persistence/persistence_agent.go
Labels: approved, lgtm, size/L

#1244 feat(backend): Optimize persistence agent to pass yaml directly to db and minio client
  backend/Dockerfile.persistenceagent
  backend/src/agent/persistence/client/client_manager.go
  backend/src/agent/persistence/client/pipeline_client.go
  backend/src/agent/persistence/main.go
  backend/third_party_licenses/persistence_agent.csv
  manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
Labels: approved, lgtm, size/XL

#1249 chore(docs): Update kfp_tekton_install.md with new compatibility map
  guides/kfp_tekton_install.md
Labels: approved, lgtm, size/S
