Repository kubeflow/kfp-tekton, pull requests merged in 2023-02, with the labels that each got.

#1139 Custom run migration for examples of PipelineLoop custom task.
  tekton-catalog/pipeline-loops/config/500-controller.yaml
  tekton-catalog/pipeline-loops/config/500-webhook.yaml
  tekton-catalog/pipeline-loops/examples/pipelinespec-with-run-arrary-value.yaml
  tekton-catalog/pipeline-loops/examples/pipelinespec-with-run-condition.yaml
  tekton-catalog/pipeline-loops/examples/pipelinespec-with-run-dict-value.yaml
  tekton-catalog/pipeline-loops/examples/pipelinespec-with-run-iterate-numeric.yaml
  tekton-catalog/pipeline-loops/examples/pipelinespec-with-run-string-value.yaml
  tekton-catalog/pipeline-loops/examples/simplepipelineloop.yaml
  tekton-catalog/pipeline-loops/examples/simplepipelineloop_taskspec.yaml
  tekton-catalog/pipeline-loops/go.mod
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/controller.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelineloop_range_test.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun_test.go
Labels: approved, lgtm, size/XL

#1140 fix(tests): update e2e tests with new api commands
  scripts/deploy/iks/test-cache.sh
  scripts/deploy/iks/test-condition-depend.sh
  scripts/deploy/iks/test-flip-coin.sh
  scripts/deploy/iks/test-many-edges.sh
  scripts/deploy/iks/test-trusted-ai.sh
Labels: approved, lgtm, size/M

#1141 Feat(pipelineloop): Migration guide for migrating from v1alpha1.Run t…
  guides/Custom-run-migration-guide.md
  tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go
Labels: approved, lgtm, size/L

#1142 fix(pipelineloop): Update security context with group id
  tekton-catalog/pipeline-loops/config/500-controller.yaml
  tekton-catalog/pipeline-loops/config/500-webhook.yaml
Labels: approved, lgtm, size/M

#1145 feat(sdk): Add env support for podtemplate in sdk
  guides/advanced_user_guide.md
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/kfp_tekton/compiler/pipeline_utils.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/tekton_pipeline_conf.py
  sdk/python/tests/compiler/testdata/tekton_pipeline_conf.yaml
Labels: approved, lgtm, size/M

#1147 chore(manifests): Fix broken github link
  manifests/kustomize/third-party/tekton/README.md
Labels: approved, lgtm, size/XS

#1152 Feat(pipelineloop-cli): support customruns validation as well.
  .github/workflows/kfp-tekton-unittests.yml
  Makefile
  tekton-catalog/pipeline-loops/Makefile
  tekton-catalog/pipeline-loops/cmd/cli/main.go
Labels: approved, lgtm, size/M

#1153 feat(sdk): Add task workspace support
  guides/advanced_user_guide.md
  sdk/python/kfp_tekton/compiler/_op_to_template.py
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/testdata/tekton_pipeline_conf.py
  sdk/python/tests/compiler/testdata/tekton_pipeline_conf.yaml
Labels: approved, lgtm, size/M

#1159 fix(sdk): optimize find item search for large amount of params
  sdk/python/kfp_tekton/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/compiler_perf.py
  sdk/python/tests/compiler/testdata/compiler_perf.yaml
Labels: approved, lgtm, size/XXL

#1157 chore(release): Update release version to 1.6.0
  Makefile
  VERSION
  guides/kfp_tekton_install.md
  install/v1.6.0/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/setup.py
Labels: approved, lgtm, size/XXL

#1160 chore(test): add python 3.10 into github actions
  .github/workflows/kfp-tekton-unittests.yml
Labels: approved, lgtm, size/S

#1161 fix(backend): Add the permissions to access customruns
  manifests/kustomize/base/installs/multi-user/api-service/cluster-role.yaml
  manifests/kustomize/base/installs/multi-user/persistence-agent/cluster-role.yaml
  manifests/kustomize/base/installs/multi-user/scheduled-workflow/cluster-role.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-role.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-role.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-role.yaml
Labels: approved, lgtm, size/XS

#1162 Chore(backend) update kube and python dependency for backend
  .github/workflows/kfp-tekton-unittests.yml
  backend/Dockerfile
Labels: approved, lgtm, size/XS

#1165 Chore(release): Add 1.6.1 release patch
  Makefile
  VERSION
  guides/kfp_tekton_install.md
  install/v1.6.1/kfp-tekton.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/third-party/tekton-custom-task/kustomization.yaml
  sdk/python/README.md
  sdk/python/kfp_tekton/__init__.py
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
Labels: approved, lgtm, size/XXL

#1166 chore(sdk): update package dependency source
  sdk/python/kfp_tekton/__init__.py
  sdk/python/setup.py
Labels: approved, lgtm, size/S

#1167 fix(backend): proper handle customrun status
  backend/src/agent/persistence/client/workflow_client.go
Labels: approved, lgtm, size/M

#1168 chore(manifests): Update embedded status to minimal
  manifests/kustomize/third-party/tekton/upstream/manifests/base/tektoncd-install/tekton-config.yaml
Labels: approved, lgtm, size/XS

#1171 fix(test): call kfp api instead of kube api
  sdk/python/tests/verify_result.py
Labels: approved, lgtm, size/S
